changelog.txt, realm/src/androidTest/java/io/realm/RealmResultsTest.java, realm/src/main/java/io/realm/RealmResults.java
Added unit test for capturing missing functionality + improved error message for bug reported here: 
https://github.com/realm/realm-java/issues/709
@bmunkholm @emanuelez @kneth
=> Improve error message for sorting by child object

changelog.txt, examples/introExample/src/main/java/io/realm/examples/intro/IntroExampleActivity.java, experimental/pathExperiment/src/main/java/io/realm/path/AddPersonJob.java, realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm/src/androidTest/java/io/realm/NotificationsTest.java, realm/src/androidTest/java/io/realm/RealmResultsIteratorTests.java, realm/src/androidTest/java/io/realm/RealmTest.java, realm/src/main/java/io/realm/Realm.java
Also adds static constructors based on File instead of Context
=> Remove the static constructors exposing autoRefresh

changelog.txt, realm-jni/src/util.cpp
=> Revert the support for lenient UTF conversion

changelog.txt, realm/src/androidTest/java/io/realm/NotificationsTest.java, realm/src/androidTest/java/io/realm/RealmListTest.java, realm/src/main/java/io/realm/RealmList.java
Fixes to RealmList.remove(), RealmList.first() and RealmList.last() found during review + additional unit tests to capture errors.
@bmunkholm @kneth @emanuelez
=> Small API fixes

realm-jni/build.gradle
=> Update core to 0.87.5

LICENSE
@bmunkholm @timanglade @kneth @cmelchior
=> Update the licence file for encryption

realm-jni/build.gradle
=> Update core to 0.88.0

distribution/RealmEncryptionExample/app/build.gradle, examples/encryptionExample/build.gradle, examples/encryptionExample/src/main/java/io/realm/examples/encryptionexample/EncryptionExampleActivity.java
Also relax the minSdk requirements
=> Simplify the encryption example

realm/src/main/java/io/realm/RealmObject.java
=> Update isValid Javadoc to specify behaviour for stand alone objects.

changelog.txt, realm/src/main/java/io/realm/Realm.java
Changelog:
* Made migrations and compression methods synchronised
=> Make migrations and compression methods synchronised

examples/threadExample/src/main/java/io/realm/examples/threads/AsyncTaskFragment.java
=> Reduce the sleep to 25 ms in the thread example as a temporary fix

changelog.txt, realm-jni/src/io_realm_internal_TableQuery.cpp, realm-jni/src/io_realm_internal_TableQuery.h, realm/src/androidTest/java/io/realm/RealmQueryTest.java, realm/src/main/java/io/realm/RealmQuery.java, realm/src/main/java/io/realm/internal/TableQuery.java
@bmunkholm @emanuelez @cmelchior
=> Added RealmQuery.not() to negate a query condition.

realm-jni/src/io_realm_internal_LinkView.cpp, realm-jni/src/io_realm_internal_Row.cpp, realm-jni/src/util.cpp, realm-jni/src/util.hpp, realm/src/androidTest/java/io/realm/RealmListTest.java, realm/src/androidTest/java/io/realm/RealmTest.java, realm/src/main/java/io/realm/RealmList.java
Parameter checking is better done at the JNI layer (C++) since these methods might be used from different parts of the Realm framework. 
As a bonus, tracing has been added to `LinkView` and `Row` C++ methods.
@emanuelez @cmelchior
=> Parameter checking of LinkView methods in C++

examples/threadExample/src/main/java/io/realm/examples/threads/AsyncTaskFragment.java, examples/threadExample/src/main/res/layout/fragment_asynctask.xml
The thread example showcased some very bad behaviour by having a write transaction lasting 5 seconds. This blocks other threads from doing writes and could cause ANR on the UI thread.
=> Thread example no longer has too long write transactions

realm/build.gradle, realm/src/main/java/io/realm/Realm.java, realm/src/main/java/io/realm/RealmList.java, realm/src/main/java/io/realm/RealmMigration.java
=> Fix JavaDoc generation.

changelog.txt, realm-jni/src/io_realm_internal_LinkView.cpp, realm-jni/src/util.hpp, realm/src/androidTest/java/io/realm/RealmListTest.java, realm/src/androidTest/java/io/realm/RealmResultsTest.java, settings.gradle
Fix for bug reported here: https://github.com/realm/realm-java/issues/875
Also made error message output a bit more relevant info.
@kneth @emanuelez @bmunkholm
=> Bugfix for removing last element in RealmList

changelog.txt, realm-annotations-processor/src/main/java/io/realm/processor/RealmJsonTypeHelper.java, realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java, realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java, realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java, realm/src/androidTest/java/io/realm/RealmJsonTest.java
This PR fixes support for fields with explicit NULL with wasn't working correctly due to a faulty unit test.
=> Fix support for Json NULL values

realm/src/main/java/io/realm/Realm.java
=> Fix javadoc issues

realm/src/main/java/io/realm/RealmResults.java
@link tags have been corrected in RealmResults.java
=> Fixed RealmResults javadoc issues

changelog.txt, realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java, realm-annotations-processor/src/test/resources/some/test/AllTypes.java
Fixes https://github.com/realm/realm-java/issues/855
@bmunkholm @emanuelez @kneth
=> Allow static fields

changelog.txt, realm-annotations-processor/build.gradle
=> Always update the Version file for the annotation processor

realm/src/androidTest/java/io/realm/RealmTest.java, realm/src/androidTest/java/io/realm/entities/OwnerPrimaryKey.java, realm/src/main/java/io/realm/Realm.java
This solves an issue occurring when trying to update a Realm backed
object.
=> Make Realm.getTable(class) work with proxy classes as well.

realm/src/main/java/io/realm/internal/Group.java
Fixes wrong error message described in https://github.com/realm/realm-java/issues/917
=> Improved error message for unknown tables

changelog.txt, realm-jni/build.gradle, realm/src/androidTest/java/io/realm/RealmTest.java, realm/src/main/java/io/realm/Realm.java
=> Core bumped to 0.88.6

realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java, realm-annotations-processor/src/test/java/io/realm/processor/RealmProcessorTest.java, realm-annotations-processor/src/test/resources/some/test/CustomAccessor.java
=> Better error reporting for custom getters and setters

changelog.txt, realm/src/androidTest/java/io/realm/RealmTest.java, realm/src/main/java/io/realm/Realm.java
Fixes https://github.com/realm/realm-java/issues/961
=> Realms are now only cached if correctly opened.

changelog.txt, realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java, realm/src/androidTest/java/io/realm/RealmMigrationTests.java
=> validateTable now also verifies that primary key and index

README.md
Fixes #1052 
Especially the SNAPSHOT description was missing since I have been pointing a lot of people to that lately in order to test bug fixes.
@bmunkholm @timanglade @emanuelez @kneth
=> Added quick guide to using Realm with gradle.

README.md
=> Updated readme to be similar to contact page

changelog.txt, realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java, realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java, realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java, realm/src/androidTest/java/io/realm/RealmMigrationTests.java, realm/src/main/java/io/realm/Realm.java, realm/src/main/java/io/realm/exceptions/RealmMigrationNeededException.java, realm/src/main/java/io/realm/internal/ImplicitTransaction.java, realm/src/main/java/io/realm/internal/SharedGroup.java
Fixes #1060 
@emanuelez @kneth @zaki50
=> RealmMigrationNeededException can now return the path to the Realm

changelog.txt, realm-jni/build.gradle, realm-jni/src/util.hpp, realm/src/androidTest/java/io/realm/RealmTest.java, realm/src/androidTest/java/io/realm/internal/JNIImplicitTransactionsTest.java
This is required for #1038.
@bmunkholm @emanuelez @cmelchior
=> Updating to Realm Core 0.89.1

gradle/wrapper/gradle-wrapper.properties, realm-annotations-processor/gradle/wrapper/gradle-wrapper.properties, realm-annotations/gradle/wrapper/gradle-wrapper.properties, realm-jni/gradle/wrapper/gradle-wrapper.properties
=> Update Gradle to version 2.4

changelog.txt, realm/src/androidTest/java/io/realm/RealmAdapterTest.java, realm/src/main/java/io/realm/RealmBaseAdapter.java
=> Accept null RealmResults for RealmBaseAdapter. refs #1086

realm-jni/src/io_realm_internal_table.cpp
=> Killing compilation warning

realm/src/main/java/io/realm/RealmQuery.java
=> Added sorting and caseInsensitive limitations to JavaDoc.

changelog.txt, realm/src/androidTest/java/io/realm/NotificationsTest.java, realm/src/main/java/io/realm/Realm.java
Weak references on a same object are not same.
=> Do remove the RealmChangeListener weak reference

realm/src/main/java/io/realm/Realm.java
=> Lazily create the toRemoveList

examples/encryptionExample/src/main/java/io/realm/examples/encryptionexample/EncryptionExampleActivity.java
Change `Random` to `SecureRandom` to generate encryption key.
I guess it is better as example.
=> Change `Random` to `SecureRandom` to generate encryption key

realm/src/main/java/io/realm/Realm.java
Fixes #1176 
@kneth @emanuelez @nhachicha
=> Specified Realm.copyToRealm behaviour 

realm/src/main/java/io/realm/internal/android/DebugAndroidLogger.java, realm/src/main/java/io/realm/internal/android/ReleaseAndroidLogger.java, realm/src/main/java/io/realm/internal/log/RealmLog.java
Fixes inital log level for DebugAndroidLogger and ReleaseAndroidLogger.
Also fixes logging with multiple loggers.
=> Fixes loggers

realm-annotations/src/main/java/io/realm/annotations/RealmModule.java, realm/src/main/java/io/realm/Realm.java, realm/src/main/java/io/realm/RealmConfiguration.java
This fixes all current JavaDoc errors preventing CI from releasing.
@emanuelez @nhachicha @kneth
=> Fix JavaDoc errors.

realm-jni/build.gradle, realm/src/main/java/io/realm/Realm.java, realm/src/main/java/io/realm/internal/Context.java, realm/src/main/java/io/realm/internal/FinalizerRunnable.java, realm/src/main/java/io/realm/internal/LinkView.java, realm/src/main/java/io/realm/internal/NativeObject.java, realm/src/main/java/io/realm/internal/NativeObjectReference.java, realm/src/main/java/io/realm/internal/Row.java, realm/src/main/java/io/realm/internal/Table.java
=> Use phantom references to manage the closing of row accessors

examples/adapterExample/src/main/java/io/realm/examples/realmadapters/AdapterExampleActivity.java, examples/encryptionExample/src/main/java/io/realm/examples/encryptionexample/EncryptionExampleActivity.java, examples/gridViewExample/src/main/java/io/realm/examples/realmgridview/CityAdapter.java, examples/gridViewExample/src/main/java/io/realm/examples/realmgridview/GridViewExampleActivity.java, examples/introExample/src/main/java/io/realm/examples/intro/IntroExampleActivity.java, examples/jsonExample/src/main/java/io/realm/examples/json/JsonExampleActivity.java, examples/kotlinExample/src/main/java/io/realm/examples/kotlin/KotlinExampleActivity.kt, examples/threadExample/src/main/AndroidManifest.xml, examples/threadExample/src/main/java/io/realm/examples/threads/AsyncTaskFragment.java, examples/threadExample/src/main/java/io/realm/examples/threads/MyApplication.java, examples/threadExample/src/main/java/io/realm/examples/threads/ThreadFragment.java
Examples has been updated to use RealmConfiguration
Note: MigrationExample has not been converted yet as that example has showcased an error in the RealmConfiguration logic. This will be fixed in a separate PR.
@emanuelez @nhachicha @kneth
=> Updated examples with RealmConfiguration

changelog.txt, realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java, realm-annotations-processor/src/main/java/io/realm/processor/Utils.java, realm-annotations-processor/src/test/java/io/realm/processor/RealmProcessorTest.java, realm-annotations-processor/src/test/resources/some/test/MissingGenericType.java
Closes #1131.
@emanuelez @cmelchior @nhachicha
=> Checking for missing generic type during annotation processing

changelog.txt, realm/src/androidTest/java/io/realm/RealmTest.java, realm/src/main/java/io/realm/internal/FinalizerRunnable.java
=> fix memory leak issue with the FinalizerRunnable

changelog.txt, realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java, realm-annotations-processor/src/test/java/io/realm/processor/RealmProcessorTest.java, realm/src/androidTest/java/io/realm/RealmAnnotationTest.java, realm/src/androidTest/java/io/realm/RealmMigrationTests.java
=> Index primary key

examples/realmModuleExample/app/proguard-rules.pro
=> Keep RealmModule class from being obfuscated

realm/src/androidTest/java/io/realm/RealmMigrationTests.java
=> Check that the right exception is thrown

realm-annotations-processor/src/main/java/io/realm/processor/RealmAnalytics.java, realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java
=> Ignore errors in analytics BG thread and allow disabling it

changelog.txt, realm/src/main/java/io/realm/internal/RealmCore.java
Otherwise it might cause #1350
=> loadLibrary should be a synchronized operation

examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java
Hi, I fixed typo of Migration.java commet.
=> Fixed typo of migration example code.

realm/src/androidTest/java/io/realm/RealmTest.java
@realm/java Strange, why didn't it crash on CI before?
=> Test case fix

realm/build.gradle
=> Add the license file to the distribution package

LICENSE, README.md
Same as https://github.com/realm/realm-cocoa/pull/2440./cc @timanglade
=> [README][LICENSE] added Crimea to list of prohibited regions

examples/gridViewExample/src/main/java/io/realm/examples/realmgridview/GridViewExampleActivity.java
=> Removed excessive calls to getInstance in GridViewExample

realm/src/androidTest/java/io/realm/RealmTest.java, realm/src/main/java/io/realm/Realm.java
=> Fixes Process listeners after refresh()

changelog.txt, realm-jni/build.gradle, realm-jni/src/io_realm_internal_Util.cpp, realm-jni/src/util.cpp, realm-jni/src/util.hpp, realm/src/main/java/io/realm/Realm.java, realm/src/main/java/io/realm/RealmConfiguration.java, realm/src/main/java/io/realm/exceptions/RealmEncryptionNotSupportedException.java, realm/src/main/java/io/realm/internal/Util.java
=> Add RealmEncryptionNotSupportedException

realm/src/androidTest/java/io/realm/RealmTest.java, realm/src/main/java/io/realm/Realm.java
=> add fix for #1466

realm/src/androidTest/java/io/realm/RealmMigrationTests.java
Testing Table.addSearchIndex() is idempotent. Closes #1385
@cmelchior
=> Testing Table.addSearchIndex() is idempotent

realm/src/main/java/io/realm/Realm.java
In order to make more clear the purpose of this method.
@realm/java @bmunkholm @timanglade
=> Updated Javadoc for getInstance(context)

changelog.txt, realm/src/androidTest/java/io/realm/RealmTest.java, realm/src/main/java/io/realm/BaseRealm.java
=> Add Realm.isClose() method.

realm/src/androidTest/java/io/realm/RealmTest.java, realm/src/main/java/io/realm/BaseRealm.java
@realm/java review this please.
=> Fix BaseRealm#checkIfValid() which does not throw Exception after close().

realm/src/main/java/io/realm/Realm.java
=> Remove empty override method

gradle-plugin/buildSrc/build.gradle
It's a very simple patch. @realm/java
=> mavenCentral -> jcenter

changelog.txt
=> Change version number to 0.83.1 in changelog.txt

changelog.txt, realm/src/androidTest/java/io/realm/RealmListTest.java, realm/src/androidTest/java/io/realm/RealmQueryTest.java, realm/src/androidTest/java/io/realm/RealmResultsTest.java, realm/src/main/java/io/realm/RealmList.java, realm/src/main/java/io/realm/RealmQuery.java, realm/src/main/java/io/realm/RealmResults.java
=> Add isValid() to RealmList, RealmResults, RealmQuery

realm/src/main/java/io/realm/RealmObject.java, realm/src/main/java/io/realm/internal/Table.java
=> Javadoc correction

changelog.txt
=> fix typo in chagelog.txt

README.md, realm-jni/build.gradle, realm-jni/gradle.properties
@realm/java I made a simple patch to supports `ANDROID_NDK`. Please help to review.
=> Support environment variable, path ends with / and determining the right NDK version.

realm/src/androidTest/java/io/realm/RealmConfigurationTest.java
=> fix ambiguous null to variable length arguments.

changelog.txt
@realm/java please review this.
=> Rephrasing items in changelog.txt

README.md
=> Add a description how to install android-ndk r10d.

changelog.txt, realm/src/androidTest/java/io/realm/RealmAnnotationTest.java, realm/src/androidTest/java/io/realm/internal/JNITransactions.java, realm/src/main/java/io/realm/exceptions/RealmPrimaryKeyConstraintException.java, realm/src/main/java/io/realm/internal/Table.java
=> Add RealmPrimaryKeyConstraintException.

realm/src/main/java/io/realm/RealmQuery.java
=> fix parameter name of RealmQuery constructor

README.md
Explain how to use homebrew-versions to install ANDROID-NDK r10d.
=> Update README.md. (homebrew-versions)

realm/src/androidTest/java/io/realm/RealmTest.java
test for #1581
I'm not sure that we should have this test in realm-java since it seems to be just testing the core.
What do you think @realm/java ?
=> Add test to open Realm database after compactRealm

realm-jni/build.gradle
=> Parallelize make jobs

realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java, realm-annotations-processor/src/main/templates/Version.java
=> Apply soft tabs for consistency.

changelog.txt, examples/introExample/src/main/java/io/realm/examples/intro/IntroExampleActivity.java, examples/kotlinExample/src/main/java/io/realm/examples/kotlin/KotlinExampleActivity.kt, realm/src/androidTest/java/io/realm/RealmAsyncQueryTests.java, realm/src/androidTest/java/io/realm/RealmListTest.java, realm/src/androidTest/java/io/realm/RealmResultsTest.java, realm/src/androidTest/java/io/realm/RealmTest.java, realm/src/main/java/io/realm/BaseRealm.java, realm/src/main/java/io/realm/Realm.java, realm/src/main/java/io/realm/internal/ImplicitTransaction.java, realm/src/main/java/io/realm/internal/SharedGroupManager.java
Fixes #1549
see also:
https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#//api/name/inWriteTransaction
Please review @realm/java
=> Add Realm.isInTransaction() to check if it is in a transaction.

changelog.txt
=> Arrangement duplicated items in changelog.txt.

changelog.txt
It's a very small patch. I reordered items of changelog.txt.
=> Reordering items of changelog.txt to categorize according to affinity.

changelog.txt, realm-jni/build.gradle
This upgrades Core to 0.94.2
It will potentially be 0.94.3 before release.
=> Upgraded core to 0.94.3

realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java, realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java, realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java, realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java, realm/src/main/java/io/realm/internal/ColumnInfo.java
https://github.com/realm/realm-java/commit/8803c6c5d28223153a5b8cb1536925d9c6cfe6c3#commitcomment-13923801
=> reorder parameters of ColumnInfo class

README.md
=> fix example path of android-ndk

realm/src/androidTest/java/io/realm/RealmTest.java
@realm/java This test case is not slow!
=> Enable not slow test case

changelog.txt, examples/kotlinExample/build.gradle, examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/KotlinExampleActivity.kt, examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/model/Cat.kt, examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/model/Dog.kt, examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/model/Person.kt
Related to #1647 
Updates our Kotlin example to be compatible with the latest Kotlin 1.0.0-beta 
@realm/java
=> Updated Kotlin example to 1.0.0 beta

realm-annotations-processor/src/main/java/io/realm/processor/RealmVersionChecker.java
I forgot to fix comment 
https://github.com/realm/realm-java/pull/1668#discussion_r42966182
fase-merge /cc @realm/java
=> Rephrase comment

changelog.txt, realm-jni/build.gradle, realm/src/androidTest/java/io/realm/RealmQueryTest.java
Exposing regression from Realm `0.83.0` to `0.83.1`
=> Deep link query crashes cores.

realm/realm-jni/src/io_realm_internal_TableQuery.cpp
Since it is supported by core now.
https://github.com/realm/realm-core/pull/1185
=> Change to is_not_null for links

README.md
=> update README for OS X users

README.md
A small annoyance :(
@emanuelez 
@realm/java
=> Added project structure gotcha.

realm/realm-library/src/androidTest/java/io/realm/RealmTest.java
It's a very simple patch. Please review this @realm/java
=> Fix formatting.

changelog.txt
A simple fix again. Please review this @realm/java
=> Fixed a typo and reordered items.

changelog.txt, realm/realm-jni/src/io_realm_internal_TableQuery.cpp, realm/realm-jni/src/io_realm_internal_UncheckedRow.cpp, realm/realm-jni/src/io_realm_internal_table.cpp, realm/realm-jni/src/io_realm_internal_tableview.cpp, realm/realm-jni/src/util.hpp
Added missing `ReleaseLongArrayElements` and `ReleaseBooreanArrayElements` call.
=> fix potential memory leak in jni code

changelog.txt
A very simple patch. Please review this @realm/java
=> Reordered items of changelog.txt.

build.gradle
Insta-merge since it affects the publishing process. @realm/java
=> Fix the Gradle publishers

changelog.txt, realm/realm-library/src/androidTest/java/io/realm/RealmTest.java, realm/realm-library/src/main/java/io/realm/BaseRealm.java
... as the Realm is always kept up to date.
This PR is for #1712
=> Checking for transaction in Realm.refresh and throwing if inside of a Transaction

.gitignore
A very small patch. Please review this @realm/java
=> Remove an unnecessary directory of .gitignore

realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTest.java, realm/realm-library/src/androidTest/java/io/realm/NotificationsTest.java, realm/realm-library/src/androidTest/java/io/realm/RealmCacheTest.java, realm/realm-library/src/androidTest/java/io/realm/RealmTest.java, realm/realm-library/src/androidTest/java/io/realm/TestHelper.java, realm/realm-library/src/main/java/io/realm/BaseRealm.java, realm/realm-library/src/main/java/io/realm/DynamicRealm.java, realm/realm-library/src/main/java/io/realm/Realm.java, realm/realm-library/src/main/java/io/realm/RealmCache.java, realm/realm-library/src/main/java/io/realm/RealmConfiguration.java
* Add RealmCache class to cache Realm instances and related resources.
* Move cache related logic from BaseRealm, Realm, DynamicRealm to
RealmCache.
* Move some test cases to RealmCacheTest.
* Fix test cases.
Close #1735
=> RealmCache to decouple some logic from BaseRealm

examples/gridViewExample/build.gradle, examples/gridViewExample/src/main/java/io/realm/examples/realmgridview/GridViewExampleActivity.java
Testing #1821 
Workaround is still required.
@realm/java
=> Upgrade example to GSON 2.5

changelog.txt, realm/realm-jni/build.gradle
=> Updated core to 0.95.1

realm/realm-library/src/androidTest/java/io/realm/RealmQueryTest.java
=> Fixed unit tests for avg

bintrayGradlePlugin.gradle
=> Should fix the CI error

build.gradle
=> Also for OJO

changelog.txt
=> Add chengelog entries for bugs which has been fixed by core 0.95.3

changelog.txt
=> fix indentation of changelog

changelog.txt, realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java, realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
=> Added RealmObjectSchema.getFieldType

changelog.txt, examples/kotlinExample/build.gradle, realm/realm-jni/build.gradle
Upgrade Core to 0.95.5 for 0.86.1 release
@realm/java
=> Upgrade core to 0.95.5

changelog.txt
=> added issue number to changelog

changelog.txt, examples/kotlinExample/build.gradle, realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTest.java, realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java, realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java
Fixes #1912 
Fixes #1451 
@realm/java
=> Fixed DynamicRealmObject.getObject()/setObject() using the wrong table

changelog.txt, examples/gridViewExample/build.gradle
Relates to #1618. 
I'm not sure how in depth you wanted to go with the split apks. We can consider this the jump off point. 
@cmelchior @emanuelez @nhachicha What would you like to see in detail?
=> Simple, naive split apks on gridview example

realm/realm-library/src/main/java/io/realm/internal/LinkView.java, realm/realm-library/src/main/java/io/realm/internal/Table.java, realm/realm-library/src/main/java/io/realm/internal/TableView.java
Preparing to add some functionality to these classes I just did a cleanup of these classes so they match our other internal classes a bit better.
- All native methods grouped at the bottom + made private where possible
- Remove outdated Javadoc
- Small style fixes
@realm/java
=> Internal class cleanup

examples/threadExample/src/main/AndroidManifest.xml, examples/threadExample/src/main/java/io/realm/examples/threads/PassingObjectsFragment.java, examples/threadExample/src/main/java/io/realm/examples/threads/ReceivingActivity.java, examples/threadExample/src/main/java/io/realm/examples/threads/ReceivingService.java, examples/threadExample/src/main/java/io/realm/examples/threads/ThreadExampleActivity.java, examples/threadExample/src/main/java/io/realm/examples/threads/WakefulReceivingBroadcastReceiver.java, examples/threadExample/src/main/java/io/realm/examples/threads/WakefulReceivingService.java, examples/threadExample/src/main/java/io/realm/examples/threads/model/Person.java, examples/threadExample/src/main/res/layout/activity_receiving.xml, examples/threadExample/src/main/res/layout/fragment_async_query.xml, examples/threadExample/src/main/res/layout/fragment_asynctask.xml, examples/threadExample/src/main/res/layout/fragment_passing_objects.xml, examples/threadExample/src/main/res/layout/fragment_thread.xml, examples/threadExample/src/main/res/values/colors.xml, examples/threadExample/src/main/res/values/dimens.xml, examples/threadExample/src/main/res/values/strings.xml
Examples that help illustrate common uses cases that relate to  #1503
=> Adding example that shows how to pass objects via ids

changelog.txt, realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTest.java, realm/realm-library/src/androidTest/java/io/realm/RealmTest.java, realm/realm-library/src/main/java/io/realm/DynamicRealm.java, realm/realm-library/src/main/java/io/realm/Realm.java
=> Align the behavior of DynamicRealm.executeTransaction() to Realm.executeTransaction()

README.md, changelog.txt, realm.properties, realm/realm-jni/build.gradle, realm/realm-jni/project.mk
Upgrading to NDK R10e and gcc 4.9.
Superseed #1937 
@realm/java
=> Upgrading to NDK R10e and gcc 4.9

README.md, changelog.txt, realm.properties, realm/realm-jni/build.gradle, realm/realm-jni/project.mk
Merge current state on `release/0.87` branch into `master`
@realm/java
=> Pull in patch release 

realm/realm-jni/build.gradle
Upgrade Core to 0.95.7 for 0.87.1 release
=> update to Core 0.95.7

realm/realm-library/src/main/java/io/realm/internal/Table.java
=> Fix typo in documentation comment: (ndex => index)

changelog.txt, realm/realm-annotations/src/main/java/io/realm/annotations/PrimaryKey.java, realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java, realm/realm-library/src/main/java/io/realm/FieldAttribute.java, realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
=> addField PRIMARY_KEY should also apply REQUIRED

realm/realm-library/src/main/java/io/realm/BaseRealm.java, realm/realm-library/src/main/java/io/realm/DynamicRealm.java, realm/realm-library/src/main/java/io/realm/Realm.java
This relates to #1541 
I also added other throws declarations in the javadoc as to fill it out a bit more so the lib is more complete.
=> Adding @throws declarations to javadocs for BaseRealm, Realm and Dynamic Realm

realm/realm-jni/src/io_realm_internal_TableQuery.cpp, realm/realm-jni/src/io_realm_internal_TableQuery.h, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTest.java, realm/realm-library/src/main/java/io/realm/RealmQuery.java, realm/realm-library/src/main/java/io/realm/internal/TableQuery.java
Patch for [#2014](https://github.com/realm/realm-java/issues/2014)  
Test cases are done in RealmQueryTest only.
=> Support for RealmQuery.isNotEmpty() added

realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
To replace #2000 . PR on release branch and will be merged back to master.
=> Fix async test strong reference problem

realm/realm-library/src/androidTest/java/io/realm/RealmTest.java
Timing issue with testProcessLocalListenersAfterRefresh.
RealmResults should be created before trasaction. Otherwise it fails by
same TableView version.
And a minor typo fix.
=> testProcessLocalListenersAfterRefresh fix

examples/gridViewExample/src/main/java/io/realm/examples/realmgridview/GridViewExampleActivity.java
findFirst() returns RealmObject not a List.
=> Fix comment in gridViewExample

changelog.txt, realm/realm-jni/src/io_realm_internal_LinkView.cpp, realm/realm-jni/src/io_realm_internal_LinkView.h, realm/realm-jni/src/io_realm_internal_TableView.h, realm/realm-jni/src/io_realm_internal_tableview.cpp, realm/realm-library/src/androidTest/java/io/realm/RealmListTest.java, realm/realm-library/src/androidTest/java/io/realm/RealmResultsTest.java, realm/realm-library/src/main/java/io/realm/RealmList.java, realm/realm-library/src/main/java/io/realm/RealmResults.java, realm/realm-library/src/main/java/io/realm/internal/LinkView.java, realm/realm-library/src/main/java/io/realm/internal/Table.java, realm/realm-library/src/main/java/io/realm/internal/TableOrView.java, realm/realm-library/src/main/java/io/realm/internal/TableView.java
Adding jni layer interop code to utilize find method (broken currently).
Checking to ensure we're on the right Realm before performing the contains check.
=> Using core method to help improve perf of RealmList#contains()

bintrayAar.gradle, bintrayAnnotations.gradle, bintrayAnnotationsProcessor.gradle, bintrayGradlePlugin.gradle, build.gradle, changelog.txt
=> Fixed source and javadoc jars not being deployed correctly.

bintrayAar.gradle, build.gradle
=> Fix artifact name causing artifactoryPublish to fail.

build.gradle
=> Remove unused defs of build.gradle.

changelog.txt, examples/jsonExample/src/main/java/io/realm/examples/json/JsonExampleActivity.java
=> Fixed bug in jsonExample

realm/realm-library/src/main/java/io/realm/RealmResults.java
=> Fix PMD error

realm/realm-library/src/androidTest/java/io/realm/RealmQueryTest.java, realm/realm-library/src/main/java/io/realm/RealmQuery.java, realm/realm-library/src/main/java/io/realm/RealmResults.java
=> Better exception message when sort on sub object

changelog.txt, realm/config/checkstyle/checkstyle-suppressions.xml, realm/realm-jni/src/io_realm_internal_TableView.h, realm/realm-jni/src/io_realm_internal_tableview.cpp, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTest.java, realm/realm-library/src/androidTest/java/io/realm/RealmResultsTest.java, realm/realm-library/src/androidTest/java/io/realm/entities/AnnotationIndexTypes.java, realm/realm-library/src/main/java/io/realm/DynamicRealm.java, realm/realm-library/src/main/java/io/realm/Realm.java, realm/realm-library/src/main/java/io/realm/RealmQuery.java, realm/realm-library/src/main/java/io/realm/RealmResults.java, realm/realm-library/src/main/java/io/realm/internal/TableView.java
=> RealmQuery, RealmResults distinct() pt1

realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java, realm/realm-library/src/androidTest/java/io/realm/entities/NonLatinFieldNames.java
Note some tests seemed out of place. I added TODO's for those so they can be fixed later instead of making noise to this PR.
Also prefixing all tests with the method being tested seemed to catch a couple of redundant tests :smile: 
@realm/java
=> Converted RealmResultsTests to JUnit4

realm/config/checkstyle/checkstyle-suppressions.xml, realm/config/findbugs/findbugs-filter.xml, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/androidTest/java/io/realm/TestHelper.java, realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java, realm/realm-library/src/main/java/io/realm/BaseRealm.java
All RealmTests have been upgraded to the new guidelines. Especially Handler tests have all moved to RunTestInLooperThread. Hopefully this will also make them less flaky.
@realm/java
=> Moved all RealmTests to new guidelines.

realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java
Use TestRealmConfigurationFactory and fix findbugs issues/lint warnings.
=> Clean up RealmListTest

CONTRIBUTING.md
Updates CONTRIBUTING.md to accurately describe how we test for exceptions.
@realm/java
=> Clarify how to check exceptions in unit tests.

realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java, realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java
=> Converted RealmObjectTests to JUnit4

realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
Cleanup of RealmAsyncQueryTests. Mainly renaming to new pattern + simplifying a few tests using `RunTestInLooperThread`
@realm/java
=> Cleanup unit test naming and looper thread usage.

changelog.txt, realm/realm-jni/build.gradle
=> Upgrading to Realm Core 0.95.8

changelog.txt, realm/realm-jni/src/util.cpp, realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTest.java
=> Fix field name in the message of IllegalArgumentException throw by the accessors of DynamicRealmObject

realm/realm-library/src/androidTest/java/io/realm/RxJavaTests.java
@realm/java 
Done as part of investigating https://github.com/realm/realm-java/issues/1998
=> Modify RxJavaTests unit test naming to new style guide

changelog.txt, realm/realm-jni/build.gradle
=> Upgrade to Core 0.96.0

realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java
=> fix typo in RunInLooperThread.java

realm/realm-library/src/main/java/io/realm/RealmResults.java
=> corrects Javadoc comment of RealmResults#removeLast()

realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java, realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java
=> make a test of RealmObject.hashCode() path independent.

examples/threadExample/src/main/java/io/realm/examples/threads/AsyncQueryFragment.java, realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/main/java/io/realm/Realm.java
=> Using separate interfaces for async transaction also fixes #2130

CONTRIBUTING.md, realm/realm-library/src/main/java/io/realm/RealmMigration.java
I searched the repo and added the pre element to anything that did not have it. 
Fixes #2206
=> Updating contributing doc & adding pre element to missing code block

CHANGELOG.md, realm/config/checkstyle/checkstyle-suppressions.xml, realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/androidTest/java/io/realm/entities/AnnotationIndexTypes.java, realm/realm-library/src/main/java/io/realm/DynamicRealm.java, realm/realm-library/src/main/java/io/realm/Realm.java, realm/realm-library/src/main/java/io/realm/RealmQuery.java, realm/realm-library/src/main/java/io/realm/RealmResults.java, realm/realm-library/src/main/java/io/realm/internal/TableQuery.java
`distinctAsync` on `RealmQuery` and `RealmResults`.
=> RealmQuery.distinctAsync(), RealmResults.distinctAsync() support

realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java
=> reformatting RealmResultsTest

realm/realm-library/src/main/java/io/realm/Realm.java
Closes #1483
Please review @realm/java
=> Adding javadoc to document field mutation behavior of copyToRealm and  createFromJson methods.

realm/realm-library/src/androidTest/java/io/realm/RealmAnnotationTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
RealmAnnotationTest and RealmConfigurationTest.
=> Convert test case to JUNIT4

realm/config/checkstyle/checkstyle.xml, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java, realm/realm-library/src/androidTest/java/io/realm/internal/JNICloseTest.java
Prevents mistakes seen in #2284 
@realm/java
=> Added whitespace check for try

changelog.txt, realm/realm-jni/src/io_realm_internal_TableQuery.cpp, realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
=> fixes #2115 IllegalStateException Caller thread behind the worker thread

CHANGELOG.md
=> Reorder items of CHANGELOG.md and improve markdown formatting.

CHANGELOG.md, realm/realm-library/src/main/java/io/realm/Realm.java
=> Deprecate Realm.getTable(Class).

realm/realm-library/src/main/java/io/realm/rx/RealmObservableFactory.java
rxJavaAvailble -> rxJavaAvailable
=> fixed typo

CHANGELOG.md, examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/MigrationExampleActivity.java, realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java, realm/realm-library/src/androidTest/java/io/realm/TestHelper.java, realm/realm-library/src/androidTest/java/io/realm/entities/NullTypes.java, realm/realm-library/src/main/java/io/realm/BaseRealm.java, realm/realm-library/src/main/java/io/realm/Realm.java
=> migrateRealm throws when db doesn't exsit

CHANGELOG.md, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm/realm-annotations-processor/src/test/java/io/realm/processor/RealmProcessorTest.java, realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java, realm/realm-annotations-processor/src/test/resources/some/test/ConflictingFieldName.java, realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java, realm/realm-library/src/androidTest/java/io/realm/entities/ConflictingFieldName.java, realm/realm-library/src/main/java/io/realm/RealmObject.java
=> allow 'realm' and 'row' as a field name of model class. This fixes #2255

README.md
=> Update README.md for OS X users.

examples/unitTestExample/build.gradle, examples/unitTestExample/src/test/java/io/realm/examples/unittesting/ExampleActivityTest.java
#2303 
Also we need to enable `./gradlew check` on CI.
=> Fix unit test example mocks

realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy
=> Fix the iteration of JarFile in the Transformer

CHANGELOG.md
We forgot to update the changelog when https://github.com/realm/realm-java/pull/2152/files was merged.
@realm/java
=> Added notice about executeTransactionAsync

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java, realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java, realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
=> Correct checking in DynamicRealmObject.setList

CHANGELOG.md
Missing change log update for #2240 
@realm/java
/cc @grahamsmith
=> Added missing changelog update.

realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy
Realm Transformer must copy non-class files to output dir since Kotlin compiler generates `*.kotlin_module` file in `META-INF`.
This fixes #2356
=> Copy resource files when transforming byte code.

realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy
before: modify the access to fields defined in models only in target project.
after: modify the access to fields defined in all models including ones in dependencies.
Suppose `Cow` is defined in target(app) project, and `Cat` is defined in dependency project.
```
Cow cow = new Cow();
cow.setName("mooo");
realm.beginTransaction();
cow = realm.copyToRealm(cow);
realm.commitTransaction();
Cat cat = new Cat();
cat.setName("doraemon");
realm.beginTransaction();
cat = realm.copyToRealm(cat);
realm.commitTransaction();
Log.d("FOO", "cow.getName(): " + cow.getName());
Log.d("FOO", "cow.name: " + cow.name);
Log.d("FOO", "cat.getName(): " + cat.getName());
Log.d("FOO", "cat.name: " + cat.name);
```
before: 
```
FOO     : cow.getName(): mooo
FOO     : cow.name: mooo
FOO     : cat.getName(): doraemon …
```
=> transform accesses to model fields in library projects

CHANGELOG.md
I propose a new format of the changelog. I think it is easier to read when a release has multiple sections. The credit section can be used to acknowledge users who has contributed code or done testing using snapshot releases.
=> Trying out multiple sections

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/androidTest/java/io/realm/TestHelper.java, realm/realm-library/src/main/java/io/realm/RealmConfiguration.java
=> Fix NPE in RealmConfiguration.equals() when RxJava is unavailable.

realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java, realm/realm-library/src/main/java/io/realm/RealmConfiguration.java
=> Reflect hash code of rxObservableFactory in RealmConfiguration.hashCode().

CHANGELOG.md, realm/realm-jni/build.gradle
=> add SONAME header to shared libraries

examples/kotlinExample/build.gradle
=> Update Kotlin to 1.0.0

CHANGELOG.md, realm/realm-jni/src/io_realm_internal_table.cpp, realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java, realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java, realm/realm-library/src/main/java/io/realm/internal/Table.java
Now DynamicRealmObject.toString() shows null value as "null".
"class_" prefix is removed from type name in that String.
Align the format to the String from typed `RealmObject`.
This fixes #2439 
=> Fix the String from DynamicRealmObject.toString().

CHANGELOG.md
=> fix format of CHANGELOG.md

CHANGELOG.md, realm/realm-jni/build.gradle
=> Update core to 0.97.1

CHANGELOG.md, realm/realm-jni/build.gradle
=> update core to 0.97.2

CHANGELOG.md, realm/realm-jni/src/io_realm_internal_TableQuery.cpp, realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java, realm/realm-library/src/androidTest/java/io/realm/TestHelper.java, realm/realm-library/src/main/java/io/realm/BaseRealm.java, realm/realm-library/src/main/java/io/realm/HandlerController.java, realm/realm-library/src/main/java/io/realm/RealmQuery.java, realm/realm-library/src/main/java/io/realm/RealmResults.java, realm/realm-library/src/main/java/io/realm/internal/ImplicitTransaction.java, realm/realm-library/src/main/java/io/realm/internal/SharedGroup.java, realm/realm-library/src/main/java/io/realm/internal/SharedGroupManager.java, realm/realm-library/src/main/java/io/realm/internal/TableQuery.java, realm/realm-library/src/main/java/io/realm/internal/async/BadVersionException.java, realm/realm-library/src/main/java/io/realm/internal/async/RealmThreadPoolExecutor.java
Fixes #2417
Fixes #2391
Fixes #2021 
This replaces #2426 
Please review this throughly @realm/java
Copy paste from #2426 
> @nhachicha I updated the PR. We didn't properly handle BadVersionException in our findAllAsync methods from what I could tell. In a lot of cases we treated that exception as fatal (even though a retry was imminent). I think I fixed it, but still trying to wrap my head around testing it in a sane way. So far I have done manual testing but stubbing out values.
> Please review, especially around retrying and batch updates.
=> Fix BadVersionException

CHANGELOG.md, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/main/java/io/realm/BaseRealm.java, realm/realm-library/src/main/java/io/realm/Realm.java
Might be the reason of #2462 .
=> Thread check for copyToRealm/copyToRealmOrUpdate

examples/kotlinExample/build.gradle
=> Update Kotlin in example to 1.0.1

realm/realm-library/src/main/java/io/realm/RealmList.java
=> Fix RealmList.isValid Javadoc

README.md
@zaki50's android-ndk-r10e should be merged into Homebrew-versions before this PR.
=> Update README.md to use Homebrew-versions

examples/kotlinExample/build.gradle
=> Update Kotlin in example to 1.0.1-2

CHANGELOG.md, realm/realm-jni/build.gradle
Bumped core to 0.97.3
@realm/java
=> Upgraded core to 0.97.3

CHANGELOG.md, realm/realm-library/src/main/java/io/realm/Realm.java
=> Remove Realm.getTable() from public API

realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
Fixed wrong method name in exception
=> Fixed wrong method name in exception

examples/adapterExample/src/main/java/io/realm/examples/realmadapters/MyAdapter.java, examples/kotlinExample/build.gradle, examples/kotlinExample/lint.xml, examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/KotlinExampleActivity.kt, examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/model/Cat.kt, examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/model/Dog.kt, examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/model/Person.kt, examples/kotlinExample/src/main/res/layout/activity_realm_basic_example.xml, examples/kotlinExample/src/main/res/values/strings.xml
=> Fixed lint warnings in Kotlin project

examples/jsonExample/lint.xml, examples/jsonExample/src/main/res/layout/activity_realm_example.xml, examples/jsonExample/src/main/res/values/strings.xml
=> fix lint warnings in jsonExample

examples/unitTestExample/lint.xml, examples/unitTestExample/src/androidTest/java/io/realm/examples/unittesting/jUnit4ExampleTest.java, examples/unitTestExample/src/main/res/layout/activity_example.xml, examples/unitTestExample/src/main/res/values/strings.xml
=> fix lint rawnings in unitTestExample

realm/realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java, realm/realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmAnalytics.java, realm/realm-annotations-processor/src/main/java/io/realm/processor/Utils.java, realm/realm-library/src/main/java/io/realm/DynamicRealm.java, realm/realm-library/src/main/java/io/realm/FieldAttribute.java, realm/realm-library/src/main/java/io/realm/Realm.java, realm/realm-library/src/main/java/io/realm/RealmCache.java, realm/realm-library/src/main/java/io/realm/RealmConfiguration.java, realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java, realm/realm-library/src/main/java/io/realm/internal/Group.java, realm/realm-library/src/main/java/io/realm/internal/RealmProxyMediator.java, realm/realm-library/src/main/java/io/realm/internal/Table.java, realm/realm-library/src/main/java/io/realm/internal/TableOrView.java, realm/realm-library/src/main/java/io/realm/internal/TableView.java, realm/realm-library/src/main/java/io/realm/internal/android/ISO8601Utils.java, realm/realm-library/src/main/java/io/realm/internal/async/QueryUpdateTask.java
=> Fix javadoc

examples/rxJavaExample/build.gradle, examples/rxJavaExample/lint.xml, examples/rxJavaExample/src/main/AndroidManifest.xml, examples/rxJavaExample/src/main/java/io/realm/examples/rxjava/MainActivity.java, examples/rxJavaExample/src/main/java/io/realm/examples/rxjava/MyApplication.java, examples/rxJavaExample/src/main/java/io/realm/examples/rxjava/model/Person.java, examples/rxJavaExample/src/main/java/io/realm/examples/rxjava/retrofit/GitHubUser.java, examples/rxJavaExample/src/main/java/io/realm/examples/rxjava/retrofit/GithubApi.java, examples/rxJavaExample/src/main/java/io/realm/examples/rxjava/retrofit/RetrofitExample.java, examples/rxJavaExample/src/main/res/layout/activity_gotchas.xml, examples/rxJavaExample/src/main/res/layout/activity_throttlesearch.xml, examples/rxJavaExample/src/main/res/values/strings.xml
=> Fixed lint warnings in RxJava example

examples/newsreaderExample/build.gradle, examples/newsreaderExample/lint.xml, examples/newsreaderExample/src/main/java/io/realm/examples/newsreader/model/Repository.java, examples/newsreaderExample/src/main/java/io/realm/examples/newsreader/model/network/RealmListNYTimesMultimediumDeserializer.java, examples/newsreaderExample/src/main/java/io/realm/examples/newsreader/ui/details/DetailsActivity.java, examples/newsreaderExample/src/main/java/io/realm/examples/newsreader/ui/main/MainActivity.java, examples/newsreaderExample/src/main/res/layout/common_emptylist.xml, examples/newsreaderExample/src/main/res/layout/content_details.xml, examples/newsreaderExample/src/main/res/layout/spinner_dropdown_item.xml, examples/newsreaderExample/src/main/res/values/colors.xml, examples/newsreaderExample/src/main/res/values/dimens.xml, examples/newsreaderExample/src/main/res/values/strings.xml
=> fix lint warnings in newsreaderExample

examples/migrationExample/lint.xml, examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/MigrationExampleActivity.java, examples/migrationExample/src/main/res/layout/activity_realm_migration_example.xml, examples/migrationExample/src/main/res/values/strings.xml
=> fix lint warnings in migrationExample

realm-transformer/src/test/groovy/io/realm/transformer/BytecodeModifierTest.groovy
=> Add a test to verify that instance methods can be used in constructors

realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
=> RealmObjectTest increased test coverage

realm/realm-library/src/androidTest/java/io/realm/OrderedRealmCollectionTests.java, realm/realm-library/src/androidTest/java/io/realm/TestHelper.java, realm/realm-library/src/androidTest/java/io/realm/UnManagedOrderedRealmCollectionTests.java, realm/realm-library/src/androidTest/java/io/realm/UnManagedRealmCollectionTests.java, realm/realm-library/src/androidTest/java/io/realm/entities/ConflictingFieldName.java, realm/realm-library/src/androidTest/java/io/realm/entities/RealmAdapter.java, realm/realm-library/src/main/java/io/realm/DynamicRealm.java, realm/realm-library/src/main/java/io/realm/internal/LinkView.java, realm/realm-library/src/main/java/io/realm/internal/RealmCore.java, realm/realm-library/src/main/java/io/realm/internal/UncheckedRow.java, realm/realm-library/src/main/java/io/realm/internal/android/ISO8601Utils.java
=> optimize imports to reduce warnings

CHANGELOG.md
Adding credits for #2648 
@realm/java
=> Added credits to 0.90

CHANGELOG.md, realm/realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm/realm-annotations-processor/src/main/java/io/realm/processor/Utils.java, realm/realm-annotations-processor/src/test/java/io/realm/processor/RealmProcessorTest.java, realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/some/test/SimpleRealmModel.java, realm/realm-library/src/androidTest/java/io/realm/RealmModelTests.java, realm/realm-library/src/androidTest/java/io/realm/entities/pojo/RealmModelWithRealmModelField.java, realm/realm-library/src/androidTest/java/io/realm/entities/pojo/RealmObjectWithRealmModelField.java
* Modify and rename isRealmObject to isRealmModel.
* Modify annotation processor to allow RealmModel as a field.
Fix #2654
=> Fix using RealmModel as a field

examples/gridViewExample/build.gradle
=> Fix the abi naming for ARM architectures

CHANGELOG.md
Fixes https://github.com/realm/realm-java/issues/2655
@realm/java
=> Add bullet to changelog about new sorting behaviour on collections.

CHANGELOG.md
=> Add bullet to changelog about behavior change of refresh() method on Looper thread

realm/realm-library/src/androidTest/java/io/realm/SortTest.java
=> Adding a test on autoresorting on Looper threads

realm/realm-library/src/main/java/io/realm/OrderedRealmCollection.java, realm/realm-library/src/main/java/io/realm/RealmResults.java
=> Java doc for RealmResults.sort

realm/realm-library/src/androidTest/java/io/realm/SortTest.java
In response to http://stackoverflow.com/questions/37127464/realm-realmresultse-no-longer-sorts-my-data-in-place
@beeender @cmelchior
=> Testing sorting of Date

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java
Title : hashCode behavior Javadoc
The behavior of hashCode is documented as it is pointed in issue #2323. Until realm-java has an immutable identifier, the behavior of hashCode should be documented.
@realm/java please review.
=> hashCode behavior javadoc

CHANGELOG.md, realm/realm-jni/build.gradle
=> Update to core 0.100.2

README.md, build.gradle
=> Fix README and top level gradle file to support benchmarks.

examples/encryptionExample/src/main/java/io/realm/examples/encryptionexample/EncryptionExampleActivity.java, examples/gridViewExample/src/main/java/io/realm/examples/realmgridview/GridViewExampleActivity.java, examples/introExample/src/main/java/io/realm/examples/intro/IntroExampleActivity.java, examples/jsonExample/src/main/java/io/realm/examples/json/JsonExampleActivity.java, examples/kotlinExample/build.gradle, examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/KotlinExampleActivity.kt, examples/moduleExample/app/src/main/java/io/realm/examples/appmodules/ModulesExampleActivity.java, examples/moduleExample/library/src/main/java/io/realm/examples/librarymodules/Zoo.java, examples/threadExample/src/main/java/io/realm/examples/threads/AsyncTaskFragment.java, examples/threadExample/src/main/java/io/realm/examples/threads/PassingObjectsFragment.java, examples/threadExample/src/main/java/io/realm/examples/threads/ThreadFragment.java, examples/unitTestExample/src/main/java/io/realm/examples/unittesting/ExampleActivity.java, examples/unitTestExample/src/main/java/io/realm/examples/unittesting/repository/DogRepositoryImpl.java, examples/unitTestExample/src/test/java/io/realm/examples/unittesting/ExampleActivityTest.java, examples/unitTestExample/src/test/java/io/realm/examples/unittesting/ExampleRealmTest.java, realm/realm-library/src/main/java/io/realm/Realm.java, realm/realm-library/src/main/java/io/realm/RealmResults.java
=> Examples should use transaction blocks

realm-annotations/src/main/java/io/realm/annotations/RealmModule.java
Closes #2566 
The general documentation has been updated.
@realm/java
=> One RealmModule per file

CHANGELOG.md, realm/realm-jni/build.gradle, realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java
=> Realm Core updated to 0.100.4.

CHANGELOG.md, realm/realm-library/src/main/java/io/realm/BaseRealm.java
=> Changed to throw IllegalStateException when setAutoRefresh() is called on non-Looper thread

realm/realm-library/src/main/java/io/realm/RealmResults.java
=> Fixed grammar in exception message

CHANGELOG.md
=> Added credits for assetFile()

CHANGELOG.md, realm/realm-jni/build.gradle
=> Updating core

examples/introExample/src/main/java/io/realm/examples/intro/IntroExampleActivity.java
=> Fix bug in IntroExample

examples/kotlinExample/build.gradle
KotlinExample needs reflection so re-added.
=> Kotlin reflection for example revived

realm/realm-library/src/main/java/io/realm/BaseRealm.java, realm/realm-library/src/main/java/io/realm/DynamicRealm.java, realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java, realm/realm-library/src/main/java/io/realm/HandlerController.java, realm/realm-library/src/main/java/io/realm/Realm.java, realm/realm-library/src/main/java/io/realm/RealmChangeListener.java, realm/realm-library/src/main/java/io/realm/RealmCollection.java, realm/realm-library/src/main/java/io/realm/RealmConfiguration.java, realm/realm-library/src/main/java/io/realm/RealmFieldType.java, realm/realm-library/src/main/java/io/realm/RealmList.java, realm/realm-library/src/main/java/io/realm/RealmMigration.java, realm/realm-library/src/main/java/io/realm/RealmModel.java, realm/realm-library/src/main/java/io/realm/RealmObject.java, realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java, realm/realm-library/src/main/java/io/realm/RealmQuery.java, realm/realm-library/src/main/java/io/realm/RealmResults.java, realm/realm-library/src/main/java/io/realm/RealmSchema.java, realm/realm-library/src/main/java/io/realm/Sort.java
=> Fixing many minor things.

realm/realm-library/src/main/java/io/realm/RealmObject.java
=> Note about empty constructor with no arguments

CHANGELOG.md, realm/realm-jni/build.gradle
=> Upgrading core

realm/realm-library/src/main/java/io/realm/RealmList.java
=> Inherit documentation

realm/realm-jni/build.gradle, realm/realm-jni/src/Makefile
**DO NOT SQUASH WHEN MERGING!! #2915 SHOULD BE MERGED FIRST!!!**
All credits go to @kneth 
1. Fixed compile errors when build with NDK, and changes are intended to be in one separated commit which will be pushed to os repo as well.
2. Continue kg's work to build the object store source.
=> Build Object-Store

examples/moduleExample/app/src/main/java/io/realm/examples/appmodules/ModulesExampleActivity.java, realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java
It's a very simple patch. Please review this @realm/java .
=> Fix typo and rename a test.

realm/realm-jni/object-store/src/collection_notifications.cpp, realm/realm-jni/object-store/src/results.cpp, realm/realm-jni/project.mk
=> gcc is overly paranoid

CHANGELOG.md, realm/realm-jni/src/io_realm_internal_TableQuery.cpp, realm/realm-jni/src/io_realm_internal_TableQuery.h
The worst thing is async query won't throw those exceptions in the
background.
=> Wrong JNI function declaration caused test timeout

CHANGELOG.md, realm/realm-jni/src/io_realm_internal_TableQuery.cpp, realm/realm-jni/src/io_realm_internal_TableQuery.h, realm/realm-library/src/androidTest/java/io/realm/NotificationsTest.java, realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java, realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java, realm/realm-library/src/androidTest/java/io/realm/rule/RunTestInLooperThread.java, realm/realm-library/src/main/java/io/realm/BaseRealm.java, realm/realm-library/src/main/java/io/realm/HandlerController.java, realm/realm-library/src/main/java/io/realm/RealmConfiguration.java
=> !!CONFLICTS!!Merge remote-tracking branch 'origin/releases' into mc/merge/1.0_560bc6ed

Dockerfile, Jenkinsfile, realm/realm-annotations-processor/build.gradle
This is done to facilitate CI and build reproducibility
=> Add a Dockerfile to the repo

realm/realm-library/build.gradle
link against JavaSE, Android, and RxJava
see also: realm/realm-android-adapters#55
=> improve generated javadoc

realm/realm-library/src/main/java/io/realm/BaseRealm.java
=> removed unused methods and a constant string

realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
If `assertTrue(tempDir.renameTo(tempDirRenamed));` is executed before other thread's `Realm realm = Realm.getInstance(configuration);`, opening Realm fails with `no such directory`.
@realm/java
=> Fixed a race condition in RealmTests.deleteRealm().

Jenkinsfile, build.gradle
Handle Bintray credentials and the monitoring of metrics
=> Fix some issues regarding Jenkinsfile and master

examples/kotlinExample/build.gradle
[Kotlin 1.0.3](https://github.com/JetBrains/kotlin/blob/1.0.3/ChangeLog.md) is released, so I updated kotlin version in example 😄
=> update kotlin version in example to 1.0.3

realm/realm-annotations-processor/src/main/java/io/realm/processor/Constants.java, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmJsonTypeHelper.java, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
=> Add quotes around terms in exceptions message

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/main/java/io/realm/BaseRealm.java, realm/realm-library/src/main/java/io/realm/Realm.java
* Throws if they are not called in a transaction.
* Test cases for buld insertion thread checking.
* Lint warnings fix.
Close #3173
=> Check transaction state for buld insertion

realm/realm-library/src/main/java/io/realm/Realm.java
=> Clarify how insertOrUpdate behave for objects with primary keys.

examples/threadExample/src/main/java/io/realm/examples/threads/PassingObjectsFragment.java
=> Missing transaction in threading example

CHANGELOG.md, realm/realm-library/src/main/java/io/realm/RealmObject.java, realm/realm-library/src/main/java/io/realm/internal/Row.java
Fixes #3200 
The exception message when accessing 'null' object fields where a bit misleading. Exception + Javadoc have been updated.
@realm/java 
@beeender
=> Fix isLoaded JavaDoc

examples/encryptionExample/build.gradle, examples/gridViewExample/build.gradle, examples/introExample/build.gradle, examples/jsonExample/build.gradle, examples/kotlinExample/build.gradle, examples/migrationExample/build.gradle, examples/moduleExample/app/build.gradle, examples/moduleExample/library/build.gradle, examples/newsreaderExample/build.gradle, examples/rxJavaExample/build.gradle, examples/threadExample/build.gradle, examples/unitTestExample/build.gradle, realm/build.gradle, realm/realm-library/build.gradle
Docker handles SDK setup and AS handles it for local build.
=> Remove dependency to sdk-manager

CHANGELOG.md, realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java
It should only accept RealmList<DynamicRealmObject>.
Fix #3280
=> DynamicRealmObject.setList declaration fix

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java, realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java, realm/realm-library/src/main/java/io/realm/RealmQuery.java
=> getFieldIndex returns null for non-existing field

CHANGELOG.md, realm/realm-jni/build.gradle, realm/realm-jni/src/io_realm_internal_Table.cpp, realm/realm-jni/src/io_realm_internal_TableQuery.cpp, realm/realm-jni/src/io_realm_internal_TableView.cpp
@realm/java
Note this PR will also mean that #672 is now supported, and we just need to enable it in the public API.
=> Updated Realm Core to 1.5.0

CHANGELOG.md, realm/realm-jni/src/io_realm_internal_TableQuery.cpp, realm/realm-jni/src/util.hpp, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
Follow up on missing items in #https://github.com/realm/realm-java/pull/3285
=> Smaller fixes to binary queries

CHANGELOG.md, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java, realm/realm-library/src/androidTest/java/io/realm/CollectionTests.java, realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java, realm/realm-library/src/androidTest/java/io/realm/ManagedRealmCollectionTests.java, realm/realm-library/src/androidTest/java/io/realm/OrderedRealmCollectionIteratorTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java, realm/realm-library/src/androidTest/java/io/realm/UnManagedOrderedRealmCollectionTests.java, realm/realm-library/src/androidTest/java/io/realm/UnManagedRealmCollectionTests.java, realm/realm-library/src/androidTest/java/io/realm/entities/CustomMethods.java, realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java, realm/realm-library/src/main/java/io/realm/Realm.java, realm/realm-library/src/main/java/io/realm/RealmCollection.java, realm/realm-library/src/main/java/io/realm/RealmList.java, realm/realm-library/src/main/java/io/realm/RealmObject.java, realm/realm-library/src/main/java/io/realm/RealmResults.java
Closes #3101 
This aligns our API with similar methods from Cocoa/.NET
=> isValid() now returns true for unmanaged object. Added isManaged()

CHANGELOG.md, realm-transformer/src/main/groovy/io/realm/transformer/BytecodeModifier.groovy, realm-transformer/src/test/groovy/io/realm/transformer/BytecodeModifierTest.groovy
=> transform accesses to other model fields in model's constructors.

realm/realm-library/src/main/java/io/realm/internal/RealmProxyMediator.java
=> Fix javadoc comments in io.realm.internal.RealmProxyMediator

CHANGELOG.md, Jenkinsfile, realm/realm-library/build.gradle, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java, realm/realm-library/src/androidTest/java/io/realm/SortTest.java, realm/realm-library/src/main/cpp/CMakeLists.txt, realm/realm-library/src/main/cpp/io_realm_internal_LinkView.cpp, realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp, realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp, realm/realm-library/src/main/cpp/io_realm_internal_TableView.cpp, realm/realm-library/src/main/cpp/tablebase_tpl.hpp, realm/realm-library/src/main/cpp/util.hpp, realm/realm-library/src/main/java/io/realm/RealmQuery.java, realm/realm-library/src/main/java/io/realm/RealmResults.java, realm/realm-library/src/main/java/io/realm/internal/LinkView.java, realm/realm-library/src/main/java/io/realm/internal/TableQuery.java
And with some code cleanup.
Throw an runtime exception when input java bytes array cannot be read.
=> Update core to 2.0.0-rc4

realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp, realm/realm-library/src/main/java/io/realm/RealmSchema.java, realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java, realm/realm-library/src/main/java/io/realm/internal/Table.java
=> use the logic in Object Store to update schema version

realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
=> fix unstable test

examples/build.gradle, examples/gradle/wrapper/gradle-wrapper.properties, examples/threadExample/src/main/java/io/realm/examples/threads/AsyncQueryFragment.java, examples/threadExample/src/main/res/values/strings.xml, gradle-plugin/gradle/wrapper/gradle-wrapper.properties, gradle-plugin/src/test/groovy/io/realm/gradle/PluginTest.groovy, realm-annotations/gradle/wrapper/gradle-wrapper.properties, realm-transformer/gradle/wrapper/gradle-wrapper.properties, realm/build.gradle
=> Bump to build tools 2.2.0

CHANGELOG.md, realm/realm-library/build.gradle
=> Upgrade to Core 2.0.0

realm/realm-library/src/androidTest/java/io/realm/internal/PrimaryKeyTests.java, realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp, realm/realm-library/src/main/java/io/realm/RealmCache.java, realm/realm-library/src/main/java/io/realm/internal/Table.java
See the change in OS https://github.com/realm/realm-object-store/pull/168
=> Use set_string_unique to set primary key

realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/SyncObjectServerFacade.java
I moved `SyncObjectServerFacade.java` to `objectserver` directory and added a license comment.
@realm/java
=> move SyncObjectServerFacade.java to objectserver directory

Dockerfile, Jenkinsfile
This should shave off a few minutes from CI builds
=> Add support for ccache

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/main/java/io/realm/BaseRealm.java
Closes #1033
Finally!!!!!
@finnschiermer @realm/java
=> Compacting encrypted Realms is working.

CHANGELOG.md, realm/realm-library/src/main/AndroidManifest.xml, realm/realm-library/src/objectServer/AndroidManifest.xml
=> move registering NetworkStateReceiver to objectServer flavor

realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java, realm/realm-library/src/main/cpp/io_realm_internal_CheckedRow.cpp, realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp, realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java, realm/realm-library/src/main/java/io/realm/internal/CheckedRow.java, realm/realm-library/src/main/java/io/realm/internal/UncheckedRow.java
fixes #3549
This PR requires #3551 to be merged.
=> fix native crash in DynamicRealmObject#setList()

build.gradle, realm/build.gradle, realm/realm-library/build.gradle
Closes #3513 
OJO Uploads now work again.
I tried to abstract the CURL commands, but it just ended up more messy and unreadable. So I went back to this more copy-paste way of doing it.
@realm/java 
@emanuelez
=> Enable OJO upload for AAR flavours.

examples/kotlinExample/build.gradle, examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/KotlinExampleActivity.kt
Part fix for #3580 
@realm/java
=> Update kotlin example

CHANGELOG.md, realm-transformer/src/main/groovy/io/realm/transformer/BytecodeModifier.groovy, realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy
The AS 2.2.1 seems enable info level log by default which makes the
build slow in the AS.
Close #3608
=> Use debug log level for transformer

CHANGELOG.md, realm/realm-library/src/main/cpp/objectserver_shared.hpp, realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/SyncSession.java
=> Call notifySessionError from native code

realm/realm-library/src/main/java/io/realm/Realm.java
I forgot to address this Muling's comment https://github.com/realm/realm-java/pull/3591/files#r83391423
@realm/java
=> fix temp directory name

CHANGELOG.md
=> Added credits to changelog

CHANGELOG.md, Dockerfile, README.md, dependencies.list, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
Upgraded to Sync BETA-3.2
Upgraded ROS (integration tests) to 2.3
Added comments to dependencies.list to increase readability.
Restructured README around integration tests to be easier to follow.
=> Upgrade to Sync BETA-3.2

CHANGELOG.md, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncConfigurationTests.java, realm/realm-library/src/main/java/io/realm/RealmConfiguration.java, realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java
=> Set default RxFactory in SyncConfiguration when RxJava is available.

realm/realm-library/src/main/cpp/util.cpp, realm/realm-library/src/main/java/io/realm/exceptions/RealmFileException.java, realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java
=> fix typo (IMCOMPATIBLE to INCOMPATIBLE)

CHANGELOG.md
=> added changelog for #3785

CHANGELOG.md, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncConfigurationTests.java, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java, realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java, realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
=> Fix SyncConfiguration.toString()

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/main/java/io/realm/RealmCache.java
=> Fix getLocalInstanceCount crashing when Realms are closed again.

realm/realm-library/src/main/cpp/objectserver_shared.hpp
Upgrade to latest commit on the `realm-object-store/realm-java` branch
@realm/java
=> Upgrade to latest OS

Jenkinsfile
=> Revert "Modernize the git checkout code in the Jenkinsfile"

Jenkinsfile
=> Revert "Revert "Modernize the git checkout code in the Jenkinsfile""

CHANGELOG.md, realm/realm-library/src/main/java/io/realm/DynamicRealm.java, realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java, realm/realm-library/src/main/java/io/realm/Realm.java, realm/realm-library/src/main/java/io/realm/RealmList.java, realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java, realm/realm-library/src/main/java/io/realm/RealmQuery.java, realm/realm-library/src/main/java/io/realm/RealmResults.java, realm/realm-library/src/main/java/io/realm/RealmSchema.java, realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java, realm/realm-library/src/objectServer/java/io/realm/SyncManager.java, realm/realm-library/src/objectServer/java/io/realm/SyncSession.java
=> Remove final modifier from all major classes.

realm/realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java
Improve error message output when an Entity Class hasn't a default constructor
=> Improve Error Message Output 

CHANGELOG.md, dependencies.list, realm/realm-library/src/androidTest/java/io/realm/RealmInMemoryTest.java, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/main/cpp/CMakeLists.txt, realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp, realm/realm-library/src/main/cpp/objectserver_shared.hpp, tools/sync_test_server/Dockerfile
Core to v2.2.0.
Sync to v1.0.0-BETA-5.0.
Also adapt changes from latest object store.
=> Update core, sync and object store

README.md
=> snapshot local url should be inside allprojects

CHANGELOG.md, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
=> Java lint warnings with proxy class

CHANGELOG.md, dependencies.list, realm/realm-library/src/main/cpp/io_realm_SyncManager.cpp, realm/realm-library/src/main/cpp/io_realm_internal_objectserver_ObjectServerSession.cpp, realm/realm-library/src/main/cpp/objectserver_shared.hpp, realm/realm-library/src/objectServer/java/io/realm/SyncManager.java
Also update object-store to 99570ba6e0 .
=> Update core to 2.3.0

realm/realm-library/src/main/cpp/CMakeLists.txt, realm/realm-library/src/main/cpp/io_realm_RealmSchema.cpp, realm/realm-library/src/main/cpp/io_realm_SyncManager.cpp, realm/realm-library/src/main/cpp/io_realm_internal_LinkView.cpp, realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp, realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp, realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp, realm/realm-library/src/main/cpp/io_realm_internal_objectserver_ObjectServerSession.cpp, realm/realm-library/src/main/cpp/jni_util/log.cpp, realm/realm-library/src/main/cpp/objectserver_shared.hpp, realm/realm-library/src/main/cpp/util.cpp, realm/realm-library/src/main/java/io/realm/exceptions/RealmFileException.java, realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java
Adapt the same warning options from object store
Depends on https://github.com/realm/realm-object-store/pull/308
=> Enable -Werror and fix warnings

CHANGELOG.md, realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp
=> Fix memory leak (#3993)

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java, realm/realm-library/src/androidTest/java/io/realm/internal/JNIQueryTest.java, realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp, realm/realm-library/src/main/java/io/realm/RealmQuery.java, realm/realm-library/src/main/java/io/realm/internal/TableQuery.java
=> Wire the "like" predicate into RealmQuery

README.md, realm/config/findbugs/findbugs-filter.xml, realm/config/studio/Realm-style.xml, realm/config/studio/Realm_lint.xml, realm/realm-library/build.gradle, realm/realm-library/src/main/java/io/realm/HandlerController.java, realm/realm-library/src/objectServer/java/io/realm/SyncManager.java, realm/realm-library/src/objectServer/java/io/realm/SyncUser.java, realm/realm-library/src/objectServer/java/io/realm/permissions/PermissionChange.java
Note UT findbugs failures
Clean up code in SyncUser to eliminate FB exception
=> Convert to annotations for findbugs exceptions

CHANGELOG.md
Update object store to bd3825e949 to fix #4002
=> Fix too many open files crash

CHANGELOG.md, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java, realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
=> SyncUser.all() returns Map

CHANGELOG.md, realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java
=> Removing unused public constants

CHANGELOG.md
=> moved changelog entry of like predicate to 2.3

README.md
=> Update the documentation for downloading the NDK.

realm/realm-library/src/main/cpp/util.cpp
=> Fix typo on error message

examples/kotlinExample/build.gradle
fixes #4108
This PR requires #4110 to be merged first.
@realm/java
=> update Kotlin used in example to 1.0.6

CHANGELOG.md, realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy
Removed gradle's class path from the Class pool of transformer.
fixes #3568
=> Fixed a bug that the classes were replaced with a class in Gradle's classpath

CHANGELOG.md, realm/realm-library/src/main/java/io/realm/HandlerController.java
=> RealmObject could be GCed when completedAsyncRealmObject

realm/config/checkstyle/checkstyle.xml
It should match:
if()
but not:
ifSomething().
=> Fix checkstyle space before opening parenthesis

realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy, realm-transformer/src/main/java/io/realm/transformer/RealmAnalytics.java
Fixes https://github.com/realm/realm-java-private/issues/206
=> Add minVersion and targetVersion to Realm Transformer metrics

CHANGELOG.md, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncConfigurationTests.java, realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java, realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
=> Allow more leniency when defining the server url

realm/realm-library/src/main/cpp/CMakeLists.txt
This is a port of #4155 to the `releases` branch
=> Use transitive dependencies in CMake

CHANGELOG.md, dependencies.list
This includes Realm Core v2.3.1:
* https://github.com/realm/realm-core/pull/2428 (LTO)
* https://github.com/realm/realm-core/pull/2426 (`advance_read` fix)
@realm/java
=> Upgrading to Realm Sync 1.0.4

realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java
There is no guarantee that posted event will be arrived later than
Object Store notification.
=> Fix flaky test

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java, realm/realm-library/src/main/cpp/jni_util/log.hpp
=> Fix log level in jni

CHANGELOG.md
fixes #4227 
I've updated internal release documentation as well.
@realm/java
=> add release date template

CHANGELOG.md, dependencies.list
=> Upgrading to sync v1.2.1 and core v2.3.2

realm-transformer/src/main/groovy/io/realm/transformer/BytecodeModifier.groovy, realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/androidTest/java/io/realm/entities/DefaultValueFromOtherConstructor.java
#4249 was accidentally merged towards master. This is the same PR against `releases`.
=> Crash when on constructor calls another with default values

realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java
=> stabilize flaky test

examples/secureTokenAndroidKeyStore/src/main/AndroidManifest.xml
I think the package name is wrong. @nhachicha
=> Fixing package name

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java, realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java, realm/realm-library/src/main/java/io/realm/RealmList.java
=> Add thread check to methods in DynamicRealmObject

CHANGELOG.md
This PR includes #1636
@realm/java
=> update release dates in CHANGELOG.md

CHANGELOG.md, dependencies.list, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
Fixes a potential corruption (never reported by anyone).
@realm/java
=> Upgrading to Realm Sync 1.3.1

realm/realm-library/src/main/java/io/realm/Realm.java
just a small improvement.
@realm/java
=> remove unnecessary array allocations

realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java, realm/realm-library/src/androidTest/java/io/realm/TestHelper.java, realm/realm-library/src/androidTest/java/io/realm/internal/test/ExtraTests.java, realm/realm-library/src/main/java/io/realm/RealmCollection.java, realm/realm-library/src/main/java/io/realm/RealmList.java, realm/realm-library/src/main/java/io/realm/RealmResults.java, realm/realm-library/src/main/java/io/realm/internal/CheckedRow.java, realm/realm-library/src/main/java/io/realm/internal/Collection.java, realm/realm-library/src/main/java/io/realm/internal/ObjectServerFacade.java, realm/realm-library/src/main/java/io/realm/internal/Table.java, realm/realm-library/src/main/java/io/realm/internal/async/RealmAsyncTaskImpl.java
https://github.com/tbroyer/gradle-errorprone-plugin
This PR does not add the plugin, just fix the warnings.
I'll add the plugin in another PR with suppressing some warnings.
=> Fix warnings from error prone plugin

realm/realm-library/src/androidTest/java/io/realm/ManagedOrderedRealmCollectionTests.java, realm/realm-library/src/androidTest/java/io/realm/ManagedRealmCollectionTests.java, realm/realm-library/src/androidTest/java/io/realm/NotificationsTest.java, realm/realm-library/src/androidTest/java/io/realm/OrderedRealmCollectionIteratorTests.java, realm/realm-library/src/androidTest/java/io/realm/OrderedRealmCollectionTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmCacheTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmJsonTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java, realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java, realm/realm-library/src/benchmarks/java/io/realm/benchmarks/config/CSVResultProcessor.java, realm/realm-library/src/objectServer/java/io/realm/SyncUser.java, realm/realm-library/src/objectServer/java/io/realm/internal/network/LogoutResponse.java, realm/realm-library/src/objectServer/java/io/realm/internal/network/NetworkStateReceiver.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProcessCommitTests.java
=> fix warnings reported by ErrorProne (second PR)

examples/kotlinExample/build.gradle
=> Upgrade Kotlin example

realm/realm-library/src/main/java/io/realm/RealmList.java
=> fix build error in Javadoc task

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
=> add @Override annotation to internal backlinks getters.

realm/config/checkstyle/checkstyle.xml, realm/realm-library/build.gradle
Not currently failing on errors
=> Enable checkstyle

realm/realm-library/src/main/cpp/util.cpp, realm/realm-library/src/main/cpp/util.hpp
These two line are supposed to be removed in #4365.
=> Remove useless code

CHANGELOG.md, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java, realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
Fixes #4370 
/cc @ericmaxwell2003
=> Automatically append `/auth` to authentication URL if needed

CHANGELOG.md, dependencies.list
=> Updating to Realm Sync 1.5.0 and Realm Core 2.5.1

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java, realm/realm-library/src/androidTest/java/io/realm/internal/SortDescriptorTests.java, realm/realm-library/src/main/java/io/realm/RealmQuery.java, realm/realm-library/src/main/java/io/realm/internal/SortDescriptor.java
=> Enable distinct on unindexed fields

realm-annotations/src/main/java/io/realm/annotations/LinkingObjects.java
Pr. internal discussion
@realm/java
=> Mark @LinkingObjects as beta

realm/realm-library/src/androidTest/java/io/realm/internal/CollectionTests.java
=> correct expected and actual in assertion

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java
=> Resume sending update messages

examples/build.gradle, realm/build.gradle
=> update android gradle plugin to 2.3.1

CHANGELOG.md, dependencies.list, realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp, realm/realm-library/src/main/cpp/util.hpp
This is https://github.com/realm/realm-java/pull/4483  against `releases`
=> update to Core 2.6.0 & Sync 1.5.2

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/LinkingObjectsManagedTests.java, realm/realm-library/src/main/java/io/realm/internal/Collection.java
=> fix a bug that Collection from backlink holds wrong table pointer.

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmJsonTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java, realm/realm-library/src/main/cpp/util.hpp
=> added field name information to exception messages

CHANGELOG.md, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java, realm/realm-library/src/androidTest/java/io/realm/LinkingObjectsManagedTests.java, realm/realm-library/src/androidTest/java/io/realm/entities/BacklinksSource.java, realm/realm-library/src/androidTest/java/io/realm/entities/BacklinksTarget.java, realm/realm-library/src/main/java/io/realm/internal/InvalidRow.java, realm/realm-library/src/main/java/io/realm/internal/PendingRow.java, realm/realm-library/src/main/java/io/realm/internal/Row.java, realm/realm-library/src/main/java/io/realm/internal/UncheckedRow.java
=> Fix exception thrown from backlinks field

realm/realm-library/src/main/cpp/io_realm_internal_CheckedRow.cpp
=> Fix return values in JNI unchecked row

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java, realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp
Update OS to 7a1924b4cf
Fix #4502
=> Update Object Store and test cases

CHANGELOG.md, dependencies.list
=> Update realm sync to 1.6.0

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/ObjectChangeSetTests.java, realm/realm-library/src/androidTest/java/io/realm/entities/Dog.java
=> Update Object Store

CHANGELOG.md, realm/realm-library/src/main/cpp/io_realm_SyncManager.cpp, realm/realm-library/src/objectServer/java/io/realm/SyncManager.java
=> Sync reconnect

tools/release.sh
There are still more work needed to do release on Jenkins. Before that a
script to help release locally is useful.
This script currently only handle the patch release.
=> Script for doing release locally

realm/realm-library/src/androidTest/java/io/realm/SortTest.java
It seems that our documentation isn't clear on how we sort: https://github.com/realm/realm-core/issues/2573
I have added a unit test to clarify it, and I will update our documentation accordingly.
=> Validate how letters are sorted.

CHANGELOG.md, realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp
As @beeender points out, we have forgot a check.
Closes #4540
=> Fixes #4540

realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java
=> Fix schemaVersion docs for synced Realms

Dockerfile, README.md, examples/build.gradle, realm/realm-library/build.gradle
=> Update build-tools to 25.0.3

examples/newsreaderExample/build.gradle, examples/newsreaderExample/src/main/java/io/realm/examples/newsreader/ui/details/DetailsActivity.java, examples/newsreaderExample/src/main/java/io/realm/examples/newsreader/ui/main/MainActivity.java, examples/objectServerExample/build.gradle
ButterKnife 8 is required by Android Gradle Plugin 2.4.0.
@realm/java
=> Update ButterKnife to 8.5.1

realm-annotations/src/main/java/io/realm/annotations/RealmModule.java
Some grammar changes for RealmModule docs
=> Grammar for RealmModule docs

examples/kotlinExample/build.gradle
=> update Kotlin in example to 1.1.2-4

CHANGELOG.md, dependencies.list, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java, realm/realm-library/src/objectServer/java/io/realm/SyncUser.java, realm/realm-library/src/objectServer/java/io/realm/internal/network/AuthenticationServer.java, realm/realm-library/src/objectServer/java/io/realm/internal/network/ChangePasswordRequest.java, realm/realm-library/src/objectServer/java/io/realm/internal/network/OkHttpAuthenticationServer.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
=> Change password using Admin user 

CHANGELOG.md
=> Add next release to changelog

CHANGELOG.md, realm/realm-library/src/objectServer/java/io/realm/SyncSession.java
=> fix crash when authentication error happens

CHANGELOG.md, realm/realm-library/src/main/java/io/realm/RealmCollection.java, realm/realm-library/src/main/java/io/realm/RealmObject.java, realm/realm-library/src/main/java/io/realm/internal/ManagableObject.java, realm/realm-library/src/main/java/io/realm/internal/ManagedObject.java
Pull out the common interface needed for RealmInteger
=> Factor out ManagedObject Interface

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java, realm/realm-library/src/main/java/io/realm/Realm.java
=> Add Realm.getDefaultConfiguration()

LICENSE
see https://github.com/realm/realm-cocoa/commit/8714b3dc6325d39366335ef3a96c68b3edd82dc6 for original commit with new wording for export compliance.
=> Update license to match changes in realm-cocoa

realm/realm-library/src/main/java/io/realm/log/RealmLog.java
=> Only format log message if the level is enabled

tools/release.sh
Reference https://stackoverflow.com/a/4247333/1389357
=> Fix release script on Mac

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java, realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp
"" is a char* type takes 1 byte of memory.
=> BLOB's default value when convert to not-nullable

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmJsonTypeHelper.java
Shortly adding one more complex `FieldConverter`
=> Clean up JsonHelper as prep for RealmInteger

examples/unitTestExample/build.gradle, examples/unitTestExample/src/test/java/io/realm/examples/unittesting/ExampleActivityTest.java, examples/unitTestExample/src/test/java/io/realm/examples/unittesting/ExampleRealmTest.java
-Upgrade to Robolectric 3.3.2 
closes #4698
=> fix roboelectric unit test

examples/build.gradle, realm/build.gradle
=> Update android gradle plugin to 2.3.3

realm/realm-library/src/androidTest/java/io/realm/internal/JNIQueryTest.java
`assert(false)` checks nothing...
=> Use fail() instead of assert(false) in tests

CHANGELOG.md, realm/realm-library/src/main/cpp/io_realm_SyncSession.cpp, realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java, realm/realm-library/src/objectServer/java/io/realm/SyncSession.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/SyncSessionTests.java
=> Returning session's state

realm/realm-library/src/androidTest/java/io/realm/internal/JNIColumnInfoTest.java, realm/realm-library/src/androidTest/java/io/realm/internal/JNIQueryTest.java, realm/realm-library/src/androidTest/java/io/realm/internal/JNIRowTest.java, realm/realm-library/src/androidTest/java/io/realm/internal/JNISortedLongTest.java, realm/realm-library/src/androidTest/java/io/realm/internal/PivotTest.java, realm/realm-library/src/androidTest/java/io/realm/internal/TableIndexAndDistinctTest.java
To prepare #4812, migrate some tests to JUnit4.
=> Migrate some test cases to JUnit4

realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java
=> Allow multiple tasks to run after test is complete.

realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java
RealmObjectSchema.addIndex() is not idempotent. The test was created
in #1544 for issue #1385 which was using Table.addSearchIndex().
RealmObjectSchema.addIndex() will just throw when called twice, it is
guaranteed by test addIndexFieldModifier_alreadyIndexedThrows.
The test can accidentally pass is just because of
default-before-migration.realm was created before 0.82 when the primary
key was not auto-indexed yet.
=> Remove outdated addSearchIndexTwice

README.md
=> Update README.md (OS X -> macOS)

README.md
=> Update README.md (OSX -> macOS)

realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncManagerTests.java, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java, realm/realm-library/src/objectServer/java/io/realm/PermissionManager.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/BaseIntegrationTest.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/IsolatedIntegrationTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/PermissionManagerTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/SSLConfigurationTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/StandardIntegrationTest.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncedRealmTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/EncryptedSynchronizedRealmTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ManagementRealmTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProcessCommitTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProgressListenerTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/SyncSessionTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/UserFactory.java, tools/sync_test_server/configuration.yml
Part of #4558 
Tries to improve the stability of the integration tests.
=> PermissionWrappers - Better Test Setup

realm/realm-library/src/androidTest/java/io/realm/RealmChangeListenerTests.java, realm/realm-library/src/androidTest/java/io/realm/TestHelper.java
To clarify expected behaviour (see also #4875).
=> Listeners and LinkingObjects

realm/realm-library/src/main/java/io/realm/RealmConfiguration.java
=> Fix wrong javadoc in RealmConfiguration

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java, realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp, realm/realm-library/src/main/java/io/realm/CompactOnLaunchCallback.java, realm/realm-library/src/main/java/io/realm/DefaultCompactOnLaunchCallback.java, realm/realm-library/src/main/java/io/realm/RealmConfiguration.java, realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java, realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java
=> Add CompactOnLaunch.

CHANGELOG.md, dependencies.list, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java, realm/realm-library/src/androidTest/java/io/realm/entities/IndexedFields.java, realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp, realm/realm-library/src/main/cpp/java_sort_descriptor.cpp, realm/realm-library/src/main/cpp/java_sort_descriptor.hpp, realm/realm-library/src/main/java/io/realm/internal/SortDescriptor.java
This introduces a breaking change to how SSL is configured. https://github.com/realm/realm-object-store/pull/493 addressed this.
Close #4791 #4788
=> Upgrade Realm Core to 2.8.6

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java, realm/realm-library/src/main/java/io/realm/internal/ProxyUtils.java
New class ProxyUtils to reduce size of proxies.
=> Create ProxyUtils class to simplify proxies

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java, realm/realm-library/src/androidTest/java/io/realm/MutableRealmIntegerTests.java, realm/realm-library/src/androidTest/java/io/realm/entities/MutableRealmIntegerTypes.java, realm/realm-library/src/main/java/io/realm/MutableRealmInteger.java
Add tests for @Required and @Index
Document ManagedRealmInteger
=> Counters: Required, Index and Documentation

CHANGELOG.md, examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/KotlinExampleActivity.kt, realm/realm-library/build.gradle, realm/realm-library/src/androidTest/kotlin/io/realm/KotlinSchemaTests.kt, realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java, realm/realm-library/src/main/java/io/realm/OrderedRealmCollectionImpl.java, realm/realm-library/src/main/java/io/realm/Realm.java, realm/realm-library/src/main/java/io/realm/RealmCache.java, realm/realm-library/src/main/java/io/realm/RealmCollection.java, realm/realm-library/src/main/java/io/realm/RealmQuery.java, realm/realm-library/src/main/java/io/realm/RealmSchema.java, realm/realm-library/src/main/java/io/realm/internal/ColumnIndices.java, realm/realm-library/src/main/java/io/realm/internal/ColumnInfo.java, realm/realm-library/src/main/java/io/realm/internal/Table.java, realm/realm-library/src/main/java/io/realm/internal/android/JsonUtils.java
This improves type inference in Kotlin.
=> add Nullable annotation to methods that can return 'null'

realm/realm-library/src/main/java/io/realm/ImmutableRealmSchema.java, realm/realm-library/src/main/java/io/realm/MutableRealmSchema.java, realm/realm-library/src/main/java/io/realm/RealmSchema.java
This PR fixes a name of internal method.
=> fix internal method name

realm/realm-library/src/main/java/io/realm/MutableRealmSchema.java
=> fix compilation error on master-4.0 branch

CHANGELOG.md
CHANGELOG update for MutableRealmIntegers
=> Add MutableRealmIntegers to the CHANGELOG.

CHANGELOG.md, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java, realm/realm-library/src/objectServer/java/io/realm/SyncManager.java, realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
=> Add SyncUser.allSessions()

realm/realm-library/src/objectServer/java/io/realm/PermissionManager.java, realm/realm-library/src/objectServer/java/io/realm/SyncUser.java, realm/realm-library/src/objectServer/java/io/realm/permissions/UserCondition.java
Part of #4558 
This PR adds the remaining public Javadoc.
=> Public Javadoc for PermissionManager

README.md
This updates the link for the community newsletter
=> Update link for community newsletter

realm/realm-library/src/main/java/io/realm/BaseRealm.java
Fix https://github.com/realm/realm-java/issues/2299#issuecomment-303508956
=> Update Javadoc to not reference Realm.getDefaultInstanceAsync.

CHANGELOG.md, realm/realm-library/src/objectServer/java/io/realm/SyncUser.java, realm/realm-library/src/objectServer/java/io/realm/SyncUserInfo.java, realm/realm-library/src/objectServer/java/io/realm/internal/network/LookupUserIdResponse.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
=> Align User Lookup implementation 

CHANGELOG.md, dependencies.list, realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp, realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java
=> Update realm-sync to 1.10.8

realm/realm-library/src/androidTest/java/io/realm/SortTest.java, realm/realm-library/src/androidTest/java/io/realm/internal/CollectionTests.java, realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp, realm/realm-library/src/main/java/io/realm/internal/Collection.java
WIP still have an issue with the linker probably because of the change of the namespace in `results.cpp` 
```
/Users/Nabil/Dev/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp:137: error: undefined reference to 'unsigned int realm::Results::index_of<realm::BasicRow<realm::Table> >(realm::BasicRow<realm::Table> const&)'
/Users/Nabil/Dev/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp:369: error: undefined reference to 'unsigned int realm::Results::index_of<realm::BasicRow<realm::Table> >(realm::BasicRow<realm::Table> const&)'
/Users/Nabil/Dev/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp:384: error: undefined reference to 'unsigned int realm::Results::index_of<unsigned int>(
```
=> Update to latest OS

tools/release.sh
- sed for Mac and Linux.
- Update submodule when release from master branch.
=> Fix release script

realm/realm-library/src/main/cpp/jni_util/java_class.cpp
Seen in #5195 that we don't report the class missing correctly
=> Report the class missing correctly

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/CollectionTests.java, realm/realm-library/src/androidTest/java/io/realm/ManagedOrderedRealmCollectionTests.java, realm/realm-library/src/androidTest/java/io/realm/ManagedRealmCollectionTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java, realm/realm-library/src/main/cpp/io_realm_internal_OsList.cpp, realm/realm-library/src/main/java/io/realm/RealmList.java, realm/realm-library/src/main/java/io/realm/internal/OsList.java
=> Fix a bug that RealmList.delete*() does not delete target objects

CHANGELOG.md, realm/realm-library/src/main/java/io/realm/internal/ColumnIndices.java
It should check the table name instead.
Close #5211
=> getColumnInfo was checking obfuscated class name

examples/encryptionExample/build.gradle, examples/gridViewExample/build.gradle, examples/introExample/build.gradle, examples/jsonExample/build.gradle, examples/kotlinExample/build.gradle, examples/migrationExample/build.gradle, examples/newsreaderExample/build.gradle, examples/objectServerExample/build.gradle, examples/rxJavaExample/build.gradle, examples/secureTokenAndroidKeyStore/build.gradle, examples/threadExample/build.gradle, examples/threadExample/src/main/java/io/realm/examples/threads/ThreadFragment.java, examples/threadExample/src/main/java/io/realm/examples/threads/widget/DotsView.java, examples/unitTestExample/build.gradle
- Close #5184 . without siging, monkeyRelease will fail with
INSTALL_PARSE_FAILED_NO_CERTIFICATES
- Enable proguard for all most all examples, both debug & release. This
will give us a chance to see proguard issues as early as possible.
- Fix a "realm was closed" crash for thread example.
=> Sign release apk for examples

examples/gridViewExample/build.gradle, examples/gridViewExample/proguard-rules.pro, examples/gridViewExample/src/main/java/io/realm/examples/realmgridview/City.java
=> Add Gridview example's proguard configuration.

realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
=> Enable test login_withAccessToken

examples/objectServerExample/src/main/java/io/realm/examples/objectserver/CounterActivity.java, examples/objectServerExample/src/main/java/io/realm/examples/objectserver/MyApplication.java
Fixed example not working correctly
=> Fix change listener getting GC'ed

realm/realm-library/src/objectServer/java/io/realm/ErrorCode.java
Fixes https://github.com/realm/realm-java/issues/5301
=> Add support for new error codes

CHANGELOG.md, examples/build.gradle, examples/objectServerExample/src/main/java/io/realm/examples/objectserver/LoginActivity.java, realm/realm-library/src/androidTestObjectServer/java/io/realm/AuthenticateRequestTests.java, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java, realm/realm-library/src/androidTestObjectServer/java/io/realm/util/SyncTestUtils.java, realm/realm-library/src/objectServer/java/io/realm/SyncSession.java, realm/realm-library/src/objectServer/java/io/realm/SyncUser.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/EncryptedSynchronizedRealmTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/SyncSessionTests.java
addresses point 5 and 6 form the issue https://github.com/realm/realm-java/issues/4785
=> 4.0 API breaking changes 

realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp, realm/realm-library/src/main/java/io/realm/Realm.java, realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java
=> partial sync fix ref

realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncSessionTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncedRealmTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/PartialSyncTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProcessCommitTests.java
Ignore unit tests until we can fix them. Enable others
=> Make CI more reliable

realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/PartialSyncTests.java
=> Re enable partial sync test

realm/realm-library/src/androidTestObjectServer/java/io/realm/SessionTests.java, realm/realm-library/src/main/cpp/io_realm_SyncSession.cpp, realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncSessionTests.java
=> Enabling client reset test

CHANGELOG.md, realm/realm-library/src/objectServer/java/io/realm/PermissionManager.java
=> Remove readonly for defaultPermissionRealmConfig

CHANGELOG.md, Jenkinsfile, dependencies.list, realm/realm-library/src/objectServer/java/io/realm/PermissionManager.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/PermissionManagerTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncSessionTests.java, tools/sync_test_server/Dockerfile, tools/sync_test_server/ros-testing-server.js
* Update to ROS-2.0.0-rc9
* Update to Sync 2.0.2
* Store ROS logs as an artifact for each test run
* Re-enable default permissions + tests.
=> Update all dependencies

realm/realm-library/src/main/java/io/realm/RealmQuery.java
=> Fix wrong Javadoc

realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProgressListenerTests.java
=> Fix progress listener flaky tests

realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java
- Re-structure codes. Move inner classes to the top, followed by the
fields defines.
- Format code.
- Remove unused var collections.
=> Clean up SharedRealm.java

realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProgressListenerTests.java
In createRemoteData we try to identify the uploading is finished by two
conditions:
- Check if the newly created data exists in the Realm on the callback thread.
- Check if uploadable == uploaded
This works if the callback is called on the sync client thread.
But actually there is a chance the callback gets called immediately after
registered because of some other data created before just got uploaded. In
this case, the data does exist in the Realm on the caller thread (we just
add on the same thread), and the uploaded could equal to the uploadable.
By only accept the callback on the sync client thread by if (threadId ==
Thread.currentThread().getId()) will make sure the data has been uploaded.
=> Enable downloadProgressListener_indefinitely

realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp
Update ObjectStore to support `realm::SyncConfig` refactor in https://github.com/realm/realm-object-store/pull/590
=> update ObjectStore to reflect SyncConfig refactor 

realm/realm-library/src/main/java/io/realm/internal/OsResults.java
=> Fix spelling mistake

CHANGELOG.md, dependencies.list
=> Update sync to 2.1.4

realm/realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java, realm/realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java
=> Ensure stable classes order in generated mediators

examples/encryptionExample/build.gradle, examples/encryptionExample/src/main/AndroidManifest.xml, examples/encryptionExample/src/main/java/io/realm/examples/encryption/EncryptionExampleActivity.java, examples/encryptionExample/src/main/java/io/realm/examples/encryption/MyApplication.java, examples/encryptionExample/src/main/java/io/realm/examples/encryption/Person.java, examples/encryptionExample/src/main/java/io/realm/examples/encryption/Util.java
Based on question here: https://stackoverflow.com/questions/47505171/realm-database-decryption-failed
=> Improve encryption example

CHANGELOG.md, realm/realm-library/src/androidTestObjectServer/java/io/realm/CredentialsTests.java, realm/realm-library/src/objectServer/java/io/realm/SyncCredentials.java
=> Add explicit support for JWT tokens

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/OrderedCollectionChangeSetTests.java
- Add a test case to show issue described in #5507.
- Update OS to a31fab1f56a3a to solve part of the issue (issue with RealmList).
- Need https://github.com/realm/realm-object-store/issues/605 to solve
the issue in RealmResults side.
=> Listener not called on RealmList

CHANGELOG.md, gradle-plugin/src/main/groovy/io/realm/gradle/RealmPluginExtension.groovy
Closes #5587 
Big ups. Could have sworn I tested this 😞
=> Fixes Kotlin extension functions always being added

realm/realm-library/src/main/java/io/realm/Realm.java
=> Fix getLocalInstanceCount doc

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java, realm/realm-library/src/main/java/io/realm/MutableRealmObjectSchema.java, realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
=> Better exception message for addField()

CHANGELOG.md, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmVersionChecker.java
=> Use https for RealmVersionChecker

CHANGELOG.md, dependencies.list, realm/realm-library/src/androidTestObjectServer/java/io/realm/CredentialsTests.java, realm/realm-library/src/objectServer/java/io/realm/SyncCredentials.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
adding nickname and anoymous auth
=> adding nickname and anoymous auth

CHANGELOG.md, realm/kotlin-extensions/src/androidTest/kotlin/io/realm/KotlinRealmQueryTests.kt, realm/kotlin-extensions/src/androidTest/kotlin/io/realm/entities/AllPropTypesClass.kt, realm/kotlin-extensions/src/main/kotlin/io/realm/kotlin/RealmQueryExtensions.kt
=> Add support for lists with non-null values in RealmQuery.oneOf

CHANGELOG.md, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncConfigurationTests.java, realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncedRealmIntegrationTests.java
Fixes #5806 
Replaces #5813
See #5813 for the discussion.
=> Add support for automatic configurations

examples/gridViewExample/build.gradle, examples/gridViewExample/src/main/java/io/realm/examples/realmgridview/City.java, examples/gridViewExample/src/main/java/io/realm/examples/realmgridview/CityAdapter.java, examples/gridViewExample/src/main/java/io/realm/examples/realmgridview/GridViewExampleActivity.java, examples/gridViewExample/src/main/java/io/realm/examples/realmgridview/MyApplication.java, examples/gridViewExample/src/main/res/layout/activity_realm_example.xml, examples/gridViewExample/src/main/res/layout/city_listitem.xml, examples/gridViewExample/src/main/res/values-w820dp/dimens.xml, examples/gridViewExample/src/main/res/values/dimens.xml, examples/gridViewExample/src/main/res/values/strings.xml
Base: Master. You guys probably know which branch this is supposed to go on.
Currently the GridView example was written by rlwaldrop in 2014.09, and it was never updated beyond adding `Realm.init(Context)`. So it had some pretty bad practices regarding current-day Realm usage.
So I updated it.
=> Update GridView example

examples/jsonExample/build.gradle, examples/jsonExample/src/main/java/io/realm/examples/json/CityAdapter.java, examples/jsonExample/src/main/java/io/realm/examples/json/JsonExampleActivity.java, examples/jsonExample/src/main/res/layout/activity_realm_example.xml
I can't help but feel like I've seen this example before....
so things that applies to `gridView example` apply to this one too. 😄
=> Update json example

CHANGELOG.md, realm/realm-library/src/objectServer/java/io/realm/SyncUser.java, realm/realm-library/src/objectServer/java/io/realm/internal/network/AuthenticationServer.java, realm/realm-library/src/objectServer/java/io/realm/internal/network/OkHttpAuthenticationServer.java, realm/realm-library/src/objectServer/java/io/realm/internal/network/UpdateAccountRequest.java, realm/realm-library/src/objectServer/java/io/realm/internal/network/UpdateAccountResponse.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/UserFactory.java
Closes #5821 
TODO
Tests are currently disabled and waiting for #5909 to complete before we can enable them. They have all been run manually and succesfully against a cloud instance.
=> Add support for resetting password and email confirmation.

Jenkinsfile
Data will be transferred from the old instance as well
=> Post size metrics to our own InfluxDB server

CHANGELOG.md, Jenkinsfile, dependencies.list, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncConfigurationTests.java, realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmTests.java, realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp, realm/realm-library/src/main/java/io/realm/Realm.java, realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java, tools/sync_test_server/Dockerfile, tools/sync_test_server/ros/src/index.ts, tools/sync_test_server/start_server.sh
=> Enable compact for synchronized Realms

CHANGELOG.md, dependencies.list
=> Fix rare native crash

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java, realm/realm-library/src/main/java/io/realm/RealmQuery.java, realm/realm-library/src/main/java/io/realm/internal/TableQuery.java
=> Fix bug when using distinct() and count()

CHANGELOG.md, gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy, realm-transformer/src/main/java/io/realm/gradle/RealmPluginExtension.java, realm-transformer/src/main/java/io/realm/transformer/Utils.java
=> Fix dependencies being changed too late.

CHANGELOG.md, realm/realm-library/src/main/java/io/realm/internal/sync/OsSubscription.java
Closes https://github.com/realm/realm-java-private/issues/234
=> Correctly keep members of OsSubscription

CHANGELOG.md, realm-annotations/src/main/java/io/realm/annotations/RealmClass.java, realm-annotations/src/main/java/io/realm/annotations/RealmField.java, realm/realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java, realm/realm-annotations-processor/src/test/resources/some/test/NamePolicyClassOnly.java, realm/realm-annotations-processor/src/test/resources/some/test/NamePolicyFieldNameOnly.java, realm/realm-library/src/androidTest/java/io/realm/CustomRealmNameTests.java, realm/realm-library/src/androidTest/java/io/realm/entities/realmname/ClassWithValueDefinedNames.java
=> Add support for using the default parameter when defining custom names

CHANGELOG.md, realm/realm-library/src/main/java/io/realm/RealmResults.java, realm/realm-library/src/main/java/io/realm/internal/OsResults.java
=> Remove Java8 bytecode

CHANGELOG.md, realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp
Closes https://github.com/realm/realm-java-private/issues/249
=> Fixed JNI reference not released correctly

realm-annotations/src/main/java/io/realm/annotations/Required.java
=> Better nullability docs

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java, tools/sync_test_server/Dockerfile
Closes https://github.com/realm/realm-java/issues/6478
=> Fix batch updates which removes objects from the query results

CHANGELOG.md, realm/kotlin-extensions/src/main/res/values/strings.xml, realm/realm-library/src/androidTestObjectServer/java/io/realm/TrustManagerCertificateValidationTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/SSLConfigurationTests.java
Fixes https://github.com/realm/realm-java/issues/6536
=> Remove app_name from Kotlin Extensions

CHANGELOG.md, dependencies.list, realm/realm-library/build.gradle, realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java, realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp, realm/realm-library/src/main/java/io/realm/RealmResults.java, realm/realm-library/src/main/java/io/realm/internal/OsResults.java
This is used mainly for debugging https://github.com/realm/realm-java-private/issues/262
=> exposing to_json from Core

CHANGELOG.md, realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp, realm/realm-library/src/objectServer/java/io/realm/SyncManager.java, realm/realm-library/src/objectServer/java/io/realm/internal/network/AuthenticateResponse.java
This PR improves the LogCat output when sessions are being created/destroyed.
Discovered this while debugging a users issue.
=> Better logging for sessions

CHANGELOG.md, realm/realm-library/src/main/cpp/CMakeLists.txt, realm/realm-library/src/main/cpp/io_realm_internal_objectstore_OsAsyncOpenTask.cpp, realm/realm-library/src/main/java/io/realm/RealmCache.java, realm/realm-library/src/main/java/io/realm/internal/ObjectServerFacade.java, realm/realm-library/src/main/java/io/realm/internal/OsRealmConfig.java, realm/realm-library/src/main/java/io/realm/sync/Subscription.java, realm/realm-library/src/objectServer/java/io/realm/SyncManager.java, realm/realm-library/src/objectServer/java/io/realm/internal/SyncObjectServerFacade.java, realm/realm-library/src/objectServer/java/io/realm/internal/objectstore/OsAsyncOpenTask.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncSessionTests.java, realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncedRealmIntegrationTests.java
=> Add support for AsyncOpen

gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy, gradle-plugin/src/test/groovy/io/realm/gradle/PluginTest.groovy
Follow up PR for #6598 to address @lacasseio comments
=> Fix #6597 - Don't enforce jCenter repository (follow up #6598)

CHANGELOG.md, Jenkinsfile, README.md, dependencies.list, gradle-plugin/build.gradle, gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy, gradle-plugin/src/test/groovy/io/realm/gradle/PluginTest.groovy
Closes: https://github.com/realm/realm-java/issues/5715
Upgrade to latest Sync release.
Doc entry for the Huawei bug fix is here: https://github.com/realm/realm.io/pull/4662
TODO
=> Upgrade to Sync 4.7.4

CHANGELOG.md, gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy, gradle-plugin/src/test/groovy/io/realm/gradle/PluginTest.groovy
Closes https://github.com/realm/realm-java/issues/6610
=> Fix support for flatDirs

realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java
=> Make setList Javadoc more accurate.

library-benchmarks/build.gradle, library-benchmarks/gradle/wrapper/gradle-wrapper.properties, library-benchmarks/src/androidTest/java/io/realm/benchmarks/CopyToRealmBenchmarks.kt, library-benchmarks/src/androidTest/java/io/realm/benchmarks/CopyToRealmOrUpdateBenchmarks.kt, library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmAllocBenchmarks.kt, library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmBenchmarks.kt, library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmInsertBenchmark.kt, library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmObjectReadBenchmarks.kt, library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmObjectWriteBenchmarks.kt, library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmQueryBenchmarks.kt, library-benchmarks/src/androidTest/java/io/realm/benchmarks/RealmResultsBenchmarks.kt
Updates the benchmark project to use the latest release. Required for #6590.
=> Upgrade benchmarks to use latest release

realm/realm-library/src/androidTest/java/ThreadStressTests.java
Closes https://github.com/realm/realm-java/issues/6668
=> Add multi-threaded stress test

Jenkinsfile
#6806  didn't actually work, because detecting the branch name logic was broken. This should fix it.
See https://ci.eclipse.org/webtools/env-vars.html/
=> Fix detecting current branch

dependencies.list
Updated Object Server pointer to v10 and bumped Sync to alpha 11-
=> Updated OS pointer to v10 and sync to alpha 11

realm/realm-library/src/androidTest/java/io/realm/internal/OsSharedRealmTests.java
Fixes our own tests and add a test for https://github.com/realm/realm-core/issues/3707
=> Fix broken tests on CI and expose bug in Core

CHANGELOG.md, gradle-plugin/src/test/groovy/io/realm/gradle/PluginTest.groovy, realm/realm-library/src/androidTest/java/io/realm/LinkingObjectsDynamicTests.java, realm/realm-library/src/androidTest/java/io/realm/internal/OsSharedRealmTests.java, realm/realm-library/src/androidTestObjectServer/java/io/realm/ObjectLevelPermissionsTest.java, realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp, realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp, realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp
Update to Core-6 and the new scheduler refactor introduced in https://github.com/realm/realm-object-store/pull/974
=> Using the new ObjectStore Scheduler

Jenkinsfile
Test restarted CI device
Fix docker caching not working correctly
=> Fix Docker push + test CI device

dependencies.list, realm/realm-library/src/androidTest/java/io/realm/internal/OsSharedRealmTests.java, realm/realm-library/src/main/cpp/io_realm_RealmApp.cpp, realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp, realm/realm-library/src/main/cpp/io_realm_internal_OsObjectSchemaInfo.cpp, realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp, realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp, realm/realm-library/src/main/cpp/io_realm_internal_objectstore_OsObjectBuilder.cpp, realm/realm-library/src/main/cpp/io_realm_mongodb_FunctionsImpl.cpp, realm/realm-library/src/main/cpp/java_accessor.hpp, realm/realm-library/src/main/cpp/java_network_transport.hpp
Update to latest version of Sync/Core/ObjectStore/Test image
=> Update to Sync-alpha.15 

CHANGELOG.md, dependencies.list, tools/sync_test_server/app_config/services/BackingDB/config.json
Update to latest Sync/OS release.
TODO
=> Update to Sync Beta 2

CHANGELOG.md
Fixes a problem with using an incorrect base url after restarting the app.
=> Prepare BETA.3 release

Jenkinsfile
All tests are independent, so running them in parallel should speed up CI.
=> Run CI tests in parallel

realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/CredentialsTests.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/UserTests.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/internal/network/LoggingInterceptorTest.kt, realm/realm-library/src/objectServer/java/io/realm/internal/objectstore/OsSyncUser.java, realm/realm-library/src/testObjectServer/kotlin/io/realm/ObfuscatorHelper.kt, realm/realm-library/src/testUtils/java/io/realm/TestHelper.java, tools/sync_test_server/app_config/functions/testAuthFunc/source.js
Enable and verify the tests for linking users.
=> Enable and fix link user tests

CHANGELOG.md, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmJsonTypeHelper.kt, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.kt, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.kt, realm/realm-annotations-processor/src/test/resources/io/realm/some_test_EmbeddedClassRealmProxy.java, realm/realm-annotations-processor/src/test/resources/io/realm/some_test_EmbeddedClassSimpleParentRealmProxy.java, realm/realm-library/src/androidTest/kotlin/io/realm/EmbeddedObjectsTest.kt, realm/realm-library/src/androidTest/kotlin/io/realm/entities/embedded/EmbeddedCircularParentWithoutPrimaryKey.kt, realm/realm-library/src/androidTest/kotlin/io/realm/entities/embedded/EmbeddedSimpleListParentWithoutPrimaryKey.kt
This adds support for stream based JSON import of embedded objects.
=> Stream based JSON import of embedded objects

realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/UserMetadataTests.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/UserTests.kt, realm/realm-library/src/objectServer/java/io/realm/mongodb/User.java
Adds tests for user's metadata and `getProviderType`.
=> Finish RealmUser, Javadoc and tests

realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/AppConfigurationTests.kt, realm/realm-library/src/objectServer/java/io/realm/mongodb/AppConfiguration.java
Implements the pending test cases and reviews the Javadoc
=> Finish RealmAppConfiguration Javadoc + Tests

CHANGELOG.md, dependencies.list, realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java, realm/realm-library/src/androidTest/kotlin/io/realm/EmbeddedObjectsTest.kt
Upgrades to latest 10.x beta Core/Sync. Ignore the wrong branch name 🙈
=> Upgrade to Sync 10.0.0-beta.6

realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/ApiKeyAuthTests.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/AppTests.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/CredentialsTests.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/EmailPasswordAuthTests.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/FunctionsTests.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/UserTests.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/admin/ServerAdmin.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/internal/network/LoggingInterceptorTest.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/AppExt.kt, realm/realm-library/src/syncIntegrationTest/kotlin/io/realm/SyncSessionTests.kt
=> Ensure alignment between test app and server admin interface

realm/realm-library/build.gradle
The object-store submodule head was a commit behind. Bumped it forward
=> Fix CI build process after merging upgrade build tools and gradle

realm-transformer/src/main/java/io/realm/transformer/RealmAnalytics.java, realm-transformer/src/main/java/io/realm/transformer/UrlEncodedAnalytics.java, realm-transformer/src/main/kotlin/io/realm/transformer/RealmTransformer.kt
This updates metrics with new resolution for Kotlin support and `target` to track if project is an application or library.
Also adds parallel segment upload.
=> Improved metrics

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp, realm/realm-library/src/main/java/io/realm/BaseRealm.java, realm/realm-library/src/main/java/io/realm/internal/OsSharedRealm.java
Closes https://github.com/realm/realm-java/issues/6977
=> Add test for realm version clean-up on close

CHANGELOG.md, dependencies.list
Upgrade to latest Core and Sync for 7.x
=> Upgrade to Sync 5.0.19

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java, realm/realm-library/src/androidTest/java/io/realm/entities/AllJavaTypes.java, realm/realm-library/src/androidTest/java/io/realm/entities/NullablePrimitiveFields.java, realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java
=> Fix retrieval of null valued primitive property from dynamic realm

realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java, realm/realm-library/src/androidTest/java/io/realm/RealmTests.java, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SyncedRealmTests.kt
This PR enables tests that were disabled by issues that are now fixed.
=> Reenable tests with resolved issues

Jenkinsfile, tools/publish_release.sh
- Add an option that disables integration tests. This can be useful when making a release and you don't want to wait for tests.
- Better formatting for the Slack notification user reporting things to our channels.
=> More CI improvements

CHANGELOG.md
This updates the changelog to reflect the most recent Studio releases.
=> Update changelog to reflect Realm Studio releases

CHANGELOG.md, dependencies.list
Closes https://github.com/realm/realm-java/issues/6969
=> Bump to Sync 5.0.24

realm/realm-library/src/objectServer/java/io/realm/mongodb/App.java
Now I'll get to pin Realm Java on my github profile 😍
=> Fix a typo in App API docs

realm/kotlin-extensions/src/androidTest/kotlin/io/realm/CoroutineTests.kt
Fixed race condition while closing realm.
=> Fixed race condition in toFlow_multipleSubscribers test

CHANGELOG.md, dependencies.list
Closes https://github.com/realm/realm-java/issues/7171
=> Update to Sync 10.1.0

realm/realm-library/src/main/java/io/realm/RealmObject.java
=> Add Decimal128 and ObjectId to supported types

CHANGELOG.md, dependencies.list
=> Prepare 10.1.0

Jenkinsfile
The CI build process fails when building the master release.
=> Fix monorepo CI build process

Jenkinsfile, realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp, realm/realm-library/src/main/java/io/realm/internal/OsRealmConfig.java
=> DO NOT MERGE - Core LTO fix

Jenkinsfile, realm/realm-library/build.gradle, realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java, realm/realm-library/src/main/cpp/CMakeLists.txt, realm/realm-library/src/main/cpp/io_realm_internal_OsObjectStore.cpp, realm/realm-library/src/main/cpp/util.cpp, realm/realm-library/src/main/java/io/realm/MutableRealmObjectSchema.java, realm/realm-library/src/main/java/io/realm/internal/OsObjectStore.java
This PR adds the latest Master changes into the new datatypes branch.
=> Merge Master branch into new datatypes

realm/realm-library/src/androidTest/kotlin/io/realm/rule/BlockingLooperThread.kt
Closes https://github.com/realm/realm-java/issues/7333.
Updated heavily outdated docs for `BlockingLooperThread` where we now point out a couple of things that need to be taken into consideration when using this solution in parameterised tests.
=> Updated docs for BlockingLooperThread

Jenkinsfile, tools/sync_test_server/app_config_generator.sh
Jenkins isn't able to boot docker images because we haven't updated the app templating logic to it.
=> Fix sync server for CI builds

realm/realm-library/src/main/java/io/realm/ManagedMapManager.java, realm/realm-library/src/main/java/io/realm/MapChangeSet.java, realm/realm-library/src/main/java/io/realm/OrderedRealmCollectionImpl.java, realm/realm-library/src/main/java/io/realm/RealmMap.java, realm/realm-library/src/main/java/io/realm/RealmMapEntrySet.java, realm/realm-library/src/main/java/io/realm/TypeSelectorForMap.java
Addresses issues raised by spotbugs and checkstyle.
=> Fix check style warnings

realm/realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.kt, realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.kt, realm/realm-annotations-processor/src/main/java/io/realm/processor/Utils.kt, realm/realm-library/src/androidTest/kotlin/io/realm/ManagedSetTester.kt, realm/realm-library/src/androidTest/kotlin/io/realm/NoPKRealmModelSetTester.kt, realm/realm-library/src/androidTest/kotlin/io/realm/NullMixedSetTester.kt, realm/realm-library/src/androidTest/kotlin/io/realm/ParameterizedSetTests.kt, realm/realm-library/src/androidTest/kotlin/io/realm/RealmModelManagedSetTester.kt, realm/realm-library/src/androidTest/kotlin/io/realm/UnmanagedSetTester.kt, realm/realm-library/src/main/java/io/realm/Mixed.java
Add supports for copyToRealm on Realm objects containing RealmSets.
=> Set  - 17: Add support for copyToRealm

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.kt, realm/realm-annotations-processor/src/main/java/io/realm/processor/Utils.kt, realm/realm-library/src/androidTest/kotlin/io/realm/ManagedSetTester.kt, realm/realm-library/src/androidTest/kotlin/io/realm/NoPKRealmModelSetTester.kt, realm/realm-library/src/androidTest/kotlin/io/realm/NullMixedSetTester.kt, realm/realm-library/src/androidTest/kotlin/io/realm/ParameterizedSetTests.kt, realm/realm-library/src/androidTest/kotlin/io/realm/RealmModelManagedSetTester.kt, realm/realm-library/src/androidTest/kotlin/io/realm/UnmanagedSetTester.kt, realm/realm-library/src/main/java/io/realm/internal/objectstore/OsObjectBuilder.java, realm/realm-library/src/testUtils/java/io/realm/entities/AllTypesPrimaryKey.java
Add supports for copyToRealm on Realm objects with PK containing RealmSets.
=> Set - 18: Add support for copy or update

realm/realm-library/src/androidTest/kotlin/io/realm/SetMiscTests.kt, realm/realm-library/src/androidTest/kotlin/io/realm/entities/SetContainerClass.kt, realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp, realm/realm-library/src/main/java/io/realm/ImmutableRealmObjectSchema.java, realm/realm-library/src/main/java/io/realm/MutableRealmObjectSchema.java, realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java, realm/realm-library/src/main/java/io/realm/internal/Table.java
=> Set - Added support for migrations

realm/realm-library/src/main/java/io/realm/ManagedMapManager.java, realm/realm-library/src/main/java/io/realm/RealmDictionary.java, realm/realm-library/src/main/java/io/realm/RealmMap.java
Documentation cleanup.
Optimised visibility in lots of non-API-public methods.
Added missing @Nullable annotations to suppress warnings.
=> Dictionary - misc cleanup

README.md
Updating the docs link for realm
=> Docs Link updated

CHANGELOG.md
fixed simple mistakes  in CHANGELOG.md
=> fixed misformatted entries in CHANGELOG.md

CHANGELOG.md, realm/realm-library/src/main/cpp/io_realm_internal_objectstore_OsSyncUser.cpp
Bumps core to version 11.1.1 in order to attempt fixing https://github.com/realm/realm-java/issues/7501
=> Bump core to version 11.1.1

README.md
=> Add survey CTA

CHANGELOG.md, realm/realm-library/src/main/java/io/realm/internal/modules/CompositeMediator.java
=> Fix copyToRealmOrUpdate for managed objects in multi module projects

CHANGELOG.md, dependencies.list, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/FlexibleSyncIntegrationTests.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SessionTests.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SubscriptionSetTests.kt, realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SyncedRealmTests.kt, realm/realm-library/src/main/cpp/io_realm_internal_OsObjectSchemaInfo.cpp, realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp, realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp, realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp, tools/sync_test_server/stop_local_server.sh
=> Update core 12.3.0

CHANGELOG.md, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java, realm/realm-library/src/testUtils/java/io/realm/entities/KeywordFieldNames.java
=> Update to Core 12.5.1 and tests for raw queries with keyword field names

CHANGELOG.md, Dockerfile, dependencies.list, realm/realm-library/src/main/cpp/io_realm_internal_OsList.cpp, realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp, realm/realm-library/src/main/cpp/io_realm_mongodb_sync_Sync.cpp, realm/realm-library/src/main/cpp/observable_collection_wrapper.hpp, realm/realm-library/src/main/cpp/observable_dictionary_wrapper.hpp, realm/realm-library/src/objectServer/java/io/realm/mongodb/ErrorCode.java
Bump core to version 1.6.0
closes https://github.com/realm/realm-java/issues/7716
=> Bump core 1.6.0

CHANGELOG.md, realm-transformer/src/main/kotlin/io/realm/analytics/RealmAnalytics.kt, realm-transformer/src/main/kotlin/io/realm/transformer/RealmTransformer.kt
Adoption of #7750 to enable CI verification. Have verified locally that the JSON payload is preserved with this fix.
=> Add support for gradle configuration cache

CHANGELOG.md, realm-transformer/src/main/kotlin/io/realm/transformer/build/BuildTemplate.kt
=> Fix zip path separator for transformer on Windows

CHANGELOG.md, dependencies.list, realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java, realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp, realm/realm-library/src/main/cpp/io_realm_internal_objectstore_OsApp.cpp, realm/realm-library/src/main/cpp/java_query_descriptor.cpp, realm/realm-library/src/main/cpp/java_query_descriptor.hpp, realm/realm-library/src/syncIntegrationTest/kotlin/io/realm/SyncSessionTests.kt, realm/realm-library/src/testUtils/java/io/realm/TestHelper.java
=> Add support for sorting on dictionary elements in raw queries
