realm/realm-java

changelog.txt
realm/src/androidTest/java/io/realm/RealmResultsTest.java
realm/src/main/java/io/realm/RealmResults.java

`RealmResults` inherits from `AbtractList`. This implies that `indexOf` will return 0 if not implemented. As we haven't yet implemented the method, it is safer to throw `NoSuchMethodError` when it is called.
@emanuelez @cmelchior @bmunkholm

Disabling indexOf()

---

changelog.txt
realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/main/java/io/realm/Realm.java

Added convenience method for using the begin/commit/cancel pattern for transactions. It also mirrors the functionality for RLMRealm.transactionWithBlock on Cocoa.
Note that while it actually looks like it is more difficult to write, IntelliJ folding + autocomplete means it actually require fewer keypresses plus folds nicely.
I added it as a inner public class in order to keep the global number of classes low.

Added Realm.executeTransaction() method

---

realm-jni/src/io_realm_internal_TableQuery.cpp
realm-jni/src/util.cpp
realm-jni/src/util.hpp

While poking at some other things I noticed a few easy spots to eliminate some bloat. Total savings is ~340 KB off realm.jar, most of which (~300 KB) is from the exception handling change. Should also improve performance insignificantly in non-error-cases due being more icache-friendly and doing less pointless refcounting at the cost of an also insignificant performance hit when exceptions are thrown.

Cut down on the size of the library a bit

---

changelog.txt
realm/src/androidTest/java/io/realm/NotificationsTest.java
realm/src/main/java/io/realm/Realm.java

This PR fixes the case where close() method removed the Thread handler to soon even though open instances still existed.
@bmunkholm @kneth @emanuelez

Thread handler no longer gets removed too soon.

---

changelog.txt
realm/src/androidTest/java/io/realm/RealmAdapterTest.java
realm/src/main/java/io/realm/RealmResults.java

Reenabled remove methods and documented their behaviour if called while inside loops.
@bmunkholm @kneth @emanuelez

Reenable RealmResults remove methods + document behavior

---

changelog.txt
realm/src/androidTest/java/io/realm/RealmQueryTest.java
realm/src/androidTest/java/io/realm/RealmResultsTest.java
realm/src/main/java/io/realm/Realm.java
realm/src/main/java/io/realm/RealmQuery.java

Changelog:
* Removed methods deprecated in 0.76. Now Realm.allObjectsSorted() and RealmQuery.findAllSorted() need to be used instead.

Remove deprecated sorting methods

---

realm-jni/build.gradle

This shaves 300KB from the jar file and for the libraries:
* ARM -200KB
* ARMv7a -300KB
* MIPS -600KB
* x86 -300KB

Using these compiler and linker flags to remove unused code

---

changelog.txt
realm-jni/build.gradle
realm-jni/generic.mk

This is done reactivating link-time optimizations and using strip.
It is now also easier to switch between any supported version of gcc and clang

Make the native libraries way smaller.

---

realm/src/androidTest/java/io/realm/RealmQueryTest.java
realm/src/main/java/io/realm/RealmList.java
realm/src/main/java/io/realm/RealmQuery.java

I found the bug of RealmQuery#findFirst() for queried ReamList.
FindFirst() may return different result of FindAll().get(0).
Code to reproduce:
```Java
public class Book extends RealmObject {
private String id;
private RealmList<Page> pages;
}
public class Page extends RealmObject {
private String id;
}
String book = "book_city";
String page = "city_japan";
RealmList<Page> pages = realm.where(Book.class)
.equalTo("id", book)
.findFirst()
.getPages();
RealmList<Page> page1 = pages.where()
.equalTo("id", page)
.findAll()
.get(0);
RealmList<Page> page2 = pages.where()
.equalTo("id", page)
.findFirst();
```
Data:
```
[book]      [page]
book_food   food_fast
book_food   food_chinese
book_food   food_japanese
book_city   city_america
book_city   city_japan
```
Results:
```
page1 -> city_japan …
```

Fix findFirst() for queried RealmList

---

realm/src/main/java/io/realm/Realm.java
realm/src/main/java/io/realm/RealmBaseAdapter.java
realm/src/main/java/io/realm/RealmChangeListener.java
realm/src/main/java/io/realm/RealmList.java
realm/src/main/java/io/realm/RealmObject.java
realm/src/main/java/io/realm/RealmQuery.java
realm/src/main/java/io/realm/RealmResults.java

In general JavaDoc isn't like markdown, and some HTML formatting must be added in order to generate some better formatted HTML for the website. In particular, this includes empty line (should be `<p>`) and unordered list.
@emanuelez @cmelchior

Adding light HTML markup to JavaDoc so documentation website looks better

---

examples/threadExample/src/main/java/io/realm/examples/threads/ThreadFragment.java

This fixes the Thread example which tried to access resources after fragment was detached.
It also now properly kills the background thread.

Made Thread example more resilient to monkey test events.

---

realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
realm/src/androidTest/assets/list_alltypes_primarykey.json
realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/androidTest/java/io/realm/entities/AllTypesPrimaryKey.java
realm/src/androidTest/java/io/realm/entities/DogPrimaryKey.java

A bug was discovered when using copyToRealmOrUpdate on child elements with primary keys: https://groups.google.com/forum/#!topic/realm-java/V7AVHgU5Oo4 which caused child objects to always be copied.
It wasn't caught due to a bug in some unit tests *cough*.
This PR fixes both the bug and the unit tests.

Child objects with PK are now updated/copied correctly

---

changelog.txt
realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/androidTest/java/io/realm/entities/Cat.java
realm/src/androidTest/java/io/realm/entities/OwnerPrimaryKey.java
realm/src/androidTest/java/io/realm/entities/PrimaryKeyMix.java

This PR fixes: https://github.com/realm/realm-java/issues/864
Before, the update flag was cleared if an class didn't contain a primary key. This could cause duplicate entry errors if that object contained references to objects with primary keys as they where only copied.

Fix crash when using copyToRealmOrUpdate with complex object graph

---

realm/src/androidTest/java/io/realm/RealmQueryTest.java

In #871 a user reports an issue with Georgian words in query. I have added a test which uses `RealmQuery.contains()` and `RealmResults.sort()`.

Testing Georgian words.

---

realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java
realm-annotations-processor/src/main/java/io/realm/processor/RealmVersionChecker.java

This is done by making a singleton out of RealmVersionChecker.
It’s not doable in RealmProcessor since one new instance of the processor is created per round.

Only do the version checker on the first round of the processor.

---

changelog.txt
realm-annotations-processor/src/main/java/io/realm/processor/RealmJsonTypeHelper.java
realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm-annotations-processor/src/test/java/io/realm/processor/RealmProcessorTest.java
realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm-annotations-processor/src/test/resources/some/test/AllTypes.java
realm-annotations-processor/src/test/resources/some/test/FieldNames.java

This PR fixes this issue: https://github.com/realm/realm-java/issues/881
It makes sure that object references are properly suffixed so they don't conflict with internal variabel names (This only happened in one JSON import function).

Allow all names in model classes

---

changelog.txt
realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/main/java/io/realm/Realm.java

Properly check for key equality while using a cached Realm instance

---

realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java
realm-annotations-processor/src/main/java/io/realm/processor/Constants.java
realm-annotations-processor/src/main/java/io/realm/processor/RealmJSonImplGenerator.java
realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java
realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm-annotations-processor/src/main/java/io/realm/processor/RealmValidationListGenerator.java
realm-annotations-processor/src/main/java/io/realm/processor/Utils.java
realm/src/androidTest/java/io/realm/RealmTest.java

Part of #880 
This PR refactors RealmProcessor so all information about a ProxyClass is now generated and encapsulated inside ClassMetaData. This makes it easier to move information about the proxy classes around as well as making the responsibility of the RealmProcessor class much cleaner.

Refactored RealmProcessor to make it easier to add changes.

---

realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java
realm-annotations-processor/src/test/java/io/realm/processor/RealmProcessorTest.java
realm-jni/src/io_realm_internal_table.cpp
realm-jni/src/util.cpp
realm-jni/src/util.hpp

Fixes a bug where having no fields crashes Realm.
@kneth @emanuelez @bmunkholm

Annotation processor now fails if a RealmObject contains no fields.

---

realm-annotations-processor/build.gradle
realm/build.gradle

Fixes #950 
We inline JavaWriter to avoid version conflicts with other libraries, but don't repackage it which then causes class name conflicts. This PR repackages it as well to avoid these kinds of conflicts.

Repackage JavaWriter to avoid name conflicts with other libraries.

---

changelog.txt
realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/androidTest/java/io/realm/entities/PrimaryKeyAsString.java
realm/src/androidTest/java/io/realm/internal/JNITransactions.java
realm/src/main/java/io/realm/Realm.java
realm/src/main/java/io/realm/internal/Table.java

Fixes https://github.com/realm/realm-java/issues/993
This PR adds a package protected method ```Realm.createObject(Class clazz, Object primaryKeyValue);```
This was needed to fix the above bug, and we have before talked about adding such a method as Cocoa has it. I am still not convinced we should make it public as using copyToRealm() is an acceptable workaround imho (See isse for details), but I am open for discussing it.

Fixed bug in Realm.copyToRealm() with primary key values

---

CONTRIBUTING.md
README.md

I’m proposing me move this section to CONTRIBUTING.md since that is the file Github points you to when you try to open an issue, and this section was previous too low in the README to really be read by many. (This section is also in CONTRIBUTING.md in realm-cocoa repo).
But if you prefer it in the README, feel free to close this PR.

Move issue instructions to CONTRIBUTING

---

build.gradle
realm-annotations-processor/build.gradle
realm-annotations/build.gradle

We can now edit the version.txt from GitHub. Yay

Linebreaks in version.txt no longer breaks build

---

changelog.txt
realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
realm/src/androidTest/java/io/realm/NotificationsTest.java
realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/main/java/io/realm/Realm.java

Fixes #1040 
@emanuelez @bmunkholm @kneth

Realm IDs are now its absolute path instead of its hashcode

---

changelog.txt
realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/main/java/io/realm/Realm.java

Fixes #1051 
We now throw a proper exception instead of crashing core.
@emanuelez @bmunkholm @kneth

Throw exception if using copyToRealmOrUpdate with a null primary key value

---

changelog.txt
realm-annotations-processor/src/main/java/io/realm/processor/RealmJsonTypeHelper.java
realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/src/androidTest/assets/list_alltypes_primarykey.json
realm/src/androidTest/java/io/realm/RealmJsonTest.java

Fixes #1095 
Date and byte[] fields where incorrectly reset even though this bug was fixed in the last release.
Lesson learned: Remember to unit test all types :(

Fix Date and byte[] being reset when using createOrUpdateFromJson

---

realm/src/main/java/io/realm/Realm.java

Add java.lang prefix to @throws comment to avoid ambiguity.

---

changelog.txt
realm/src/main/java/io/realm/Realm.java

Fixes #1109
We now use WeakReferences to store the change listeners.
This allows the Garbage Collector to clean up the adapters.

Fix a memory leak in RealmBaseAdapter

---

changelog.txt
realm/src/androidTest/java/io/realm/NotificationsTest.java
realm/src/main/java/io/realm/Realm.java

This PR makes the OnRealmChanged callback behave more as expected and puts it in line with Realm-Cocoa behaviour.
Previously, callbacks registered on the thread doing the commit was not triggered, this is now the case. In order avoid weird cases like be below. The OnRealmChangedListener is called immediately instead of using the Handler mechanism.
```
// If using Handler messages, the following would be possible. By calling listeners at once, this is avoided.
realm.beginTransaction();
...
realm.commitTransaction();
realm.addChangeListener(new RealmChangedListener() {
// This would get triggered even though it was added after the commit.
});
```
@emanuelez @kneth @jpsim @bmunkholm

RealmChangedListener now gets called on the same thread doing the commit

---

realm/src/androidTest/java/io/realm/NotificationsTest.java
realm/src/main/java/io/realm/Realm.java

This is caused by 54501237b3 which doesn't seem to be right behaviour.

Fix sendNotifications called twice

---

realm/src/main/java/io/realm/Realm.java

Add Javadoc comment which specifies that Realm.deleteRealmFile(...) throws IllegalStateException if target Reealm file is not closed.

---

changelog.txt
realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/src/androidTest/java/io/realm/RealmListTest.java

Adding objects using a RealmLists now properly clears any previous data.

---

realm/src/androidTest/java/io/realm/NotificationsTest.java
realm/src/androidTest/java/io/realm/RealmConfigurationTest.java
realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/androidTest/java/io/realm/TestHelper.java
realm/src/main/java/io/realm/Realm.java
realm/src/main/java/io/realm/RealmConfiguration.java
realm/src/main/java/io/realm/RealmList.java
realm/src/main/java/io/realm/internal/RealmProxyMediator.java

This changes the Realm caching to work on RealmConfiguration instead of path alone. This is needed to catch subtle errors that path alone cannot, eg. different schema versions in the configuration and different configured schemas.
This means that an IllegalArgumentException will be thrown if:
- Encryption key in two different configurations pointing to the same file are used
- Schema version is different in two different configurations pointing to the same file
- The configured schema is different in two different configurations pointing to the same file.

RealmConfiguration used as cache key

---

realm/build.gradle

Fixes #893 
This assumes that the S3 credentials have already been setup with s3cmd --configure on the hosting machine

Use s3cmd to perform the deployment of releases

---

realm/src/main/java/io/realm/RealmList.java

Small fix for an issue that crept up when reviewing DynamicObject. 
Realm theoretically support collections larger that Integer.MAX_VALUE. Collections.size() has a return type of int and right now we just cast the size potentially overflowing the value. 
For reference: http://docs.oracle.com/javase/7/docs/api/java/util/Collection.html#size()
@emanuelez @nhachicha @kneth 
No changelog, because....really?

size() now respect the Collection.size() contract.

---

realm/src/main/java/io/realm/Realm.java

Our current check for testing for the correct thread is stupidly expensive and it is executed for each accessor. It should be enough to just compare thread ID's.
An informal benchmark showed a ~20% speed increase when running RealmResultsTest.
@emanuelez @kneth @nhachicha @beeender

Optimised thread check.

---

realm/src/main/java/io/realm/RealmConfiguration.java

Should be the type of `schemaVersion` of `RealmConfiguration` `long`?
It seems to assume `long` anywhere using other `schemaVersion`.
https://github.com/realm/realm-java/blob/master/realm/src/main/java/io/realm/Realm.java#L1534
https://github.com/realm/realm-java/blob/master/realm/src/main/java/io/realm/Realm.java#L601-L602
https://github.com/realm/realm-java/blob/master/realm/src/main/java/io/realm/RealmMigration.java#L62
@cmelchior @emanuelez @kneth

Type of `schemaVersion` of `RealmConfiguration` should be `long`

---

changelog.txt
realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/main/java/io/realm/Realm.java

Without checking the thread in close, some weird logic could be
triggered which is really hard to think about.
I was thinking maybe this would cause #1241 , but according to the feedback, this might not the root cause. But anyway, it is something worth to fix.

Throw exception when close called on a diff thread.

---

realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java
realm-jni/src/io_realm_internal_CheckedRow.cpp
realm-jni/src/io_realm_internal_CheckedRow.h
realm-jni/src/io_realm_internal_UncheckedRow.cpp
realm-jni/src/io_realm_internal_UncheckedRow.h
realm/build.gradle
realm/src/androidTest/java/io/realm/DynamicRealmListTest.java
realm/src/androidTest/java/io/realm/DynamicRealmObjectTest.java
realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/androidTest/java/io/realm/TestHelper.java
realm/src/androidTest/java/io/realm/entities/AllJavaTypes.java
realm/src/main/java/io/realm/RealmObject.java
realm/src/main/java/io/realm/dynamic/DynamicRealmList.java
realm/src/main/java/io/realm/dynamic/DynamicRealmObject.java
realm/src/main/java/io/realm/internal/CheckedRow.java
realm/src/main/java/io/realm/internal/InvalidRow.java
realm/src/main/java/io/realm/internal/Row.java
realm/src/main/java/io/realm/internal/Table.java
realm/src/main/java/io/realm/internal/UncheckedRow.java

This PR is a prerequisite for the new Migration API. It adds support for manipulating RealmObjects/RealmList using a Dynamic API instead of the current type safe one.
Implementation details:
DynamicRealmList currently only extends AbstractList instead of RealmList. This is to avoid also having to make a dynamic query API as well, which seemed a bit overkill for migration purposes. For a full blown dynamic API it will be needed, but for the purpose of Migrations I think it can be left out.
```
public interface DynamicRealmObjectInterface {
boolean getBoolean(String fieldName);
int getInt(String fieldName);
short getShort(String fieldName);
long getLong(String fieldName);
byte getByte(String fieldName);
float getFloat(String fieldName);
double getDouble(String fieldName);
byte[] …
```

Dynamic API

---

changelog.txt

`setDate` will check range of date object as Integer.
https://github.com/realm/realm-java/blob/master/realm/src/main/java/io/realm/internal/UncheckedRow.java#L194-L203
So, the lower bound is -2147483648 and will convert "Fri, 13 Dec 1901 20:45:52 GMT".
http://www.epochconverter.com/

Fixed incorrect old changelog's description

---

changelog.txt
realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java
realm-annotations-processor/src/main/java/io/realm/processor/Constants.java
realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm-annotations-processor/src/test/java/io/realm/processor/RealmProcessorTest.java
realm-annotations-processor/src/test/java/io/realm/processor/TestRealmObjectFileObject.java
realm-annotations/src/main/java/io/realm/annotations/Index.java
realm-jni/src/io_realm_internal_table.cpp
realm/src/androidTest/java/io/realm/RealmAnnotationTest.java
realm/src/androidTest/java/io/realm/entities/AnnotationIndexTypes.java
realm/src/androidTest/java/io/realm/internal/JNITableTest.java

1. Enable the search index annotation on byte, short, int, long,
boolean, and Date.
2. Enable add/remove search index in java.
3. Annotation processor test to support better detailed test cases.
4. Refactor RealmQueryTest to apply all normal query test cases on a
RealmObject with indexed fields.
5. Modify JNI test cases.
6. Update doc.
This is the first PR for #1039. Implicit index to int primary keys will
be handled in another PR.

Support search indexing for column int, bool, date

---

realm/src/androidTest/java/io/realm/RealmResultsTest.java
realm/src/main/java/io/realm/RealmResults.java

Documenting that RealmResults.{first,last} throw exception if result is empty. I have added a simple unit test and added the exception to the documentation.
Closes #1102.
@realm/java

Document RealmResults.{first,last} can throw

---

changelog.txt
realm-jni/src/io_realm_internal_tableview.cpp
realm/src/androidTest/java/io/realm/RealmQueryTest.java
realm/src/androidTest/java/io/realm/TestHelper.java
realm/src/main/java/io/realm/internal/TableQuery.java
realm/src/main/java/io/realm/internal/TableView.java

A reported in #1161, querying `RealmResults` might lead to a crash. The reason seems to be that a `TableQuery` might be finalised prematurely, and the native resource is freed. When the native resource is freed, accessing it will cause a segmentation fault.
This fixes #1161 by adding references to TableView and TableQuery in order to prevent premature garbage collection.
@emanuelez @cmelchior @beeender

Querying RealmResults can crash

---

changelog.txt
realm-jni/src/io_realm_internal_TableQuery.cpp
realm/src/androidTest/java/io/realm/RealmLinkTests.java

As discussed at length in #1237 `RealmQuery.between()` does not work as expected in many cases. As the underlaying storage engine does not provide a operator directly, I think it is better for remove it.
@realm/java

Removed RealmQuery.between() for link queries

---

realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java
realm-annotations-processor/src/main/java/io/realm/processor/RealmAnalytics.java
realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java
realm-annotations-processor/src/main/java/io/realm/processor/Utils.java

Asynchronously submits build information to Realm when the annotation processor is running
To be clear: this does *not* run when your app is in production or on your end-user’s devices; it will only run when you build your app from source.
Why are we doing this? Because it helps us build a better product for you. None of the data personally identifies you, your employer or your app, but it *will* help us understand what Realm version you use, what host OS you use, etc. Having this info will help with prioritizing our time, adding new features and deprecating old features. Collecting an anonymized bundle & anonymized MAC is the only way for us to count actual usage of the other metrics accurately. If we don’t have a way to deduplicate the info reported, it will be useless, as a single …

Add analytics on annotation

---

realm/src/main/java/io/realm/RealmList.java
realm/src/main/java/io/realm/RealmResults.java
realm/src/main/java/io/realm/internal/ImplicitTransaction.java

Fixes #1165 
All @InheritDoc tags has been replaced with proper documentation as @InheritDoc doesn't work well with the Android SDK.
@realm/java

Replaced all @InheritDoc with proper documentation.

---

changelog.txt
realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java
realm/src/androidTest/java/io/realm/RealmConfigurationTest.java
realm/src/main/java/io/realm/RealmConfiguration.java

Fixes #1302
We had a fair amount of issues over the last weeks where people did not properly understanding when to use Realm.getDefaultModule(), which means they used even when no DefaultModule was created. This is fairly common when all your RealmClasses are in a library and your application just uses the RealmClasses from that library. 
This PR relaxes the requirements and allows a smaller programmer error by ignoring null values parsed to `RealmConfiguration.setModules()`. It turned out that returning a empty module would require a lot more code.
See #1302 for possible other solutions.
@realm/java

RealmConfiguration now accepts Null modules

---

changelog.txt
realm-annotations-processor/src/main/java/io/realm/processor/RealmJsonTypeHelper.java
realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm-annotations-processor/src/main/java/io/realm/processor/Utils.java
realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
realm/src/androidTest/assets/all_types_primary_key_null.json
realm/src/androidTest/java/io/realm/RealmJsonTest.java

Fix #1344
Update the object's String field to empty string when the corresponding
field in Json is null.

Handle null value for String in Json when updating

---

examples/kotlinExample/build.gradle

Apparently incremental build doesn't work with Kotlin (reported by a user). 
Example has been updated with that info.
@realm/java

Updated Kotlin example with incremental build setting

---

changelog.txt
realm/src/androidTest/java/io/realm/RealmObjectTest.java
realm/src/main/java/io/realm/internal/InvalidRow.java

#1393 reports a bug in `isValid()`. When an object is deleted from a Realm, the underlaying row is change to an instance of the invalid row. Methods of invalid rows throw an exception unconditionally.
Fixes #1393
@realm/java

isValid should not throw

---

realm/src/main/java/io/realm/internal/CheckedRow.java
realm/src/main/java/io/realm/internal/Context.java
realm/src/main/java/io/realm/internal/UncheckedRow.java

HashMap value of rowReferences is never used but the HashMap.put() call is always using a Integer.MIN_VALUE as value arg which is small integer and causes autoboxing allocations to Integer().
Use static Integer object to remove autoboxing and Integer object allocations.

Reduce rowReferences HashMap autoboxing allocations.

---

realm/src/main/java/io/realm/internal/Group.java
realm/src/main/java/io/realm/internal/SharedGroup.java

Cleanup native methods to match earlier discussed style (=grouped at the bottom of the class).
Preparing for bugfix for #1406

Cleanup SharedGroup.java and Group.java

---

realm/src/main/java/io/realm/Realm.java

writeEncryptedCopyTo might throw RealmEncryptionNotSupportedException as well.

writeEncryptedCopyTo might throw RENSE

---

README.md

We will abolish current office hour system. So We are going to remove the go-to-meeting's link everywhere. I've deleted the sentence about office hour in README.md.
Could you please review this?
/cc @emanuelez @timanglade
same as realm-cocoa: https://github.com/realm/realm-cocoa/pull/2498

remove about office hour from README.md

---

changelog.txt
realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/main/java/io/realm/Realm.java

Fixes #1373 
Prevents a long living write transaction on a background thread blocking opening Realm on the UI thread if it is the same file, as we then are sure that the schema has already been validated.
@realm/java

Schemas are now only validated once across threads.

---

build.gradle
realm-jni/build.gradle

And introduced SHA-256 hash checking to archive file.
The archive file is downloaded only when specified hash differs from local archive.
When new core is comming, please update 'ext.coreSha256Hash' in realm-jni/build.gradle in addition to 'ext.coreVersion'.

moved core files into realm-jni/build/ and keep archive file of core under root project. related to #1479

---

realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/androidTest/java/io/realm/TestHelper.java
realm/src/main/java/io/realm/BaseRealm.java
realm/src/main/java/io/realm/Realm.java
realm/src/main/java/io/realm/RealmConfiguration.java
realm/src/main/java/io/realm/dynamic/DynamicRealmObject.java
realm/src/main/java/io/realm/internal/SharedGroup.java
realm/src/main/java/io/realm/internal/SharedGroupManager.java

**Description**
Two new abstractions has been added: SharedGroupManager and RealmBase
- *SharedGroupManager*: Encapsulates the SharedGroup and Transaction to encapsulate reuse across Realm/DynamicRealm.
- *RealmBase*: Abstract class for sharing code/logic between Realm/DynamicRealm. 
**Missing**:

Introduce RealmBase and SharedGroupManager

---

realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/main/java/io/realm/Realm.java

This fixes a recently introduced bug (caught by the async branch) where column indices are not configured correctly if the same Realm is opened on multiple threads causing queries to crash.
@realm/java

ColumnIndices are now setup correctly for all Realms

---

realm/src/androidTest/java/io/realm/NotificationsTest.java
realm/src/androidTest/java/io/realm/TestHelper.java
realm/src/main/java/io/realm/BaseRealm.java

This PR is the result of some bug hunting and turned out some minor issues:
1) If a Looper is explicitly quit (e.g. a IntentService). We risk triggering warnings in the Log with the following wording "Handler sending message to a handler on a dead thread". An additional log message is now added with a description on how to avoid this.
2) If using `realm.setAutoRefresh(false)` the internal handler is not properly cleared. This has now been fixed.
@realm/java

Fixed handler not being removed when using setAutoRefresh(false)

---

changelog.txt
realm-jni/src/io_realm_internal_TableQuery.cpp
realm-jni/src/io_realm_internal_table.cpp
realm-jni/src/io_realm_internal_tableview.cpp
realm-jni/src/mixedutil.cpp
realm/src/androidTest/java/io/realm/RealmObjectTest.java
realm/src/androidTest/java/io/realm/RealmQueryTest.java
realm/src/androidTest/java/io/realm/RealmResultsTest.java
realm/src/androidTest/java/io/realm/internal/JNIQueryTest.java
realm/src/main/java/io/realm/internal/UncheckedRow.java

Original code:
* `Date` value had range check when copied into Realm.
* `Date` value was cast to 32bit signed integer when copied from Realm.
* `Date` query parameters are also cast to 32bit signed integer.
This PR removes these checks and casts in order to expand `Date` range.

Expand Date range(#1510)

---

realm/build.gradle

Problem:
Language of generated Javadoc depends on build environment, because no locale/charset information is explicitly provided.
If Javadoc is generated on Japanese environment, generated Javadoc contains クラス instead of Classes.
This PR fixes that problem by prioviding explicit locale and charset information.

Fix locale and encoding of Javadoc

---

realm/src/main/java/io/realm/BaseRealm.java

We had a bug reported against current master:
```
88    09-26 22:15:09.497 E/ACRA ( 438): ACRA caught a ArrayIndexOutOfBoundsException for com.podfather.podfather
89    09-26 22:15:09.497 E/ACRA ( 438): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
90    09-26 22:15:09.497 E/ACRA ( 438): at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:117)
91    09-26 22:15:09.497 E/ACRA ( 438): at io.realm.BaseRealm.validateAgainstExistingConfigurations(BaseRealm.java:482)
92    09-26 22:15:09.497 E/ACRA ( 438): at io.realm.Realm.createAndValidate(Realm.java:276)
93    09-26 22:15:09.497 E/ACRA ( 438): at io.realm.Realm.create(Realm.java:245)
94    09-26 22:15:09.497 E/ACRA ( 438): at io.realm.Realm.getDefaultInstance(Realm.java:200)
95    09-26 22:15:09.497 …
```

Guard globalPathConfigurationCache properly.

---

changelog.txt
realm-jni/src/io_realm_internal_LinkView.cpp
realm-jni/src/io_realm_internal_LinkView.h
realm/src/androidTest/java/io/realm/RealmListTest.java
realm/src/main/java/io/realm/RealmList.java
realm/src/main/java/io/realm/internal/LinkView.java

This commit fixes #1561
Methods listed below in RealmList now throws IllegalStateException if container object has been removed or Realm instance has been closed.
* add(int,RealmOject)
* add(RealmObject)
* set(int,RealmObject)
* move(int,int)
* clear()
* remove(int)
* remove(int)
* remove(RealmObject)
* removeAll(Collection)
* get(int)
* first()
* last()
* size()
* where()
RealmList#toString() now returns "<ClassName>@[invalid]" if container object has been removed or Realm instance has been closed.

Fix native crash and wrong exception in RealmList.

---

realm/src/main/java/io/realm/internal/TableQuery.java

Preparing to add `isEmpty()`
This reorders the native methods + fix their visibility pr. previous style fixes in other classes.
@realm/java

Cleanup native methods in TableQuery

---

changelog.txt
realm/src/androidTest/java/io/realm/internal/JNIQueryTest.java
realm/src/main/java/io/realm/internal/TableQuery.java

Fixed a bug in `RealmQuery.isNull()` and `RealmQuery.isNotNull()` which validated the query prematurely.
@cmelchior @beeender

Premature query validation

---

changelog.txt
realm-jni/src/io_realm_internal_table.cpp
realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/main/java/io/realm/Realm.java

Issue #960 requests a `distinct()` method. As Realm's underlying storage engine added support for the method recently, it is time to add such a method to Realm Java.
Closes #960 
@realm/java

Adding Realm.distinct() method.

---

changelog.txt
realm/src/main/java/io/realm/BaseRealm.java

Fixes #1608 
To qoute Dianne Hackborn: "Once you think you understand concurrency, It will jump right back and bite you" :(
Also WTF is a method called `removeCallbacksAndMessages` not removing the only thing in the Handler API actually called Callback.
Problem is that we store our handlers in a ConcurrentHashMap. This means that if we start iterating over them in another thread it is over a copy of the map, so if a Realm is closed in the meantime on the original thread, the iterator will still post messages to it. At the same time, we have no way of telling the handler on the original thread to actually stop handling messages.
Only way around this would be to synchronize access to all our handlers, which I want to avoid for performance reasons as the Handlers are our main way of …

Fixed race condition when closing Realms

---

changelog.txt
realm-jni/src/io_realm_internal_TableQuery.cpp
realm-jni/src/io_realm_internal_TableQuery.h
realm/src/androidTest/java/io/realm/RealmQueryTest.java
realm/src/main/java/io/realm/RealmQuery.java
realm/src/main/java/io/realm/internal/TableQuery.java

Fixes #1601 
Adds a method to RealmQuery called `isEmpty()` it can be used to check if Strings are empty (non-null), binary arrays have length 0 (non-null) and if RealmLists have size 0. 
That last was the primary reason as this was no longer possible after adding Null support.
@realm/java

Add RealmQuery.isEmpty()

---

realm/src/main/java/io/realm/Realm.java

`loadMediatorClass(Realm)` and `setupColumnIndices(Realm)` are completely the same.

remove `loadMediatorClass(Realm)`

---

changelog.txt
realm/src/androidTest/java/io/realm/RealmMigrationTests.java
realm/src/main/java/io/realm/BaseRealm.java

Found while investigating #1610 
It should not be possible to migrate open Realms as that can potentially invalidate the schema. As the schema is only validated when opening the Realm this can cause all kinds of strange behavior in querying/reading and writing data.
@realm/java

Prevent migration of open Realms

---

changelog.txt
realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/src/androidTest/java/io/realm/RealmListTest.java
realm/src/androidTest/java/io/realm/RealmObjectTest.java
realm/src/androidTest/java/io/realm/RealmResultsTest.java
realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/main/java/io/realm/Realm.java
realm/src/main/java/io/realm/RealmList.java
realm/src/main/java/io/realm/RealmObject.java
realm/src/main/java/io/realm/RealmQuery.java
realm/src/main/java/io/realm/RealmResults.java

* Generate realm check for getter and setter of RealmObject and RealmList.
* Add realm check in RealmObject.removeFromRealm
* Add realm check in RealmResults's remove, removeLast, clear methods
* Add test cases
* Minor warning fix
Maybe related with #1554 ?

Missing realm check in some functions

---

realm/src/androidTest/java/io/realm/RealmTest.java
realm/src/main/java/io/realm/Realm.java

Problem:
`Realm#lastLocalInstanceClosed()` which is called by `Realm#close()` can remove entries from `validatedRealmFiles` while other thread is executing `Realm#createAndValidate()`.
This might lead to `null` assignment to `Realm.columnIndices`.
Solution:
Modified to deal with `validatedRealmFiles` in synchronized block of `Realm.class`.
this PR fixes #1646

fix possible null assignment to Realm.columnIndices.

---

realm-annotations/src/main/java/io/realm/annotations/Required.java

Currently (as documented in #1647) the `@Required` annotation, when used from a constructor in Kotlin, must be applied to a field explicitly using Kotlin's `@field:` syntax.
This change brings the annotations for the `@Required` interface in line with other Realm annotation interfaces to improve Kotlin compatibility. It follows the same format found in the `@Ignore`, `@Index` and `@PrimaryKey` annotations.
cc @zaki50

Add annotations to @Required for better Kotlin compatibility

---

changelog.txt
realm-annotations-processor/src/main/java/io/realm/processor/Constants.java
realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java

we had twe kind of warnings.
* rawtype
* useless cast
This PR fixes #1644
TODO:

fix RealmProxy code generator to avoid warnings

---

realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java

If model class has no primary key, we don't need to generate `update()` method in generated Proxy class.
fixes #1660

Removed update() method from generated proxy class corresponding to un-updatable model.

---

realm/src/androidTest/java/io/realm/RealmTest.java

Fixes #1417 
With core upgraded to 0.93+, this now throws an error in Core. Since we still have an `immutable` boolean in group it makes sense to keep the check there. So this PR just adds the test to verify that the behaviour doesn't change.
@realm/java

Check that double commit throws.

---

changelog.txt
realm/src/androidTest/java/io/realm/RealmConfigurationTest.java
realm/src/main/java/io/realm/RealmConfiguration.java

Saving and providing a mutable reference of the key is both a security threat and possibly the origin of subtle bugs.
We now make security copies of the byte arrays to solve the issue.

Make security copies of the key in RealmConfiguration

---

changelog.txt
realm/src/main/java/io/realm/exceptions/RealmEncryptionNotSupportedException.java
realm/src/main/java/io/realm/exceptions/RealmError.java
realm/src/main/java/io/realm/exceptions/RealmIOException.java
realm/src/main/java/io/realm/exceptions/RealmMigrationNeededException.java
realm/src/main/java/io/realm/exceptions/RealmPrimaryKeyConstraintException.java
realm/src/main/java/io/realm/internal/ColumnType.java
realm/src/main/java/io/realm/internal/Keep.java
realm/src/main/java/io/realm/internal/OutOfMemoryError.java
realm/src/main/java/io/realm/internal/TableSpec.java
realm/src/main/java/io/realm/internal/async/BadVersionException.java

Related to #1658
Introduced `@Keep` annotation.
Using `@Keep` annotation, we can simply write ProGuard configuration like:
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class *
instead of
```
-keep class io.realm.exceptions.* { *; }
-keep class io.realm.internal.async.BadVersionException { *; }
-keep class io.realm.internal.OutOfMemoryError { *; }
-keep class io.realm.internal.TableSpec { *; }
-keep class io.realm.internal.ColumnType { *; }
```
TODO:
fixes #1658

introduce @Keep annotation to mark classes to be kept by ProGuard/DexGuard

---

realm-annotations-processor/src/main/java/io/realm/processor/RealmVersionChecker.java

If a user is in the separate network and he/she needs http proxy setting for accessing the Internet,
latest version string may not com from our server.
To deal with that situation, this change adds the check that obtained latest version string has expected format.
@realm/java 
fixes #1666

Add format check to latest version string obtained from our server.

---

realm/src/androidTest/java/io/realm/RealmTest.java

It's a really simple fix. Please review this @realm/java

Fix an indentation of testCopyOrUpdateIterable

---

changelog.txt
realm-jni/src/io_realm_internal_table.cpp
realm/src/androidTest/java/io/realm/internal/JNITableTest.java

`Table.convertColumnToNotNullable` did not create a non-nullable column, but a nullable one.
@realm/java

convertColumnToNotNullable now works correctly.

---

changelog.txt
realm/realm-jni/src/io_realm_internal_Group.cpp
realm/realm-jni/src/io_realm_internal_Group.h
realm/realm-jni/src/io_realm_internal_Util.cpp
realm/realm-jni/src/io_realm_internal_Util.h
realm/realm-jni/src/util.hpp
realm/realm-library/src/androidTest/java/io/realm/RealmTest.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/internal/Group.java
realm/realm-library/src/main/java/io/realm/internal/Table.java
realm/realm-library/src/main/java/io/realm/internal/Util.java

Added Realm.isEmpty()

---

gradle.properties

I encountered the following error.
```
Execution failed for task ':assembleExamples.'.
> Failed to notify build listener.
> PermGen space
```
So I increased the default MaxPermSize to 512m.
Please review this, @realm/java.

Increase XX:MaxPermSize to avoid PermGen space problem.

---

changelog.txt
realm/realm-jni/src/io_realm_internal_TableQuery.cpp
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTest.java

Currently, `isNull()`/`isNotNull()` for linked field whose last element is a link is not supported.
We should throw `IllegalArgumentException` instead of `RealmError` if that happened.
refs #1693

throws IllegalArgumentException if isNull/isNotNull is called for unsupported field.

---

realm/realm-library/src/androidTest/java/io/realm/internal/JNITableTest.java

Due to an embarrassing error a unit test, the bug #1695 wasn't discovered before release. Retrospectively, the unit tests are complex and need a few comments to understand what is tested.
@realm/java

Extending tests for converting tables

---

changelog.txt
realm/realm-library/src/androidTest/java/io/realm/RealmTest.java
realm/realm-library/src/main/java/io/realm/internal/CheckedRow.java
realm/realm-library/src/main/java/io/realm/internal/Context.java
realm/realm-library/src/main/java/io/realm/internal/LinkView.java
realm/realm-library/src/main/java/io/realm/internal/NativeObjectReference.java
realm/realm-library/src/main/java/io/realm/internal/UncheckedRow.java

* Add abstract method to NativeObjectReference for native resource
releasing.
* Implement NativeObjectReference.cleanup for UncheckRow and LinkView

Release LinkView native pointers

---

changelog.txt
realm/realm-library/src/androidTest/java/io/realm/RealmTest.java
realm/realm-library/src/main/java/io/realm/Realm.java

To close #1728
The only usage of the Realm instance counter for now is to clean up
validatedRealmFiles.
We do need to refactor the whole counter/cache part.

Add counter for Realm instance for all threads.

---

changelog.txt
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTest.java

fixes #1749 and is related to #1745

Setters for RealmObject and RealmList now throw IllegalArgumentException if the value contains an invalid object.

---

changelog.txt
realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTest.java
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmAsyncTask.java

Fixes #1682
Checking to see if a transaction is currently in progress for sync and async transaction pathways. Also adding logging. Added a test helper to assist with log assertion.

Checking to see if a transaction is in progress & more.

---

realm/realm-library/src/androidTest/java/io/realm/RealmQueryTest.java
realm/realm-library/src/androidTest/java/io/realm/RealmResultsTest.java
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java

Added tests for aggregation methods in `RealmQuery` for partial null rows .
`RealmQueryTest.testSumGivesCorrectValueForPartialNullRows()` and `RealmQueryTest.testAvgGivesCorrectValueForAllNonNullRows()` tests wrong value for now.
These tests must be updated after core's fix.
related to #1803

Add tests of average for nullable column

---

changelog.txt
realm/realm-library/src/androidTest/java/io/realm/NotificationsTest.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmBaseAdapter.java
realm/realm-library/src/main/java/io/realm/RealmChangeListener.java

**Breaking change:**
`realm.addChangeListener` hold a string reference 
```java
realm.addChangeListener(listener); //keep a strong reference to listener
realm.removeChangeListener(listener); // to remove a non-anonymous listener
realm.removeAllChangeListeners(); // to remove all listeners (including anonymous one)
realm. addChangeListenerAsWeakReference(listener); // add a WeakReference listener (this is package-private) for internal use only (RealmBaseAdapter)
```

fix #1675 RealmChangeListener are strong reference now. 

---

changelog.txt
realm/realm-library/src/main/java/io/realm/RealmQuery.java

RealmQuery.minimum{Int,Float,Double}
RealmQuery.maximum{Int,Float,Double}
RealmQuery.sum{Int,Float,Double}
RealmQuery.average{Int,Float,Double}
Those have been deprecated for months.

Remove deprecated methods from RealmQuery

---

changelog.txt
realm/realm-library/src/androidTest/java/io/realm/MediatorTest.java
realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTest.java
realm/realm-library/src/main/java/io/realm/RealmConfiguration.java
realm/realm-library/src/main/java/io/realm/internal/modules/CompositeMediator.java
realm/realm-library/src/main/java/io/realm/internal/modules/FilterableMediator.java

* Removed `RealmConfiguration.getSchemaMediator()` which was left public by mistake
* Added `RealmConfiguration.getRealmClasses()` which returns the unmodifiable set of model classes that belong to the configuration.
I refactored for all implementations of `RealmProxyMediator.getModelClassed()` to return unmodifiable `Set`.
please review this @realm/java 
closes #1797

Deprecate RealmConfiguration.getSchemaMediator() from public API and add getRealmObjectClasses() instead

---

changelog.txt
realm/realm-library/src/androidTest/java/io/realm/RealmTest.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/Realm.java

Core will guarantee the file is not opened while compacting.
Core also guarantee opening Realm will be blocked until compacting
finished.

compact returns false if the file is opened

---

realm/realm-library/src/androidTest/java/io/realm/NotificationsTest.java
realm/realm-library/src/main/java/io/realm/HandlerController.java

Fixes #1875 
We didn't remove listeners correctly in `addChangeListenerAsWeakReference` compared to `notifyGlobalListeners`. 
No changelog needed as this hasn't been released yet.
@realm/java

Fixed weak change listeners being removed correctly

---

changelog.txt
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTest.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java

fixed a bug where RealmQuery.findFirst() returned a wrong result if that RealmQuery had been created from RealmResults.
review this please @realm/java 
closes #1905

fixed a bug in RealmQuery.findFirst()

---

changelog.txt
realm/realm-jni/src/io_realm_internal_tableview.cpp

Call TableView::clear() and TableView::remove() with RemoveMode::unordered.
This change requires a new core release as unordered removal is broken without realm/realm-core#1384.
So this PR should be merged after #1913
I'll merge this since review has been done in #1915

Call TableView::clear() with RemoveMode::unordered

---

CONTRIBUTING.md

Fixes https://github.com/realm/realm-java-private/issues/26
We currently use the in-build formatting in Android Studio as tool-support.
@realm/java

Add Javadoc requirements to CONTRIBUTING.md

---

examples/kotlinExample/build.gradle

Some people have been reporting problems with the Kotlin example and I experienced it myself yesterday when testing our distribution package. The error doesn't always happen though, so I am a bit perplexed.
In any case. Adding this line to `build.gradle` prevents it from happening.

Fix Kotlin example

---

realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java

add unit test to make sure this bug is fixed when we start using the new Core
fixes https://github.com/realm/realm-java/issues/1676

fixes #1717 

---

README.md

Since we use the latest NDK now, we use Homebrew instead of Homebrew-versions.

Use Homebrew instead of Homebrew-versions.

---

examples/gradle/wrapper/gradle-wrapper.properties
gradle-plugin/gradle/wrapper/gradle-wrapper.properties
gradle/wrapper/gradle-wrapper.properties
realm/build.gradle
realm/gradle/wrapper/gradle-wrapper.properties
realm/realm-library/build.gradle

Changing `-bin` to `-all` for all Gradle wrappers to avoid those annoying Android Studio popups. Also provides sources + doc at the expense of a little extra disc space.
Bumped Gradle to latest version, 2.10. That required bumping Android Build Tools to 1.5.0 in the process. I didn't want to promote my bleeding edge tendencies by bumping to "2.0.0-alpha3" (although it seems stable enough from what I can tell).
@realm/java

Upgraded Gradle to latest version

---

realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/RealmObject.java
realm/realm-library/src/main/java/io/realm/RealmResults.java

Based on external feedback this updates the `asObservable()` Javadoc to be more specific about it's behavior.
@realm/java

Update Javadoc for Rx Observables to be more specific.

---

changelog.txt
realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTest.java
realm/realm-library/src/main/java/io/realm/HandlerController.java

* It should be legal to modify realmObjects map in listener.
* It should be legal to modify syncRealmResults/asyncRealmResults map
in listener.
Fix #1970

Fix ConcurrentModificationException in listeners

---

changelog.txt
realm/realm-library/src/androidTest/java/io/realm/RealmListTest.java
realm/realm-library/src/main/java/io/realm/RealmList.java

Fixes #2044 
Also migrated RealmList unit tests to Junit4.
@realm/java

RealmList.set() now correctly returns the old item.

---

realm/realm-library/build.gradle

Code coverage finally seems to be working for Android library projects running instrumentation tests.
This PR enables creating a Jacoco code coverage report for `realm-library` as part of running the unit tests.
```
cd realm
./gradlew createDebugCoverageReport
``` 
will run the unit tests and create a coverage report in `/realm/realm-library/build/reports/coverage/debug`
@realm/java

Enable code coverage for realm-library

---

realm/realm-library/src/androidTest/java/io/realm/RealmTest.java
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java
realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java

* Add JUnit rule TemporaryRealmFolder which helps to create test Realm
file in the temp folder.
* Deprecate similar functions in TestHelper.
* Adapt changes to RealmTest.
I will adapt this to other test cases later.

Isolate test Realm files

---

realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java

Only throw the exception caused by deleting the opened Realm if the test
case itself doesn't throw. Otherwise the test case cannot fail by the
original exception.

Not throw always in TestRealmConfigurationFactory

---

changelog.txt
realm/realm-library/src/androidTest/java/io/realm/RealmTest.java
realm/realm-library/src/main/java/io/realm/Realm.java

Fixes #2058
It should not be possible to call `Realm.copyFromRealm()` with DynamicRealmObject. Right now it crashes with a weird schema exception "cannot find RealmObject".
@realm/java

IllegalArgumentException when calling copyFromRealm(dynamicRealmObject)

---

changelog.txt
realm/realm-jni/src/io_realm_internal_LinkView.cpp
realm/realm-jni/src/io_realm_internal_LinkView.h
realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmListTest.java
realm/realm-library/src/androidTest/java/io/realm/RealmTest.java
realm/realm-library/src/androidTest/java/io/realm/entities/Cat.java
realm/realm-library/src/androidTest/java/io/realm/entities/Dog.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/RealmList.java
realm/realm-library/src/main/java/io/realm/internal/LinkView.java

* Add LinkView.removeAllTargetRows.
* Add Realm.removeAll.
* Add Realm.remove(RealmObject).
* Add Realm.remove(Iterable<RealmObeject>).
* Javadoc & test case update.
Close #1560

Add RealmList.removeAllFromRealm and Realm.clear

---

realm/realm-library/src/androidTest/java/io/realm/RealmTest.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/Realm.java

* Background realm needs to be closed before notifying other threads
in async transaction.
* Latch needs to be called after Realm closed.

Fix flaky tests related with async transaction

---

changelog.txt
realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTest.java
realm/realm-library/src/androidTest/java/io/realm/RealmListTest.java
realm/realm-library/src/androidTest/java/io/realm/entities/Dog.java
realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java

RealmLists containing DynamicRealmObjects wrongly sat the type for them as the parent objects types instead of the linkview type. This caused segmentation faults if the wrong fields was accessed as the underlying type didn't match the getter used.
@realm/java

RealmList not returning DynamicRealmObjects of the proper type

---

realm/realm-library/src/androidTest/java/io/realm/TestHelper.java
realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java

This PR fixes the `RunInLooperThread` rule so e.g. test timeouts are not shadowed by cleanup methods failing, which makes debugging very hard. After this the chance of failure is lower, and if it happens both test errors + errors from the `after()` method is reported.
@realm/java

Improve error reporting from failed unit tests.

---

realm/realm-jni/src/io_realm_internal_Util.cpp
realm/realm-jni/src/io_realm_internal_tableview.cpp
realm/realm-jni/src/util.cpp
realm/realm-jni/src/util.hpp
realm/realm-library/src/androidTest/java/io/realm/RealmResultsTest.java
realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTest.java
realm/realm-library/src/androidTest/java/io/realm/entities/Dog.java
realm/realm-library/src/main/java/io/realm/RealmResults.java
realm/realm-library/src/main/java/io/realm/internal/DeletedRealmListException.java
realm/realm-library/src/main/java/io/realm/internal/Util.java

* When the original RealmList is deleted, for most methods of
RealmResults should just work without crash by just treat it like an
empty RealmResults.
* RealmResults.where() throws IllegalStateExecption in this case.
* RealmResults.isValid() return false in this case.
This is a temp fix, check https://github.com/realm/realm-core/pull/1434
for more details.
Close #1945

Access to RealmResults based on deleted RealmList

---

realm/realm-jni/build.gradle
realm/realm-jni/project.mk

Using a locally build core, it is possible to single step into C++. You will have to add the following two lines to `realm.properties`:
debugBuild=true
stripSymbols=false
@cmelchior @emanuelez @beeender

Removing LTO from debugging builds

---

realm/realm-library/src/androidTest/java/io/realm/NotificationsTest.java
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java

Converted NotificationTests to use TestRealmConfigurationFactory so one unit test failure doesn't cause all the other tests to fail as well.
@realm/java

NotificationTests converted to use TestRealmConfigurationFactory

---

realm/realm-jni/src/io_realm_internal_table.cpp
realm/realm-jni/src/util.cpp
realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java

`StringData.data()` does not guarantee the null termination of returned char array.
We must use `size()` information to properly handle the char array in the StringData like `std::string(str.data(), str.size())`.
Added test case does not fail on my local machine even if this fix was not applied since the next byte of char array happens to be null character.

Fix wrong usages of StringData.data().

---

changelog.txt
realm/realm-library/src/androidTest/java/io/realm/RealmSchemaTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/AllJavaTypes.java

Fixes #1829 + re-enables the previously failing unit test (which is now fixed by the new core)
This was actually fixed in 0.87.3, so this PR adds the changelog to that version.
@realm/java

Convert RealmSchemaTests to JUnit4 + reenable fixed unit test.

---

README.md
build.gradle
realm/realm-jni/build.gradle

`./gradlew clean -PdontCleanJniFiles` removes all generated files except for JNI related files.
@realm/java

add dontCleanJniFiles option to clean task

---

realm/realm-library/src/androidTest/java/io/realm/RealmTests.java

Minor issue, but it could blocking Realm reading which is not what we expected.
This is the test case only, the problem has been fixed when we introduce
the schema caches.
Since we are caching the schemas for typed Realm, when a transaction
lock is holding by one type Realm, open Realm instance in another thread
should not be blocked.
But if there is no typed Realm instance opened, DynamicRealm transaction
should block the typed Realm openning.

Transaction should not block opening Realm

---

changelog.txt
realm/realm-jni/src/util.cpp
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java

As suggested in #1756, `IllegalArgumentException` is better than `RealmError` when trying to store an invalid string.
@realm/java @remeissner

String setters will throw IllegalArgumentException

---

changelog.txt
realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java
realm/realm-library/src/main/java/io/realm/RealmResults.java

`RealmResults` gets `distinct()` results from its backing `TableView`.
fixes a bug introduced in #2107

RealmQuery 'distinct()' TableView Patch

---

realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java
realm/realm-library/src/main/java/io/realm/RealmObject.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java
realm/realm-library/src/main/java/io/realm/internal/Row.java

Notify listeners of async RealmObject even if the result is empty

---

examples/kotlinExample/build.gradle

We should migrate to realm gradle plugin. I'll do that after merging of better objects PR since that PR includes changes for Kotlin.

Update Kotlin used in example to 1.0-RC

---

CHANGELOG.md
realm/realm-library/build.gradle
realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java
realm/realm-library/src/main/java/io/realm/RealmList.java
realm/realm-library/src/main/java/io/realm/RealmResults.java

now RealmResults.size() honors the contract of the Collection interface

---

README.md
realm/realm-jni/build.gradle

This enables us to keep archive files when executing 'git clean -xfd'.
usage: add following line to your ~/.profile
```
export REALM_CORE_DOWNLOAD_DIR=~/.realmCore
```
@realm/java

add environment variable to specify the location of core's archive files.

---

realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java
realm/realm-library/src/androidTest/java/io/realm/proxy/HandlerProxy.java
realm/realm-library/src/androidTest/java/io/realm/util/ExceptionHolder.java
realm/realm-library/src/androidTest/java/io/realm/util/LooperSpy.java
realm/realm-library/src/androidTest/java/io/realm/util/RealmBackgroundTask.java

Moved all RealmAsyncQueryTests to use RunTestInLooperThread, which massively simplified them + prepared them for https://github.com/realm/realm-java/pull/2233 (which was the main driver for this)
Also improved HandlerProxy so it can now intercept both sending and receiving messages.
I  added 3 new util classes:
- LooperSpy: For dumping the MessageQueue in a debug situation
- RealmBackgroundTask: Wrapper around executing a small task on a background thread. Automatically handles error propagating and closing of Realm
- ExceptionHolder: Can be used to avoid `Exception[]` like code if you only want to test for 1 exception.

Simplify ReamAsyncQueryTests + added new test util classes

---

CHANGELOG.md
examples/adapterExample/src/main/java/io/realm/examples/realmadapters/AdapterExampleActivity.java
examples/adapterExample/src/main/java/io/realm/examples/realmadapters/WorkerThread.java
examples/introExample/src/main/java/io/realm/examples/intro/IntroExampleActivity.java
examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/KotlinExampleActivity.kt
examples/threadExample/src/main/java/io/realm/examples/threads/ThreadFragment.java
examples/unitTestExample/src/main/java/io/realm/examples/unittesting/ExampleActivity.java
examples/unitTestExample/src/test/java/io/realm/examples/unittesting/ExampleActivityTest.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/exceptions/RealmMigrationNeededException.java

* Deprecate Realm.getInstance(Context).
* Replease `Realm.getInstance(Context)` in examples.
See #2303 , `UnitTestExample` doesn't work even before.
Realm doc needs to be updated as well.

Deprecate Realm.getInstance(Context)

---

CHANGELOG.md
realm/realm-library/src/main/AndroidManifest.xml

References: #2227
The consequence of this is that the developer will have ignore the lint warning in their project because we are not setting it. This can be accomplished by adding a `lint.xml` file to the application with the following contents: 
```
<?xml version="1.0" encoding="UTF-8"?>
<lint>
<issue id="AllowBackup" severity="ignore" />
</lint>
```
Then, in the applications build.gradle add the following lint config in the android block.
```
lintOptions {
lintConfig file('lint.xml')
}
```
At that point, when `./gradlew lint` is run, the `AllowBackup` warning will be ignored.

Removing allow back up

---

CHANGELOG.md
realm/realm-jni/src/io_realm_internal_TableView.h
realm/realm-jni/src/io_realm_internal_tableview.cpp
realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java
realm/realm-library/src/androidTest/java/io/realm/entities/AllJavaTypes.java
realm/realm-library/src/androidTest/java/io/realm/entities/AllTypes.java
realm/realm-library/src/androidTest/java/io/realm/entities/AnnotationIndexTypes.java
realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java
realm/realm-library/src/main/java/io/realm/RealmResults.java
realm/realm-library/src/main/java/io/realm/internal/TableView.java

Support multi-arguments `distinct(...)` for Realm, DynamicRealm, RealmQuery, and RealmResults.
Supports for issue #1568

Support multi-arguments distinct() for Realm, DynamicRealm, RealmQuery, and RealmResults

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/RealmConfiguration.java

`RealmConfiguration.getSchemaMediator()` was deprecated in `0.86.0`.
@realm/java

remove RealmConfiguration.getSchemaMediator() from public API

---

CHANGELOG.md

`<B>` of `RealmList<B>` broke markdown formatting. Fix it.

Improve formatting of CHANGELOG.md

---

realm-transformer/src/main/groovy/io/realm/transformer/BytecodeModifier.groovy
realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy
realm/realm-library/src/androidTest/java/io/realm/MediatorTest.java
realm/realm-library/src/main/java/io/realm/RealmConfiguration.java
realm/realm-library/src/main/java/io/realm/internal/RealmProxyMediator.java
realm/realm-library/src/main/java/io/realm/internal/modules/CompositeMediator.java
realm/realm-library/src/main/java/io/realm/internal/modules/FilterableMediator.java

This commit adds default implementation of `transformerApplied()` to `RealmProxyMediator` class which returns `false`.
And then Realm transformer adds overriding methods to its subclasses and those methods returns `true`.
If Realm transformer was applied, `RealmProxyMediator.transformerApplied()` returns `true` and
if not, `RealmProxyMediator.transformerApplied()` returns `false`.
That enable us to detect Realm transformer was applied or not at runtime.
review this please @realm/java @emanuelez

Add a check whether transformer was applied or not.

---

realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java
realm/realm-library/src/main/java/io/realm/RealmConfiguration.java
realm/realm-library/src/main/java/io/realm/RealmObject.java
realm/realm-library/src/main/java/io/realm/RealmResults.java
realm/realm-library/src/main/java/io/realm/rx/RealmObservableFactory.java

Close #1990.
* Check RxJava existence only once.
* Don't load RealmObservableFactory if RxJava doesn't exist.
* Correct exceptions in the java doc.
NOTE: When reflection called on the RealmObject/RealmResults, crash will
still happen because of Observable doesn't exist in the class path. In
such a case, a dummy rx.Observable is still needed as a workaround.

Only load RealmObservableFactory when RxJava exist

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RxJavaTests.java
realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java
realm/realm-library/src/main/java/io/realm/rx/RealmObservableFactory.java

Fixes #2357 
Due to how RxJava executes the chain of Observables, currently it isn't possible to use `doOnUnsubscribe()` to close Realm instances as the side-effect is triggered before the Observable is truly unsubscribed to (crashing our 'removeChangeListeners() method).
This PR changes the current implementation so each Observable also holds onto a Realm instance prevent the Realm from being fully closed until the Observable is unsubscribed to. This means we can now guarantee that the Realm is alive for as long as the Observable is subscribed to. The only downside is that you risk leaking Realm instances if you forget to unsubscribe, but that would be a memory leak in any case.
@realm/java 
/cc @lucamtudor

Realm Observables now holds a Realm instance reference

---

gradle-plugin/build.gradle
gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy
realm-transformer/build.gradle

We don't need to have runtime dependency to  `com.android.tools.build:transform-api` since android gradle plugin has that dependency.
Removing this explicit dependency from `realm-transformer` solves the compatibility issue against android gradle plugin 2.0.0-beta.
This fixes #2348

removed runtime dependency from 'realm-transformer' to 'com.android.tools.build:transform-api:1.5.0'.

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/RealmList.java

0.88 will be released before the RealmCollection API is done with review. Since we are adding two new methods in 0.88 (`Realm.clear()` and `RealmList.removeAllFromRealm()` ) and these are not compatible with the refactoring done by the RealmCollection API. This PR changes these methods so they don't need to be deprecated right after they are released.
It means that API gets slightly confusing since we will have `Realm.clear(Class)` and `Realm.deleteAll()`, at least until the next release. I think that is acceptable.
@realm/java

Rename clear and removeAllFromRealm

---

realm/realm-jni/src/io_realm_internal_LinkView.cpp
realm/realm-jni/src/io_realm_internal_LinkView.h
realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/Owner.java
realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java
realm/realm-library/src/main/java/io/realm/RealmList.java
realm/realm-library/src/main/java/io/realm/RealmSchema.java
realm/realm-library/src/main/java/io/realm/internal/CheckedRow.java
realm/realm-library/src/main/java/io/realm/internal/LinkView.java
realm/realm-library/src/main/java/io/realm/internal/UncheckedRow.java

Fix #2381
* New method LinkView.getTargetTable().
* Proper checking to add DynamicRealmObject to RealmList.
* Disallow modifying with RealmObject belongs to another Realm instance.

More checkings when modify RealmList

---

CHANGELOG.md
realm/realm-jni/build.gradle
realm/realm-jni/src/io_realm_internal_SharedGroup.cpp
realm/realm-jni/src/io_realm_internal_SharedGroup.h
realm/realm-jni/src/io_realm_internal_TableQuery.cpp
realm/realm-jni/src/io_realm_internal_TableQuery.h
realm/realm-jni/src/util.hpp
realm/realm-library/src/main/java/io/realm/internal/SharedGroup.java
realm/realm-library/src/main/java/io/realm/internal/SharedGroupManager.java
realm/realm-library/src/main/java/io/realm/internal/TableQuery.java
realm/realm-library/src/main/java/io/realm/internal/async/QueryUpdateTask.java

Upgrading to Realm Core 0.97.0

---

.github/ISSUE_TEMPLATE.md

In the current template the headers are to large and contains to much description which makes it hard to easily get an overview of new issues.
This PR makes the headers smaller and move the description text out of the header itself
@bmunkholm 
@realm/java

Minimise headers and visual noise in ISSUE_TEMPLATE

---

CHANGELOG.md
realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy

getAnnotations will return all Annotation classes, if the class doesn't
exist in the transformer project, exception will be thrown.
Fix #2413

Useless line triggers bugs

---

CHANGELOG.md
gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy
realm/config/findbugs/findbugs-filter.xml
realm/realm-library/build.gradle
realm/realm-library/src/main/java/io/realm/internal/RealmCore.java
realm/realm-library/src/main/java/io/realm/internal/android/ReLinker.java

The problem is that libraries that use Realm were forced to tell users to add the jitpack repo manually, which is inconvenient.
Fixes #2415

Use a local copy of ReLinker

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java
realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java

* Add RealmObjectSchema.isPrimaryKey(). RealmObjectSchema.getPrimaryKey()
is not added since it doesn't seem to be necessary.
* isNullable & isRequired didn't throw which is wrong.
* Add throws doc to hasIndex.
Close #2440

isPrimaryKey on RealmObjectSchema

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/internal/CheckedRow.java
realm/realm-library/src/main/java/io/realm/internal/Context.java
realm/realm-library/src/main/java/io/realm/internal/LinkView.java
realm/realm-library/src/main/java/io/realm/internal/NativeObjectReference.java
realm/realm-library/src/main/java/io/realm/internal/UncheckedRow.java

Problems we had by using hashmap:
1. Hashmap is not thread safe and we access the same hashmap in
finalizer thread and caller thread of Row's constructor.
2. Removing reference from the hashmap is a little bit slower when
there are many references waited to be GCed.
Refactor the NativeObjectReference, make it as a final class and calling
native resource's deallocation directly inside the class. This is needed
for further optimization, like batch delete native pointers to avoid
multiple JNI calls.
* On Genymotion Nexus 6 5.1.0 this improves around 50%
* On Huawei Honor 7 Android M this only improves **-2**% - 9%
* On ARMv7 4.1.2 this improves around 30%
Some benchmark comparison using the array solution vs hashmap solution:
(Benchmark running on Genymotion Nexus 6 5.1.0)
```
(hashmap) …
```

Finalizer optimization: Replace hashmap

---

realm/realm-library/src/androidTest/assets/all_types_invalid.json
realm/realm-library/src/androidTest/java/io/realm/RealmJsonTests.java
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java

* createAllFromJson(Class<E>, String)
* createObjectFromJson(Class<E>, InputStream)
* createOrUpdateObjectFromJson(Class<E>, InputStream)
* createOrUpdateObjectFromJson(Class<E>, JSONObject)
* createOrUpdateObjectFromJson(Class<E>, String)
In progress, I've rearranged some methods. Without rearrangements, I cannot figure out what methods are not covered.

Increase code coverage createXXXFromJson methods in RealmJsonTests.

---

README.md
build.gradle
realm/realm-jni/build.gradle

example(only build jni files for arm64 and x86_64):
```
./gradlew assemble -PbuildTargetABIs=arm64,x86_64
```
example(build jni files for connected device and execute connectedCheck):
```
./gradlew connectedCheck -PbuildTargetABIs=$(adb shell getprop ro.product.cpu.abi)
```
@realm/java

introduce `buildTargetABIs` property to realm-jni project in order to allow to build only specified ABI(s)

---

CHANGELOG.md
examples/moduleExample/app/src/main/java/io/realm/examples/appmodules/ModulesExampleActivity.java
examples/moduleExample/library/src/main/java/io/realm/examples/librarymodules/Zoo.java
realm-annotations/src/main/java/io/realm/annotations/RealmModule.java
realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmConfiguration.java

Part of #1594. Merge all together in one release.
@realm/java 
Final commit message:
------
Title: Replace setModules() with modules()
This PR deprecates RealmConfiguration.setModules() in favour of RealmConfiguration.modules(). The reason being using the setter terminology is not common in builders. See Effective Java item 2.

Use RealmConfig.modules() instead of RealmConfig.setModules()

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java
realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java

Resolves #2636: this PR adds a `getPrimaryKey()` method to `RealmObjectSchema`.
`getPrimaryKey()` returns the name of the primary key field if the model has a primary key, or throws an `IllegalStateException` if the model doesn't have a primary key field (using the same message that `removePrimaryKey()` uses in such a situation).
I've also modified/added tests in `RealmObjectSchemaTests.java` in order to attain 100% coverage for `getPrimaryKey()`.
I'm new to GitHub pull requests, so if I've done something wrong here please don't hesitate to tell me!

Add getPrimaryKey() method to RealmObjectSchema

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-library/src/androidTest/java/io/realm/RealmNullPrimaryKeyTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmPrimaryKeyTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/PrimaryKeyRequiredAsBoxedByte.java
realm/realm-library/src/androidTest/java/io/realm/entities/PrimaryKeyRequiredAsBoxedInteger.java
realm/realm-library/src/androidTest/java/io/realm/entities/PrimaryKeyRequiredAsBoxedLong.java
realm/realm-library/src/androidTest/java/io/realm/entities/PrimaryKeyRequiredAsBoxedShort.java
realm/realm-library/src/androidTest/java/io/realm/entities/PrimaryKeyRequiredAsString.java

When `@PrimaryKey` and `@Required` annotations are applied together on `String` type field, inappropriate type cast is generated to cause compilation fail. This PR addresses the issue.
All the review points in #2644 are now addressed. 
@realm/java please review.
<hr/>
Final Commit Message : 
Title : A combination of @PrimaryKey and @Required annotation now generates appropriate type cast when a primary key field type is `String`.
When `RealmProxyClassGenerator.emitCopyOrUpdateMethod()` is generating code for checking `@PrimaryKey` value for not-nullable types (i.e. primitive types  or marked with `@Required`), it now generates appropriate type casts according to the field types.

@PrimaryKey + @Required annotation generates inappropriate type cast

---

realm/realm-annotations-processor/build.gradle

All projects other than `realm-annotations-processor` is using JUnit 4.12.

Update JUnit version used in realm-annotations-processor to 4.12

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmSchemaTests.java
realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/RealmSchema.java

* RealmSchema.remove() should remove the field from PK table.
* RealmSchema.rename() should change the corresponding row in the PK
table.
Fix #2555

Handle PK when calling RealmSchema's remove/rename

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/RealmAsyncTask.java
realm/realm-library/src/main/java/io/realm/RealmCache.java
realm/realm-library/src/main/java/io/realm/RealmConfiguration.java
realm/realm-library/src/main/java/io/realm/RealmObject.java
realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java
realm/realm-library/src/main/java/io/realm/exceptions/RealmError.java
realm/realm-library/src/main/java/io/realm/exceptions/RealmException.java
realm/realm-library/src/main/java/io/realm/exceptions/RealmIOException.java
realm/realm-library/src/main/java/io/realm/exceptions/RealmMigrationNeededException.java
realm/realm-library/src/main/java/io/realm/exceptions/RealmPrimaryKeyConstraintException.java

Part of #1594. Merge all together in one release.
@realm/java
Final commit note:
-----
Title: Make all methods on RealmObject and all classes in public API final
We should mark all methods that should not be overridden final.
We should mark all classes that should not be inherited final.

Make all methods on RealmObject and all classes in public API final

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/RealmAsyncTask.java

Part of #1594. Merge all together in one release.
@realm/java
Final commit note:
----
Title: mark constructor of RealmAsyncTask package protected
Removed constructor from the public API as the method is not useful for public use and we want to keep the public API as clean as possible

mark constructor of RealmAsyncTask package protected

---

examples/moduleExample/app/build.gradle

ProGuard example should have `proguardFiles` configuration which enables
app to have application specific configurations for ProGurad since
real app needs to have configuration for it's library in most cases.
@realm/java

add proguardFiles configuration to modulesExample/app project

---

CHANGELOG.md

related to #2680 
plus, this PR includes back-port of #2656 (Add bullet to changelog about new sorting behaviour on collections.)

Add bullet to changelog about behavior change of RealmList.first() and RealmList.last()

---

CHANGELOG.md
gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy

Apparently just having "apt" is not enough if you have a library project with unit tests that uses Realm.
Explicitly adding the annotation processor to `androidTestApt` fixes that.
I am guessing we also need to do the same for JVM tests with `testApt`, but since we don't support that yet. I didn't do that in this PR.
@realm/java

APT is now correctly applied for unit tests in library projects.

---

realm-transformer/src/main/java/io/realm/transformer/ComputerIdentifierGenerator.java

The solution relying on the BIOS turned out to be not too solid.

Use the motherboard identifier instead of the BIOS one for Windows machines

---

realm/realm-library/src/main/java/io/realm/BaseRealm.java

`BaseRealm.stopWaitForChange()` exception description in Javadoc.
@realm/java

StopWaitForChange exception in Javadoc

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java
realm/realm-library/src/main/java/io/realm/RealmCache.java

People not overriding `equals` in their custom Migration class is a common source of errors if people are creating multiple RealmConfiguration instances (which they shouldn't in the first place), but at least this gives better hints to what is wrong.
@realm/java

Better exception message when using custom migrations

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/HandlerController.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmObject.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java

* Only add the RealmObject to HandlerController.realmObjects when
addChangeListener called. This will avoid we have too many objects in
the map.
* addToRealmObjects missed reference queue which would lead to the map
grows always without cleaning.
Close #2569, potentially a fix to #2686 .

Add to realmObjects when addChangeListener called

---

realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/HandlerController.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmAsyncTask.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java

asyncQueryExecutor and pendingQuery seem to be very confusing since they
are used for async transaction as well.

Give async related vars better names

---

realm/realm-library/src/main/java/io/realm/RealmObject.java

Title : A note on the behavior of RealmObject.isValid() 
When an invalid `RealmObject` is subscribed, no proper notification will be triggered for `rx.Observer`.
This PR addresses the issue #2158. 
@realm/java

A note on the behavior of RealmObject.isValid() added

---

realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/RealmObject.java
realm/realm-library/src/main/java/io/realm/RealmResults.java

It is recommended to use Realm.where().find*Async() instead of SubscribedOn() to avoid Realm being accessed from different threads.
This PR addresses issue #2607.
@realm/java

Javadoc for using Realm with SubscribedOn() 

---

CHANGELOG.md
gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy
realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy

==== Final commit message === 
Close #2703
While javassit manipulating the method, it requires all of the classed
used in the method can be found in the class pool. But android.jar will
not be passed to the transform -- It is not in any of
QualifiedContent.Scope definitions.
We use project.android.bootClasspath which is public right now to get
the path to android.jar. Project is passed from gradle.
See https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/gradle/src/main/groovy/com/android/build/gradle/BaseExtension.java#737

Workaround to add android.jar for transform

---

realm/realm-library/src/main/java/io/realm/RealmQuery.java

Javadoc fix addressing the issue #2792, which could arise a confusion as to where one might search with a child `RealmList` or `RealmObject` field.
@realm/java

Javadoc corrections for findAllSorted & findAllSortedAsync

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmObject.java
realm/realm-library/src/main/java/io/realm/RealmResults.java

fixes #2772
`{Realm,DynamicRealm}.{add,remove}ChangeListener()` accept `null` as a listener.
And then Crash will happen when it is called.
I added `null` check to those methods(corresponding methods in `RealmObject` and `RealmResults` already check `null`).

add a null check to addChangeListener and removeChangeListener

---

CHANGELOG.md
CONTRIBUTING.md
examples/rxJavaExample/src/main/java/io/realm/examples/rxjava/gotchas/GotchasActivity.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
realm/realm-library/src/androidTest/java/io/realm/CollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/ManagedRealmCollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/OrderedRealmCollectionIteratorTests.java
realm/realm-library/src/androidTest/java/io/realm/OrderedRealmCollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmModelTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java
realm/realm-library/src/main/java/io/realm/OrderedRealmCollection.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmList.java
realm/realm-library/src/main/java/io/realm/RealmObject.java
realm/realm-library/src/main/java/io/realm/RealmResults.java
realm/realm-library/src/main/java/io/realm/internal/RealmProxyMediator.java

Fixes #2789 
This PR changes the terminology on the Java side so object not in Realm are called "unmanaged" everywhere:
- Changlog
- Unit tests
- variables
- Javadoc / comments / exception messages
The following terms have been converted:
- un-managed
- standalone
- non-managed
- nonmanaged
@realm/java

Objects not in Realm are now called unmananged everywhere.

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java
realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java

`RealmObjectSchema.addPrimaryKey()` is supposed to add a search index to its primary key field but it is currently missing.  This is to fix the addition and removal of a search index related to primary key methods in `RealmObjectSchema`. Closes #2819.
@realm/java please review.

addPrimaryKey() on RealmObjectSchema misses Index addition.

---

build.gradle
realm/realm-jni/build.gradle

And remove some useless lines
Unfortunately crashlytics's symbols uploading is not what we want. It would be useful if user is using ndk and 3rd party libs exist in the `lib` dir. I couldn't make it work.
Having debug so on s3 would be good enough for us right now.
TODO:
**PS. Haven't successfully tested the uploading part since it always fails in my network :(**

Upload native lib with symbols to s3

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java

Remove log files in Realm.deleteRealm

---

CHANGELOG.md
realm/realm-jni/src/io_realm_internal_Table.h
realm/realm-jni/src/io_realm_internal_TableView.h
realm/realm-jni/src/io_realm_internal_table.cpp
realm/realm-jni/src/io_realm_internal_tableview.cpp
realm/realm-library/src/androidTest/java/io/realm/internal/JNITableTest.java
realm/realm-library/src/androidTest/java/io/realm/internal/JNIViewTest.java
realm/realm-library/src/main/java/io/realm/internal/Table.java
realm/realm-library/src/main/java/io/realm/internal/TableOrView.java
realm/realm-library/src/main/java/io/realm/internal/TableView.java

Table::row_to_string Table::to_string are for debugging purpose only, it
calls string::substr which might truncate an UTF-8 string at any char.
Thus a crash could happend in JNI when converting to UTF-16.
This will only happen when user attach a debugger and the debugger is
trying to call Table.toString.
Close #2429

Avoid Table.nativeToString/nativeRowToString

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/RealmResults.java

`RealmResults.isLoaded()` description fix. Closes #2895.
@realm/java

RealmResults.isLoaded description fix

---

realm/realm-library/src/androidTest/java/io/realm/internal/JNITransactions.java
realm/realm-library/src/main/java/io/realm/internal/Table.java

This PR is to enhance `toString()` message for `Table` debugging.

Table.toString() message for debugging Table with PrimaryKey

---

CHANGELOG.md

The missing changelog entry for #2903 is added.
@realm/java

Changelog fix for PR #2903

---

realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java

In `RealmObjectSchema.addModifiers()` there is a redundant `addIndex(fieldName)` called before `addPrimaryKey(fieldName)`. This should have been removed at #2832.

Redundant addIndex(fieldName) removed

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/NotificationsTest.java
realm/realm-library/src/main/java/io/realm/HandlerController.java

Close #2408
RealmResults are synced when calling its listener, since we need to
check the table version before calling the listener. So sync it just
after advance read won't be an option - in that way, the result's
listener won't be triggered.
So we notify the global listeners as the last thing to do, at that
point, result will be synced already.
Also a test case is added to ensure the calling sequence of synced
listeners.

RealmResults is not synced in global listener

---

CHANGELOG.md
realm/realm-library/proguard-rules.pro

related to #2927
This PR adds a ProGuard configuration for native methods.
In normal cases, users include android's default ProGuard configuration and it contains a configuration for native methods.
But including default configuration is not mandatory and users freely write their own configurations from scratch.
To allow such a usage, ProGuard configuration provided by Realm should not depend on default configuration.

update proguard configuration no to depend on Android's default configuration

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java
realm/realm-library/src/main/java/io/realm/RealmConfiguration.java

RealmConfiguration.Builder.assetFile() and deleteRealmIfMigrationNeeded() should not be called at the same time to prevent the provided asset file from deletion in migrations.
Closes  #2933.

Asset file provided in configuration should not be deleted in migrations

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/main/java/io/realm/RealmConfiguration.java

`RealmConfiguration.Build(context, dirPath)` constructor invokes ReLinker which provides protections on broken android installs/updates with custom directory path.
Closes #2900.

Builder takes custom directory path and context

---

realm/realm-library/src/main/java/io/realm/BaseRealm.java

We recently had a number of questions around refreshing and modifying data.
I extended the `beginTransaction` Javadoc to be very explicit about what happens and what the best practise is around this.
@realm/java

Updated beginTransaction doc

---

CHANGELOG.md
realm/config/findbugs/findbugs-filter.xml
realm/realm-jni/src/io_realm_internal_Util.cpp
realm/realm-jni/src/util.cpp
realm/realm-jni/src/util.hpp
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/main/java/io/realm/exceptions/IncompatibleLockFileException.java
realm/realm-library/src/main/java/io/realm/internal/SharedGroup.java
realm/realm-library/src/main/java/io/realm/internal/Util.java

This PR is the result of investigating https://github.com/realm/realm-java/issues/2459
We have anecdotal evidence that multiple processes might be open for the same app. We have not been able to verify this, but the result matches the "IncompatibleLockFile" errors reported in #2459. This happens if the two processes have two versions of Realm (e.g. during app upgrades).
This PR is based on our assumption that such an overlap is not intentional and only happens because one process is started before the previous was completely shut down.
So this PR introduces an optimistic opening scheme where we retry for 1 second before crashing as before.
I also added logging so users can log if they run into this issue.
The settings for this are currently public in SharedGroup, which will allow users to …

Optimistic opening of a Realm file

---

realm/realm-jni/src/io_realm_internal_LinkView.cpp
realm/realm-jni/src/io_realm_internal_Table.cpp
realm/realm-jni/src/io_realm_internal_TableQuery.cpp
realm/realm-jni/src/io_realm_internal_TableView.cpp

`std::move` casts an lvalue to an rvalue. It's redundant to call it with an rvalue as its argument.
/cc @beeender

Remove redundant calls to std::move

---

Jenkinsfile
integration-tests/optionalAPIExists/build.gradle
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/JNIMixedSubtableTest.java

Move from https://github.com/realm/realm-java/pull/3049
If unit tests crashes with native exceptions we currently have no way of knowing why.
With this PR we now save the LogCat file in case there is a test failure. For green builds nothing is saved.
A local test on my phone indicates that a full logcat file is ~8MB in size and 400Kb when zipped.
The CI log seems to be much smaller (~4Mb compressed to 130k) 
An example is here: https://ci.realm.io/job/android-pr-jenkinsfile/630/
We need to enable logging before starting tests as Android only have a 256Kb buffer for log entries and rotates between multiple files. This means that dumping the log afterwards are missing _a lot_ of entries.
@realm/java 
@emanuelez

Save LogCat file in case of test failure

---

Dockerfile
README.md
examples/build.gradle
examples/newsreaderExample/build.gradle
examples/threadExample/build.gradle
examples/unitTestExample/build.gradle
integration-tests/build.gradle
integration-tests/optionalAPIExists/build.gradle
realm/gradle.properties
realm/realm-annotations-processor/build.gradle
realm/realm-library/build.gradle
realm/realm-library/src/androidTest/java/io/realm/ManagedOrderedRealmCollectionTests.java

Update compileSdkVersion and build tools to 24

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/Realm.java

So DynamicRealm can have a warning logged as well.

Move Realm.finalize to BaseRealm

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/HandlerController.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java
realm/realm-library/src/main/java/io/realm/internal/HandlerControllerConstants.java
realm/realm-library/src/main/java/io/realm/internal/async/QueryUpdateTask.java

For example the UnsatisfiedLinkError should cause the process terminated.
This is the reason of all the time out issues we found for CI.

Forward all throwables but not only excpetions - Fix the CI timeout

---

realm/realm-library/src/androidTest/java/io/realm/RealmLinkTests.java

`RealmLinkTest` is the last user of the deprecated `TestHelper.createConfiguration()` method.
I'll clean up `TestHelper.createConfiguration()`s in other PR.
@realm/java

Migrate RealmLinkTests.java to JUnit4 style.

---

Dockerfile
Jenkinsfile

Also, we need to install `hexdump` on our docker images in order to perform the method count.

Don't rely on dir() in docker containers in the Jenkinsfile

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java

This PR changes the Realm annotation processor so it no longer consumes the annotations. The only effect this has is that it is now possible to write multiple annotation processors for the same annotation. 
It is not possible to specify the order of annotation processors from two different libraries, so if one of the processors consumed the annotation it would be random if both ran or only one of them.
I ran into this problem while working on a small side-project that involved creating a new annotation processor that also wanted to generate files based on the Realm model classes. So opening up for this will also allow others to write similar processors.
@realm/java

Annotation processor no longer consume annotations

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java
realm/realm-library/src/androidTest/java/io/realm/NotificationsTest.java
realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java
realm/realm-library/src/androidTest/java/io/realm/rule/RunTestInLooperThread.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/HandlerController.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmObject.java
realm/realm-library/src/main/java/io/realm/RealmResults.java

Fixes #2875 
With this change, using any form of ChangeListener will now throw on an IntentService thread.
IntentService has always been a bastard child in the sense that it is a  Looper thread, but is not meant to be used as such, since the looping is just used to process the queue of jobs.
- All logic around the auto-refresh feature has also been moved to the HandlerController instead of being scattered all over the place.
- `RunTestInLooperThread` have been extended so it is now possible to define the name of the worker thread.

Disable change listeners on IntentService

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java
realm/realm-library/src/main/java/io/realm/internal/Table.java

Fixes #3212 
This PR fixes a bug which happened when using `insert()` with two java instances with the same primary key. This now correctly throws a `RealmPrimaryKeyConstraintBrokenException`.
@realm/java

insert(): Correctly detect multiple objects with the same primary key 

---

realm/realm-jni/src/io_realm_internal_Table.cpp

`Table::get_name()` returns `StringData`. Converting to `string` and back to `StringData` is really stupid. Let's run `git blame` and see how did that!
@realm/java

Do not copy strings too many times.

---

README.md

From time to time we have people that clone the repo to run the examples, and then get support questions on it since you need to assemble everything from the top-level directory first. Latest example: http://stackoverflow.com/questions/38772301/realm-gradle-examples-project-refresh-failed
This isn't entirely intuitive, but a consequence of our need to have multiple independent gradle projects. 
I added a small section to address this.
@realm/java

Add section about examples.

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java
realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java

Closes #3294
DynamicRealmObject typed getters didn't check if the field name being retrieved was the correct type, which caused a seg fault if you called dynamicObj.getString(integerField). A proper IllegalArgumentException is now being throw instead.

DynamicRealmObject typed getters

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmSchema.java

This PR solves following problems.
* There are two `Class to Table` caches. One is in `Realm` class and another is in `RealmSchema` class.`
* The cache never hits against proxy classes.

improve `Table` and schema cache.

---

realm/realm-jni/build.gradle

closes #3284 
The name and the format of the file which contains ndk version information was changed since NDK r11.
This PR accepts new format.
@realm/java

accept new version file (sources.properties) in NDK

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/HandlerController.java

In a rare case, if handleAsyncTransactionCompleted posted before set
handler to null, the handleAsyncTransactionCompleted will be called with
a closed Realm.
It is very difficult to construct a test case for this.

Verify SharedGroup in handleAsyncTransactionCompleted

---

realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java
realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/Realm.java

This is highly related with #1900.
Below things are still guaranteed by this change after commit async
transaction:
* When callback function called (onSuccess/onError), the background
Realm is closed.
* When any change listeners called, the background Realm is closed.
What is true now but it is not guaranteed in the future:
* Background Realm might not be closed before REALM_CHANGED sent (not
received).
Due to this, to avoid the flaky tests, we have to ensure all async tasks
quit peacefully before start the next test. This is implemented by wait
and check in the TestRealmConfigurationFactory.
NOTE: Any test, if the async tasks cannot be finished peacefully in a
certain time, it has to be considered as a problem and fixed.
This would be needed by OS notifications since Java won't have a …

Wait all async tasks done before next test

---

realm/realm-library/src/androidTest/java/io/realm/RealmTests.java

This test is not constructed properly. It tries to modify the lock file
while the Realm is still opened. This would cause some undefined
behaviour in core. Especially when we are using the generic
external_commit_helper which is based on SharedGroup::wait_for_change()
the helper thread will freeze because of polling hangs forever.
Just remove the test, core should ensure the proper exception thrown and
we have other tests to ensure the exception conversion right.

Remove improper incompatibleLockFile test

---

realm/realm-library/build.gradle

* revive the version check of ndk in order not to waste our time by using wrong version of NDK.
* minor fix
* minor fix
* move 'checkNdk(ndkPathInLocalProperties)' to ensure the existance of the directory when obtainig canonical path

revive the version check of ndk (#3354)

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java

Fix a lint error in proxy classes when the 'minSdkVersion' is smaller than 11

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmCacheTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java
realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java
realm/realm-library/src/benchmarks/java/io/realm/benchmarks/config/BenchmarkConfig.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/RealmCache.java
realm/realm-library/src/main/java/io/realm/RealmConfiguration.java

This PR removes previously deprecated constructor + adds a new `directory(File)` option to the RealmConfiguration builder.
This means that we now always have a Context reference, so `assetFile(context, string)` could be simplified to `assetFile(string)` as well.
Most of the changes in this PR is in the unit tests. The interesting code change is in `RealmConfiguration`
@realm/java

Remove deprecated constructor + add directory()

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp
realm/realm-library/src/main/cpp/util.hpp

Add wrapper class for JNI local reference to delete the local ref after
using it.
This is reported by user on helpscout:
https://secure.helpscout.net/conversation/244053233/6163/?folderId=366141
And some useful explanation can be found:
http://stackoverflow.com/questions/24289724/jni-deletelocalref-clarification
Normally the local ref doesn't have to be deleted since they will be
cleaned up when program returns to Java from native code. Using it in a
loop is obvious a corner case: the size of local ref table is relatively
small (512 on Android). To avoid it, the local ref should be deleted
when using it in a loop.

DeleteLocalRef when the ref is created in loop

---

realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java
realm/realm-library/src/androidTest/java/io/realm/CollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/ManagedOrderedRealmCollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/ManagedRealmCollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmAnnotationTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmChangeListenerTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmCollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java

Since Realm.createObject(class) will be deprecated on master for Classes
with primary key defined, fix the test cases which use it first to avoid
more conflicts when merging.

Use createObject(class, primaryKey) in test

---

realm/realm-library/src/main/java/io/realm/RealmConfiguration.java

fix Javadoc documentation about encryption key length (64 bit -> 64 bytes)

---

realm/realm-library/build.gradle

The realm javadoc is served via https so the links should be https too in order to avoid a mixed content blocking:
https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox

Use https in javadoc links

---

realm/realm-library/src/androidTest/java/io/realm/NotificationsTest.java

since it becomes a flaky test after #3370.
And it will be fixed very soon.

Ignore callingOrdersOfListeners for now

---

CHANGELOG.md
realm-annotations/src/main/java/io/realm/annotations/PrimaryKey.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/Constants.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java
realm/realm-library/src/androidTest/java/io/realm/CollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/OrderedRealmCollectionIteratorTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmAnnotationTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmModelTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/AllJavaTypes.java
realm/realm-library/src/androidTest/java/io/realm/entities/PrimaryKeyAsBoxedLong.java
realm/realm-library/src/androidTest/java/io/realm/entities/PrimaryKeyAsByte.java
realm/realm-library/src/androidTest/java/io/realm/entities/PrimaryKeyAsInteger.java
realm/realm-library/src/androidTest/java/io/realm/entities/PrimaryKeyAsLong.java
realm/realm-library/src/androidTest/java/io/realm/entities/PrimaryKeyAsShort.java
realm/realm-library/src/androidTest/java/io/realm/entities/pojo/AllTypesRealmModel.java
realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java

Thrown an exception if changing the pk after the object created.

Disallow changing PK after object created

---

realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/main/java/io/realm/Realm.java

Thread check in `Realm#createObject(Class,Object)` seems to be missing.
@realm/java

added thread check to Realm#createObject(Class,Object)

---

realm/realm-library/build.gradle

generated jni header files must be cleaned when cleaning `.so` files.
@realm/java

add a task to clean jni header files when .so file is cleaned

---

realm/realm-library/src/main/java/io/realm/Realm.java

`createAllFromJson(Class,InputStream)`, `createOrUpdateAllFromJson(Class,InputStream)`, `createObjectFromJson(Class,InputStream)` and `createOrUpdateObjectFromJson(Class,InputStream)` only supports API level 11 or later.
That should be mentioned in API reference. Actually related issue was created multiple times (#3356, #3455 ).
This PR adds a mention to the limitation of those APIs.
fixes #3455

update javadoc comments of JSON APIs in Realm class to mention available API level.

---

realm/realm-library/build.gradle

This PR enables us to specify `buildTargetABIs` property in command-line or in `~/.gradle/gradle.properties` like before and it will be ignored when we execute gradle from AS (AS automatically set appropriate ABI to `android.injected.build.abi`).
@realm/java

resurrect buildTargetABIs property support

---

CHANGELOG.md
realm-transformer/src/main/groovy/io/realm/transformer/BytecodeModifier.groovy
realm-transformer/src/test/groovy/io/realm/transformer/BytecodeModifierTest.groovy

We need to pass `java.lang.String` object instead of `groovy.lang.GString` object to `contains()` since the `contains()` method accepts any type of object thus `groovy.lang.GString` is not converted to `java.lang.String`.
fixes #3469

fix duplicate check of accessors when adding them

---

realm/realm-library/build.gradle

Fixes #3514.
This might solve an issue regarding Bintray not updating the `maven-metadata.xml` file in the Maven repository

Append the version number to the name of all the artifacts uploaded to Bintray

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/internal/ObjectServerFacade.java
realm/realm-library/src/objectServer/AndroidManifest.xml
realm/realm-library/src/objectServer/java/io/realm/ObjectServer.java
realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/SessionStore.java
realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/SyncObjectServerFacade.java
realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/SyncUtil.java

On Android 7 device, android.net.conn.CONNECTIVITY_CHANGE is not deliverd to receivers registerd by AndroidManifest.xml.
See https://developer.android.com/topic/performance/background-optimization.html#connectivity-action
fixes #3511

use Context.registerReceiver() instead of AndroidManifest.xml to register NetworkStateReceiver for android.net.conn.CONNECTIVITY_CHANGE broadcast

---

realm/realm-library/build.gradle

Credit to @zaki50 to add this fix.
After a gradle clean `realm/realm-library/src/main/jniLibs` was not cleared causing the packager to use old generated _.so_  in the AAR instead of the freshly compiled inside `externalNativeBuild` ex `./realm/realm-library/.externalNativeBuild/cmake/objectServerDebug/obj/x86/librealm-jni.so`
without this fix it might include old _.so_ not containing the sync symbols.

Clean .so files that were created by old build script

---

CHANGELOG.md
gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy
gradle-plugin/src/main/groovy/io/realm/gradle/RealmPluginExtension.groovy

fixes #3501
This PR changes the way to add the dependencies.
`DependencyResolutionListener` was removed and the setter of `syncEnabled` property in `RealmPluginExtension` modifies `compile` dependencies instead.
This worked as expected with the project provided in https://github.com/realm/realm-java/issues/3501#issuecomment-250413228
@realm/java @emanuelez

fixed a bug causing ConcurrentModificationException on some Gradle 3.1 environment

---

realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java
realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java

fixes #3404 
DynamicRealmObject should not have `UncheckedRow` instance as a `row`. This PR fix that issue.
And this also removes a check of the `row` instance if it is an instance of `UncheckedRow` in some constructors of DynamicRealmObject since CheckedRow is never passed to it.

Always use CheckedRow when creating DynamicRealmObject

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp

distinctAsync now respects other query parameters.

---

CHANGELOG.md
gradle-plugin/src/main/groovy/io/realm/gradle/RealmPluginExtension.groovy

This PR stops using `removeIf` in gradle plugin.
That method is available only on Java 8 or later.
fixes #3563
@realm/java

fix build error on Java 7 environment

---

realm/realm-library/src/androidTestObjectServer/java/io/realm/android/UserStoreTest.java

Life is to short for restarting CI all the time. Disabling this for now until we can figure out what is wrong with it.
/cc @nhachicha

Disable flaky test

---

realm/realm-library/build.gradle
realm/realm-library/src/main/cpp/CMakeLists.txt

See https://github.com/beeender/lcache for source code for lcache.
It is very simple right now. It identify if the link target is cached by
using checksums from command line + checksums of all input files.
The realm-library gradle check those paths from project properties first
, then the system env.
So those can be set in the ~/.gradle/gradle.properties like:
ccachePath=/usr/bin/ccache
lcachePath=/usr/bin/lcache
Or by system ENVs like:
NDK_CCACHE=/usr/bin/ccache
NDK_LCACHE=/usr/bin/lcache

[CherryPick] Accelerate build with ccache and lcache (#3523)

---

realm/realm-library/build.gradle

It is set by AS randomly for some reasons, seems AS will inject ABIs
according to execution target. But it is not having the right ABI values
all the time. So just disable it, only check buildTargetABIs property.

Ignore android.injected.build.abi

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/java/io/realm/UserTests.java
realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/UserFactory.java

Fixes #3638  
Also fixed some compile errors. Not entirely sure how they where not caught by CI? 
@realm/java 
Also this impact #3639 (/cc @zaki50 )

SyncUser.currentUser is now correctly cleared on logout

---

realm/realm-library/src/androidTest/java/io/realm/RealmTests.java

existing database file may cause `RealmMigrationNeededException`
@realm/java

delete realm file before test

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/rx/RealmObservableFactory.java

Fixes #3672 
Fixes #3552 
This PR fixes a bug that would leak all RealmResults/RealmObject instances on any long lived thread. Kind embarrassing since I looked into this a couple of weeks ago and couldn't find anything, but yay for a good repo case.
There is no unit test since the code in question is private and any test would be non-deterministic. If you think a unit test is required, I can move the helper class to our internal package and unit test it from there. That wouldn't have caught this particular case though as this bug was more about calling code and class not agreeing on the protocol for using the class.
@realm/java

Fix memory leak when unsubscribing from RxJava observables.

---

CHANGELOG.md
realm/realm-library/proguard-rules-common.pro
realm/realm-library/src/main/java/io/realm/internal/KeepMember.java
realm/realm-library/src/main/java/io/realm/log/RealmLogger.java
realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/ObjectServerSession.java

Our ProGuard configuration introduced in `2.1.0` unexpectedly keeps classes those do not have any fields with KeepMember annotation.
fixes #3689

fix a bug that proguard configuration keeps all class names.

---

realm/realm-library/src/main/cpp/CMakeLists.txt

See https://github.com/googlesamples/android-ndk/issues/319

Workaround for jni headers path in AS

---

realm/realm-library/src/main/java/io/realm/BaseRealm.java

Thread pool is not associated with Сontext. It looks like a typo.

Remove excess comment

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java

DefaultRealmModule not created for empty Kotlin projects

---

CHANGELOG.md
examples/introExample/build.gradle
examples/objectServerExample/build.gradle
examples/unitTestExample/build.gradle
gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy

Supported `annotationProcessor` configuration provided by Android Gradle Plugin 2.2.0 or later.
Realm plugin adds its annotation processor to `annotationProcessor` configuration instead of `apt` configuration if `annotationProcessor` configuration is provided and `com.neenbedankt.android-apt` plugin is not applied.
In Kotlin project, `annotationProcessor` configuration is never used for now
The projects that satisfy all following conditions must apply `com.neenbedankt.android-apt` manually (or modify the configurations to `annotationProsessor` or its variants).
* Java project (not Kotlin project).
* Not applying `com.neenbedankt.android-apt` plugin manually.
* Using `apt` or its variants (`*Apt`) configurations.
fixes #3026 
In this PR, Realm gradle plugin chooses a configuration by …

Support annotationProcessor configuration.

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java

In sync mode, `validateTable()` must get all fields in the tabla.
@realm/java

Fixed a bug that caused unexpected MigrationNeededException when a field was added to synced Realm

---

CHANGELOG.md
realm/realm-library/proguard-rules-common.pro
realm/realm-library/src/main/java/io/realm/exceptions/RealmFileException.java
realm/realm-library/src/main/java/io/realm/log/RealmLogger.java

removed includedescriptorclasses option to supprt built-in shrinker of Android Gradle Plugin

---

realm/realm-annotations-processor/build.gradle

When `master` branch is built on CI, `ojoUpload` task in `realm/build.gradle` is executed.
However, that task is defined only in `realm/realm-library/build.gradle`, not in `realm/realm-annotations-processor/build.gradle`.
This PR defines `ojoUpload` task in `realm/realm-annotations-processor/build.gradle` as well.
@realm/java @emanuelez

fix a bug that realm-snnotations-processor is not deployed to ojo

---

realm/realm-library/build.gradle
realm/realm-library/src/main/java/io/realm/internal/RealmCore.java

Set native library version to `ReLinker` in order to prevent to use old native library.
fixes #3775 
@realm/java

Set native library version to ReLinker

---

realm/build.gradle
realm/realm-annotations-processor/build.gradle
realm/realm-library/build.gradle

fix NPE when executing `artifactoryPublish` task in `realm-annotations-processor`.
```
:****:****-annotations-processor:artifactoryPublish FAILED
:ojoRealm FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':****-annotations-processor:artifactoryPublish'.
> java.lang.NullPointerException (no error message)
```
@realm/java @emanuelez

fix artifactoryPublish task in realm-annotations-processor

---

realm/realm-library/build.gradle
realm/realm-library/src/androidTest/AndroidManifest.xml
realm/realm-library/src/androidTest/java/io/realm/RealmJsonAbsentPrimaryKeyTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmJsonTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmModelTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/JNITableViewTest.java
realm/realm-library/src/main/AndroidManifest.xml

This enables for us to reproduce #3804 on our unit test.
@realm/java 
After applying this change, our android test reproduces #3804 on ARM with API 9 device, and #3735 on x86  with API 9 emulator.

Added a support for androidTest on API 9 devices

---

realm/realm-library/src/benchmarks/java/io/realm/benchmarks/RealmObjectWriteBenchmarks.java
realm/realm-library/src/main/cpp/util.cpp

I have noticed that while debugging in Android Studio, strings contain garbage. Java strings can contain `NULL` characters so it can be a simple artefact of that. But in the light of our string issues in the last two years,  it might be worth zeroing the memory before using it.
The impact on performance is evaluated using the microbenchmark (included in the project)  on a Samsung S III mini (I-8190N). Impact is minimal (writeLong is included to evaluate the variance).
| Test | String length | w/o `memset` | with `memset` |
|------|--------------|---------------|-----------------|
| writeLong |N/A | 15.63 μs | 16.09 μs |
| writeLongString | 64 | 23.71 μs | 24.86 μs |
| writeMediumString | 16 | 20.8 μs | 21.55 μs |
| writeShortString | 3 | 20.31 μs | 20.40 μs |

Zeroing memory before using it

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncConfigurationTests.java
realm/realm-library/src/main/java/io/realm/Realm.java

Due to https://github.com/realm/realm-core/issues/2345 we need to disable `Realm.compactRealm()` when the Realm is sync'ed.

Disabling sync/compact combo

---

realm/realm-library/src/androidTest/java/io/realm/RealmInMemoryTest.java

The StrictMode warnings is caused by testInMemoryRealm which try to
detect if there are IOs in the thread when using in-memory Realm.
Well, that test is created by me and it doesn't make any sense to check
with StrictMode.
In memory Realm doesn't mean there will be no disk IOs, it only means
if all the instances are closed, the data will not be persisted on the
disk.
And the StrictMode warning is cause by the last statement
`StrictMode.enableDefault()`. StrictMode is not turned on for testing by
default!
Fix #3141
Also convert the test to JUNIT4.

Fix the warnings of StrictMode

---

realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/util/SyncTestUtils.java
realm/realm-library/src/main/cpp/io_realm_RealmFileUserStore.cpp
realm/realm-library/src/main/cpp/util.cpp
realm/realm-library/src/objectServer/java/io/realm/SyncUser.java

`SyncUser.currentUser` should throw IllegalStateException if multiple users are logged in.
@realm/java

Throw correct exception for multiple logged in users

---

realm/realm-library/src/main/cpp/util.cpp

Add the underlying information on RealmFileException to help investigating incompatible lock file issue.

Add the underlying information on RealmFileException.

---

realm/realm-library/src/androidTest/java/io/realm/TestHelper.java

It is quite annoy when we stop at a breakpoint the awaitOrFail timeout
happens. By checking if the debugger connected, we can know we are
actually debugging the test and don't want to be interrupted by the
timeout.

Wait forever in debugging mode

---

realm/realm-library/src/main/java/io/realm/Realm.java

Added Missing `throws` in the javaDoc

added the throw documentation for delete method

---

CHANGELOG.md
realm/realm-library/src/main/cpp/io_realm_SyncManager.cpp
realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp
realm/realm-library/src/main/cpp/io_realm_internal_Util.cpp
realm/realm-library/src/main/cpp/java_binding_context.hpp
realm/realm-library/src/main/cpp/jni_util/java_global_weak_ref.cpp
realm/realm-library/src/main/cpp/jni_util/java_global_weak_ref.hpp
realm/realm-library/src/main/cpp/jni_util/java_local_ref.hpp
realm/realm-library/src/main/cpp/jni_util/java_method.cpp
realm/realm-library/src/main/cpp/jni_util/java_method.hpp
realm/realm-library/src/main/cpp/jni_util/jni_utils.cpp
realm/realm-library/src/main/cpp/jni_util/jni_utils.hpp
realm/realm-library/src/main/cpp/objectserver_shared.hpp
realm/realm-library/src/main/cpp/util.cpp
realm/realm-library/src/main/cpp/util.hpp

* Move the global jvm pointer to JniUtils and add some helper functions.
* Wrapper for jmethodID, global weak ref.
* Refactor the wrapper for the local ref.
* Before using the global weak ref, always try to acquire a local ref
first since until Android 4.0 weak global references could only be
passed to NewLocalRef, NewGlobalRef, and DeleteWeakGlobalRef.
See https://developer.android.com/training/articles/perf-jni.html#unsupported
for more details. This fix #3726 .

RAII wrapper for some JNI resources

---

realm/realm-library/src/main/java/io/realm/BaseRealm.java

It is related #3520.
Compacting encrypted Realms is working, so Javadoc should be updated.

Update Javadoc of Realm.compactRealm.

---

build.gradle

The gradle exec task only takes the last commandLine arg.
To fix the manual uploading in the release process.

realm-java-<version>.zip cannot be uploaded

---

README.md
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java

... and to separate connected tests that require a server and those that do not
Also raise the timeout for the connectedUnitTests from 7 to 10 seconds (necessary for Nexus 4, 5.1.1)

Edited the README.md to clarify some of the "Gottchas"

---

realm/realm-library/build.gradle
realm/realm-library/src/main/java/io/realm/internal/async/RealmThreadPoolExecutor.java

of counting processors and setting the max threads for the Executor. (#3810)

Count 'cpuX' files in /sys/devices/system/cpu as a more accurate way

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/java/io/realm/CredentialsTests.java
realm/realm-library/src/objectServer/java/io/realm/SyncCredentials.java

Change the order of args for the custom method to match the iOS call
Add an overloaded 2 arg usernamePassword method that defaults createUser false
Add unit tests as appropriate

Issue 3698

---

CHANGELOG.md
gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy

fixes #4008 
Work-around for now is adding following two lines to `dependencies` in your `build.gradle`
```
kaptAndroidTest 'io.realm:realm-annotations:<your_realm_version>'
kaptAndroidTest 'io.realm:realm-annotations-processor:<your_realm_version>'
```

Activated Realm's annotation processor on connectedTest when the project is using kapt

---

CHANGELOG.md
realm/realm-library/src/objectServer/java/io/realm/SyncSession.java
realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java

If an exception is thrown in an async error handler, the app's behaviour is highly unpredictable. We swallow the exception and log that it happens but let the app continue.
Closes #3559

Ignore exceptions

---

Jenkinsfile
README.md
dependencies.list
realm/config/findbugs/findbugs-filter.xml
realm/realm-library/src/androidTest/AndroidManifest.xml
realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java
realm/realm-library/src/objectServer/java/io/realm/SyncCredentials.java
realm/realm-library/src/objectServer/java/io/realm/SyncManager.java
realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
realm/realm-library/src/objectServer/java/io/realm/internal/network/AuthenticateResponse.java
realm/realm-library/src/objectServer/java/io/realm/internal/network/NetworkStateReceiver.java
realm/realm-library/src/objectServer/java/io/realm/internal/network/OkHttpAuthenticationServer.java
realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/Token.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/BaseIntegrationTest.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProcessCommitTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/service/SendOneCommit.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/service/SendsALot.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/Constants.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/HttpUtils.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/UserFactory.java
tools/sync_test_server/Dockerfile
tools/sync_test_server/configuration.yml
tools/sync_test_server/ros-testing-server.js
tools/sync_test_server/start_server.sh

This PR adds support for `SyncCredentials.accessToken()` which is required for #4005. I also found a number of issues with the integration tests. They have been fixed as well.

SyncCredentials.accessToken + Integration tests

---

realm/realm-library/src/objectServer/java/io/realm/ErrorCode.java

On par with protocol 16. The error code is handled by object store.
Closes #4046

Adding error code disabled_session

---

realm/realm-library/src/main/cpp/util.cpp

This is not ideal. In general this exception should be converted to
RealmFileException then convert to java exception. But normally the
first step is done in object store. Just work around it like this until
we migrate to Object Store's SyncManager.

Print the path when get File::AccessError

---

Jenkinsfile

This will allow avoiding issues when a previously running ROS container has not been closed for whatever reason. Fixes realm/ci#61

Don't use a fixed name for the ROS container

---

realm/realm-library/src/main/java/io/realm/RealmConfiguration.java

encryptionKey requires a 64 byte key instead of a 64 bit key. May lead to confusion

Corrected RealmConfiguration#encryptionKey JavaDoc

---

CHANGELOG.md
realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp
realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java

Treat the SharedRealm the same as other native objects.
SharedRealm.close will only call Object Store Realm::close without
deleting the ShareRealm pointer.
Then we don't need the finalizer anymore. Fix #3730 .
This is related with
https://github.com/realm/realm-object-store/pull/318
as well. It is possible that java close the Realm in any of the Object Store's 
callbacks. To avoid Object Store operating on a invalid SharedRealm
pointer, binding should try to make sure after callbacks. However, it
cannot be totally avoided since user could set the Realm instance to
null and the instance can be GCed at any time. It is still something
should be considered in the Object Store implementation.

Free the SharedRealm in phantom daemon

---

CHANGELOG.md
gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy

`realm-annotations-processor` has a transitive dependency to `realm-annotations`.
No need to add it manually.
And this change also fixes #4087.

remove kapt dependency to io.realm:realm-annotations

---

realm/realm-library/build.gradle

allow to skip native build by setting buildTargetABIs to empty

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmCollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/CustomMethods.java
realm/realm-library/src/main/java/io/realm/RealmList.java
realm/realm-library/src/main/java/io/realm/RealmResults.java

Got reported directly, and fixing it was easier than creating the issue :D
EDIT: `static.realm.io` is still insanely slow so CI times out on the unit tests. Will move into review once that is fixed

Fix RealmCollection.contains not respecting custom equal methods

---

realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java
realm/realm-library/src/main/cpp/io_realm_RealmFileUserStore.cpp
realm/realm-library/src/objectServer/java/io/realm/ObjectServer.java
realm/realm-library/src/objectServer/java/io/realm/RealmFileUserStore.java

calling `nativeConfigureMetaDataSystem` once to init the ObjectStore metadata table needed for client reset action & store Sync users

remove duplicate init of the OS metadata

---

realm/realm-library/build.gradle

now publishToMavenLocal in realm/realm-library/build.gradle depends on assembleRelease task insteadof assemble task in order to improve build time.
@realm/java

Improve performance of publishToMavenLocal (installRealmJava) task

---

realm/realm-library/src/main/java/io/realm/RealmConfiguration.java

There is no `context.getFiles()` method. The correct documentation for the `directory()` should read 
`The default value is {@code context.getFilesDir()}` instead of `The default value is {@code context.getFiles()}`

Fix documentation for directory() method in RealmConfiguration

---

CHANGELOG.md
realm-transformer/src/main/groovy/io/realm/transformer/BytecodeModifier.groovy
realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java
realm/realm-library/src/main/java/io/realm/internal/RealmObjectProxy.java

This change is a part of fixes of #3809.
Before this PR:
```
public class Model implements Realm Model {
private String foo;
public Model() {
super();
// 2: context is not set yet
realmGet$foo(); // 3: this getter injects the context
}
}
public class ModelRealmProxy extends Model {
public ModelRealmProxy() {
super(); // 1: execute the parent's constructor
// 4: proxyState == null should be false since getter already injected the context.
// If parent's constructor does not use any setters/getters at all, context is injected here.
if (proxyState == null) {
injectObjectContext();
}
}
}
```
After this PR:
```
public class Model implements Realm Model  {
private String foo;
public Model() {
super();
injectObjectContext(); //2: this line is injected by our transformer.
realmGet$foo(); // 3: no …
```

improve performance of getters and setters in proxy classes

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/NotificationsTest.java
realm/realm-library/src/androidTest/java/io/realm/OrderedCollectionChangeSetTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/CollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/ObserverPairListTests.java
realm/realm-library/src/main/cpp/CMakeLists.txt
realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp
realm/realm-library/src/main/cpp/io_realm_internal_CollectionChangeSet.cpp
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/OrderedCollectionChangeSet.java
realm/realm-library/src/main/java/io/realm/OrderedRealmCollectionChangeListener.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmCollectionObservable.java
realm/realm-library/src/main/java/io/realm/RealmObservable.java
realm/realm-library/src/main/java/io/realm/RealmResults.java
realm/realm-library/src/main/java/io/realm/internal/Collection.java
realm/realm-library/src/main/java/io/realm/internal/CollectionChangeSet.java
realm/realm-library/src/main/java/io/realm/internal/Context.java
realm/realm-library/src/main/java/io/realm/internal/ObserverPairList.java
realm/realm-library/src/main/java/io/realm/internal/RealmNotifier.java

- Add RealmObservable and RealmCollectionObservable interfaces.
- Enable detailed change information for RealmResults through
OrderedCollectionChange interface.
- Fix a bug in the ObserverPairList which could cause the removed
listener gets called if it was removed during previous listener
iteration.
Fix #989

Implement fine gained notification

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/RxJavaTests.java

Fixes #3138 
It appears that moving to the Object Store notifications accidentally fixed https://github.com/realm/realm-java/issues/3138 for us. Yay.
I just added the unit tests to verify + changelog.

Deleted RealmObjects are now emitted as well.

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/main/java/io/realm/RealmObject.java

This PR makes RealmObject have the same methods for controlling change listeners as `OrderedRealmCollection` but without implementing the interface.
Yes, it is extremely annoying, but so far any attempt to make it better have failed:
```
public abstract class Realm<E extends RealmObject> implements RealmModel, RealmObservable<E>
```
* Crashes the Java compiler because it cannot find `rx.Observable`. Which is extremely perplexing. Possible the class loader does something else than normal in this case. We cannot require everyone to include RxJava. Attempting to add RxJava as a provided dependency in the maven POM for the artifact did not solve the issue.
* Also Kotlin has stricter requirements for generics. Causing fun errors like `Projections are not allowed for immediate arguments of a …

RealmObject now uses the same interface methods for RealmObservable

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
realm/realm-library/src/main/java/io/realm/OrderedRealmCollectionImpl.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java
realm/realm-library/src/main/java/io/realm/RealmResults.java

Those methods should only exist in the RealmResults. And maybe those
should be deprecated since all they are doing is distinct on the
where().
And annotate methods with @Override in the OrderedRealmCollectionImpl.

Deprecate distinctXxx of RealmResults

---

realm-transformer/src/main/groovy/io/realm/transformer/BytecodeModifier.groovy
realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/DefaultValueFromOtherConstructor.java

Apparently the recent change to getters/setters (https://github.com/realm/realm-java/pull/4206)  caused a regression not caught by our unit tests, but it was revealed by our Kotlin example (we should really re-enable checking those again).
/cc @zaki50

Expose bug with default constructors

---

realm/realm-library/build.gradle

revert #4207 since we need to build both release and debug before importing `realm` project into Android Studio.
@realm/java

Revert #4207

---

realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/Realm.java

Since this.removeListener and this.removeAllListeners does not exist,
super.removeListener and super.removeAllListeners are not necessary.
Just use removeListener and removeAllListeners instead.
Please merge #4247 before this PR.

Remove unnecessary 'super's

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java

Throw IllegalStateException instead of process crash when any of thread confined methods in RealmQuery is called from wrong thread.
fixes #4228 
@realm/java

Add thread check to methods in RealmQuery.

---

realm/realm-annotations-processor/build.gradle

UT in `realm/realm-annotations-processor` only uses classes.jar of `baseRelease`.
No need to depend on entire `assemble` task.
@realm/java

minimize task dependency

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmMigrationTests.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java

Fixes #4075 
I used `IllegalArgumentException` instead of `UnsupportedOperationException`, since the later should only really be used if the method fails for all input IMO.

Fail Realm.migrateRealm() if a SyncConfiguration is used.

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java
realm/realm-library/src/main/java/io/realm/Realm.java

@bmeike and others have run into this from time to time. But throwing the original exception makes much more sense when debugging. Apparently, we didn't have an issue tracking it.

Proper RealmMigrationNeededException is now thrown.

---

realm/realm-library/src/main/java/io/realm/Realm.java

If `Realm.getInstance()` is called in the 'transaction' object, calling `close()` does not cancel current transaction. To ensure that the transaction is not left open, cancel it explicitly if needed.
@realm/java

Cancel transaction explicitly

---

realm/realm-library/src/main/java/io/realm/internal/async/RealmThreadPoolExecutor.java

`edu.umd.cs.findbugs.annotations.SuppressWarnings` is deprecated.
This PR replaces it with `edu.umd.cs.findbugs.annotations.SuppressFBWarnings`.
@realm/java

stop using deprecated findbugs annotation

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java

Add `Override` annotation to accessors and stop using raw type in proxy classes in order to remove warnings from java.
fixes #4329

fix warnings in generated code

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/main/java/io/realm/ProxyState.java
realm/realm-library/src/main/java/io/realm/internal/PendingRow.java

Fix #4352
The findFirstAsync()'s behavior doesn't match the javadoc from the first
day the API was introduced. It kept running the query until it could
find a row match the query condition. This behavior create difficulties
if user want to check if there is no object in the db. Also it was not
consistent with the behavior of findFirst() which will return an invalid
row in the same condition.

findFirstAsync returns invalid row if no object

---

realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp
realm/realm-library/src/main/cpp/io_realm_internal_Util.cpp
realm/realm-library/src/main/cpp/jni_util/java_class.cpp
realm/realm-library/src/main/cpp/jni_util/java_class.hpp
realm/realm-library/src/main/cpp/jni_util/java_global_ref.cpp
realm/realm-library/src/main/cpp/jni_util/java_global_ref.hpp
realm/realm-library/src/main/cpp/jni_util/jni_utils.cpp
realm/realm-library/src/main/cpp/jni_util/jni_utils.hpp

- Added two class to help manage the jobject lifecycle.
- Use a static local JavaClass for SyncManager.
Since to support old/new values for object notification, we need to create java objects from JNI frequently. Clean up this part to make future work easier.

Add JNI helper class JavaGlabalRef and JavaClass

---

realm/realm-library/src/main/java/io/realm/RealmQuery.java

Javadoc for findFirstAsync

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/CollectionTests.java
realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp

- The listeners on RealmList/RealmResults will be tiggered immediately
when the transaction committed on the same thread if the collections
are changed or the async query should return.
- Listeners on the RealmObject will have same behaviour after #4331
merged.
This is to solve the problem for predictive UI animations and local
transactions.
Fix #4245

Trigger collection listeners when commit

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/log/RealmLogTests.java
realm/realm-library/src/main/cpp/io_realm_SyncManager.cpp
realm/realm-library/src/main/cpp/io_realm_log_RealmLog.cpp
realm/realm-library/src/main/cpp/jni_util/log.cpp
realm/realm-library/src/main/cpp/jni_util/log.hpp
realm/realm-library/src/main/java/io/realm/log/RealmLog.java

Set the all core logger bridges log level with the global log level.
Fix #4337

Set log level for core logger bridge

---

realm/realm-library/build.gradle
realm/realm-library/src/main/cpp/CMakeLists.txt

Fix #4130
- Fix the problem with build.gradle's coreSourcePath.
- Build with output in the core source dir instead of deploy the
tarball.
- Skip objectServer flavor when build from core source.
- Build sync from source code is still not supported.
There are still a lot of improvements can be done in the future:
- Build specific ABI only when build core.
- Skip core tarball generation.
But it would be a good idea to do above after core switches to cmake.
Our current build system sucks.

Enable build from core source

---

realm/realm-library/src/androidTest/java/io/realm/ObjectChangeSetTests.java
realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp
realm/realm-library/src/main/cpp/jni_util/java_global_ref.hpp

When there are more than 512 fields change, the JNI local ref table size
limitation may be reached. Fix #4378

Acquire a global ref of jstring for field changes

---

realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmCache.java
realm/realm-library/src/main/java/io/realm/RealmSchema.java

@realm/java 
The main purpose of this refactoring is making it easy to distinguish updating `ColumnIndices` object itself and creating new `ColumnIndices` object.

refactor internal method name in RealmSchema

---

examples/build.gradle
examples/jsonExample/build.gradle

Users don't need to use `com.neenbedankt.android-apt` plugin anymore.
@realm/java

remove com.neenbedankt.android-apt plugin from example projects.

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/ObjectChangeSetTests.java
realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp

The changed field string array needs to be reset after sending
notifications.
Fix #4437

Stale local ref crash with Object listener

---

CHANGELOG.md
realm/realm-library/src/main/cpp/jni_util/java_method.cpp
realm/realm-library/src/main/java/io/realm/internal/OsObject.java

- Fix #4461.
- Use release assertion when finding java method.

KeepMember OsObject.notifyChangeListeners

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmSchemaTests.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/OsRealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/OsRealmSchema.java
realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java
realm/realm-library/src/main/java/io/realm/RealmSchema.java
realm/realm-library/src/main/java/io/realm/StandardRealmObjectSchema.java

fixes #4443 
I fixed incompatibility of `RealmSchema.getAll()` in addition to `BaseRealm.getSchema()`.
@realm/java

fix API incompatibility introduced in 3.1.0

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/internal/CollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/SharedRealmTests.java
realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp
realm/realm-library/src/main/java/io/realm/internal/Collection.java
realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java

- Keep the SharedRealm ptr valid when close it. To allow the is_closed
checking could throw in the Object Store and it can be converted to a
friendly Java exception.
- Check if SharedRealm is closed when create collection iterator. Throw
an ISE if it is. Fix #4471 .

Dont reset SharedRealm ptr

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/main/java/io/realm/internal/PendingRow.java

Otherwise the pending query will be executed again if there is a local
transaction in the listener. That would cause a infinite recursion or
NPE (like #4495).
Fix #4495

Clear pending collection first for findFirstAsync

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java

Closes #3476 
This PR adds back `refresh()`. Mostly for two reasons:
1) With the adoption of the ObjectStore and Snapshots for iterations, the reasons we originally removed `refresh()` in favour of `waitForChange()` for are no longer valid.
2) We keep getting support requests by people using event buses and such instead of RealmChangeListeners. In some of those cases `refresh()` does make sense, so this would lessen the support burden as well.
3) @Zhuinden no longer have to keep various hacks up to date ( Just kidding mate, we really appreciate what you are doing 😄  💯 ) 
Feel free to tell me if this is just stupid, but then we should probably also close #3476 with a Wont Fix.

Re-add Realm.refresh()

---

realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java

When the case is using ExpectedException, TestRealmConfigurationFactory
won't be able to detect the Realm instance is not closed.

Fix flaky test caused by non-closed Realm

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/main/java/io/realm/Realm.java

Closes #4493 
We cannot "fix" it, but this way we try as hard as possible to recover from the situation, and if that fails we throw a better exception, explaining the situation.
/cc @rajuashok

Try to create getFilesDir if it doesn't exist on startup.

---

realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTests.java
realm/realm-library/src/androidTest/java/io/realm/LinkingObjectsManagedTests.java
realm/realm-library/src/androidTest/java/io/realm/NotificationsTest.java
realm/realm-library/src/androidTest/java/io/realm/ObjectChangeSetTests.java
realm/realm-library/src/androidTest/java/io/realm/OrderedCollectionChangeSetTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmChangeListenerTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmModelTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTest/java/io/realm/RxJavaTests.java
realm/realm-library/src/androidTest/java/io/realm/SortTest.java
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java
realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/CollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/RealmNotifierTests.java
realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java
realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SessionTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ManagementRealmTests.java

During the process of fixing the last couple bugs in the backlinks UTs, I discovered that the `RunInLooperThread` `Rule` was both difficult to read and, probably because of that, had fundamental threading bugs.  This PR fixes both of those problems.

Fix threading bugs in RunInLooperThread rule

---

build.gradle

Current `clean` task depends on the artifacts of the project itself. That means `clean` task only works after successful build.
I've added `manualClean` task, which removes all build files without requiring any artifacts.
@realm/java

Add manualClean task, which works without requiring any dependency artifacts

---

examples/kotlinExample/build.gradle

@realm/java 
Android Gradle Plugin 2.4.0(-alpha) requires Kotlin 1.1.2 plugin.

Update Kotlin to 1.1.2

---

realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTests.java
realm/realm-library/src/androidTest/java/io/realm/LinkingObjectsManagedTests.java
realm/realm-library/src/androidTest/java/io/realm/NotificationsTest.java
realm/realm-library/src/androidTest/java/io/realm/ObjectChangeSetTests.java
realm/realm-library/src/androidTest/java/io/realm/OrderedCollectionChangeSetTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmCacheTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmChangeListenerTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmInMemoryTest.java
realm/realm-library/src/androidTest/java/io/realm/RealmInterprocessTest.java
realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmModelTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTest/java/io/realm/RxJavaTests.java
realm/realm-library/src/androidTest/java/io/realm/SortTest.java
realm/realm-library/src/androidTest/java/io/realm/TestHelper.java
realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/CollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/RealmNotifierTests.java
realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java
realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java
realm/realm-library/src/androidTest/java/io/realm/util/RealmBackgroundTask.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SessionTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ManagementRealmTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/Constants.java

This is a backport of #4563 (already merged to master), and #4572 (soon to be abandoned) to merge them to the release branch.
The cherry-picked commits were:
commit 9e740f8fd5d631070d54c9d2b3ce5e3c5d7ea410
Author: G. Blake Meike <blake.meike@realm.io>
Date:   Thu Apr 27 12:42:28 2017 -0700
Standardize test timeouts
commit 9e86af814ba2878ea91969d8cd073a9a7456d372
Author: G. Blake Meike <blake.meike@realm.io>
Date:   Wed Apr 26 13:52:15 2017 -0700
Respond to comments
Fix spelling errors
Clean up multi-error recovery.
commit fd76c00e92b759b2d9461381e8158954cc516d7d
Author: G. Blake Meike <blake.meike@realm.io>
Date:   Tue Apr 25 06:25:47 2017 -0700
Fix threading bugs in RunInLooperThread rule
This will, of course fail to merge to master.

Backport Unit Test PRs to  releases

---

examples/threadExample/src/main/java/io/realm/examples/threads/AsyncTaskFragment.java

made `ImportAsyncTask` class static and canceled the task in `onStop() `.
fixes #4580

Fix Context leak warning in threadExample (#4580)

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmCacheTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java
realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmCache.java
realm/realm-library/src/main/java/io/realm/internal/async/RealmThreadPoolExecutor.java

Fix #2299
- Add APIs to get Realm instance asynchronously.
- Remove some useless methods.
There are some work need to be done before create the first Realm instance
in the process, like creating schema table, doing migration, etc.. Those
could block the UI thread quite badly. This commit tries to do those
initialization work in the background and hold a Realm instance in the
background until the 2nd instance created in the caller thread.
A better solution than this would be do initialization in the
background and only deliver a column indices cache to caller thread
without holding a Realm instance in the background. But that is not
possible since from the current database design, we cannot know if the
schema changes compared with the last time it was opened.
Also create a SharedGroup in …

Implement getInstanceAsync

---

realm/realm-library/src/main/java/io/realm/internal/CheckedRow.java
realm/realm-library/src/main/java/io/realm/internal/Collection.java
realm/realm-library/src/main/java/io/realm/internal/CollectionChangeSet.java
realm/realm-library/src/main/java/io/realm/internal/LinkView.java
realm/realm-library/src/main/java/io/realm/internal/NativeContext.java
realm/realm-library/src/main/java/io/realm/internal/NativeObjectReference.java
realm/realm-library/src/main/java/io/realm/internal/RealmContext.java
realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java
realm/realm-library/src/main/java/io/realm/internal/Table.java
realm/realm-library/src/main/java/io/realm/internal/TableQuery.java
realm/realm-library/src/main/java/io/realm/internal/UncheckedRow.java

Renames `io.realm.internal.Context` to `io.realm.internal.NativeContext` (started out as RealmContext) to avoid confusion with `android.content.Context`

Rename Context to NativeContext

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/main/java/io/realm/internal/RealmNotifier.java

Otherwise it will cause infinite recursion if a transaction is committed
in the callback.
Fix #4595

Remove onSuccess callback before calling it

---

realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java

Apparently waiting some random millisecond is never a good idea.

    Wait for async tasks finish to solve flaky test

---

CHANGELOG.md
examples/kotlinExample/build.gradle
examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/KotlinExampleActivity.kt
examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/model/Cat.kt
examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/model/Dog.kt
examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/model/Person.kt
realm-annotations/src/main/java/io/realm/annotations/LinkingObjects.java

Fixes #4611 
Apparently, annotations need CLASS retention in order to work with Kotlin. I'm guessing some combination of how annotation processors work with the Kotlin compiler.
Also updated the example code to be more correct (don't need open on fields / updated Anko). And yes that should probably have been in another PR 😄

Fixed @LinkingObjects notation for Kotlin

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/OrderedRealmCollectionChangeListener.java
realm/realm-library/src/main/java/io/realm/RealmChangeListener.java
realm/realm-library/src/main/java/io/realm/RealmObjectChangeListener.java

By using a shorthand for the generic argument when creating Changelisteners, IntelliJ (and Android Studio) will expand that automatically to be a camel-cased version of the generic argument. This makes the code more readable with minimal effort. Existing code will not be affected.
Example:
```
// Before
RealmResults<Permission> permissions = realm.where(Permission.class).findAll();
permissions.addChangeListener(new RealmChangeListener<RealmResults<Permission>>() {
@Override
public void onChange(RealmResults<Permission> element) {
// user forced to manually rename `element` to something more descriptive
}
});
// Now 
permissions.addChangeListener(new RealmChangeListener<RealmResults<Permission>>() {
@Override
public void onChange(RealmResults<Permission> permissions) {
// IntelliJ will …
```

Use shorthand for generic arguments for better AS support

---

realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp
realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java

- Remove unused methods.
- Fix double negatives.
- Use auto& to avoid creating temp objects.

Clean up SharedRealm source

---

realm/realm-library/src/main/java/io/realm/RealmList.java
realm/realm-library/src/main/java/io/realm/RealmObject.java
realm/realm-library/src/main/java/io/realm/RealmResults.java

Closes https://github.com/realm/realm-java/issues/4626
Closes https://github.com/realm/realm-java/issues/4472
This adds a mention about the GC to all relevant listeners. Note, the subtle differences in the code samples ;)
Also, this has not been added to the `Realm` change listeners as our internal `RealmCache` keeps a strong reference to them while they are open.

Add comment about GC to all relevant change listeners

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java

Make the `toString` methods in the DynamicObject Proxy and the Realm Proxy more up-front about who  they are.

Make the proxy toString methods reveal themselves

---

realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/JNIQueryTest.java
realm/realm-library/src/androidTest/java/io/realm/internal/JNIRowTest.java

When I compiled Realm java with Java 8 compiler, I got some warnings.
This PR fixes those warnings in advance.
@realm/java

fix ambiguous method calls warned by Java 8 compiler

---

CHANGELOG.md
examples/moduleExample/app/build.gradle
examples/moduleExample/app/src/main/java/io/realm/examples/appmodules/ModulesExampleActivity.java
realm/realm-library/src/androidTest/java/io/realm/ColumnIndicesTests.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmSchema.java
realm/realm-library/src/main/java/io/realm/internal/ColumnIndices.java
realm/realm-library/src/main/java/io/realm/internal/util/Pair.java

Fixes #4673 
The new ColumnIndices wrapper cached names using `class.getSimpleName()` which breaks when the class is obfuscated (We should really have caught this in code review 😢 )
I modified it so a pair consisting of `<class, realSimpleName>` is now being passed around instead. It complicated the internals of `ColumnIndices` a little more than I would like (We could really use a MultiKeyMap implementation).
Creating/Copying this class is now also more expensive as we have to go through the mediator for the proper non-obfuscated name, but given how rarely this happens, it is probably acceptable for now.
We have an example `moduleExample/app` that used a proguarded Realm and we test the Release build as part of the release process, but unfortunately, that example didn't use any query …

Fix queries not working on proguarded Realms model classes

---

realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmSchemaTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/AnimalModule.java
realm/realm-library/src/androidTest/java/io/realm/entities/HumanModule.java

Those tests pass with current schema implementation since currently it
will create extra object schemas which are not in the module. This
behaviour is not right and will fail those tests in the future schema
refactor.
So always define all the needed object schemas in the module.
This is needed for #4674

Fix test case with missing linking object schema

---

CHANGELOG.md
realm/realm-library/src/main/cpp/io_realm_RealmFileUserStore.cpp
realm/realm-library/src/objectServer/java/io/realm/RealmFileUserStore.java
realm/realm-library/src/objectServer/java/io/realm/SyncManager.java
realm/realm-library/src/objectServer/java/io/realm/SyncSession.java
realm/realm-library/src/objectServer/java/io/realm/internal/objectserver/ObjectServerUser.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/BaseIntegrationTest.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SSLConfigurationTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncedRealmTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/BaseIntegrationTest.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/EncryptedSynchronizedRealmTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ManagementRealmTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProcessCommitTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/HttpUtils.java

Replaces #4754
Changed integration tests to completely reset Sync between each test. We should probably consider a more global reset function since right now reset is scattered between multiple classes. I didn't want to do this as part of this PR though.

Fix admin users not connection correctly to ROS

---

realm/realm-library/build.gradle

From Android Plugin Version 2.2.0, it tries to strip debug symbols of
native libs for all build types (even debug build!!??).
I don't like something try to be smart, so just let our cmake handler
stripping and backup the unstripped libs.

Don't strip debug symbols for debug build!

---

examples/kotlinExample/build.gradle
realm/build.gradle

Updated kotlin to `1.1.2-5`.
And now example project uses `kotlin-stdlib-jre7` instead of `kotlin-stdlib`.
Chnagelog of kotlin 1.1.2-5 is https://github.com/JetBrains/kotlin/blob/1.1.2/ChangeLog.md#112-5

Update kotlin to 1.1.2-5

---

realm/realm-library/src/syncIntegrationTest/java/io/realm/BaseIntegrationTest.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SSLConfigurationTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncedRealmTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/EncryptedSynchronizedRealmTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ManagementRealmTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProcessCommitTests.java

Logging was not reset correct when running integration tests with @RunTestInLooperThread. Also clean up all subclasses of `BaseIntegrationTest`

Fix logging for RunTestInLooperThreadTests integration tests.

---

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
realm/realm-library/build.gradle

There is no reason that generated code, in production, should ever generate a warning.
We may decide for any of a number of reasons, that we wish to generated code that would otherwise generate a warning.  We may also decide to pay attention to some warnings, an eliminate them.
The user, who can *never* do anything about warnings in the generated code, though, should never, ever see them.

Suppress warnings in generated code.

---

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java

I would like to be able to read the proxy code easily, so that I can make the (possibly somewhat complicated) changes for `RealmInteger`.  There should be absolutely no functional changes here: just syntax.

Clean up the Proxies a bit, in prep for RealmInteger mods

---

tools/sync_test_server/ros-testing-server.js

According to @mrackwitz, we need to delete the `realm-object-server` directory between each integration test to correctly reset ROS ( https://github.com/realm/realm-object-server/issues/1225#issuecomment-308216359 ) .
This error caused #4655 to be extremely flaky. After this change, it seems to run consistently.

Correctly reset integration tests.

---

Dockerfile

Migrated CI environment to `sdkmanager` command from deprecate `android` command.

migrate to sdkmanager

---

tools/sync_test_server/Dockerfile
tools/sync_test_server/configuration.yml
tools/sync_test_server/ros-testing-server.js

- Hack for detecting if the ROS is fully initialized in the docker
sided.
- Dockerfile optimization.
- Use "0.0.0.0" instead of "::" to solve dns issues inside docker.

Fix flaky tests caused by half inited ROS

---

CHANGELOG.md
realm/realm-library/src/main/cpp/io_realm_SyncSession.cpp
realm/realm-library/src/main/cpp/jni_util/java_local_ref.hpp

- Add support for null JavaLocalRef.
- Clean the local ref after notifyAllChangesDownloaded.

Local ref needs to be cleaned on client thread

---

tools/sync_test_server/ros-testing-server.js

Used the wrong method for error reporting which crashed the Integration Test Server. Ups.

winston.err did not exist

---

realm/realm-library/src/androidTest/java/io/realm/TestHelper.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/PermissionManagerTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/UserFactory.java

This PR adds a few helper methods required for the PermissionManager unit tests in #4731

PermissionWrapper unit test helper methods

---

realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java
realm/realm-library/src/objectServer/java/io/realm/PermissionManager.java
realm/realm-library/src/objectServer/java/io/realm/SyncUser.java

Discovered this embarrassing bug while writing unit tests for #4731 ... apparently caching is hard.
I modified the cache to be per user.

PermissionManger should not return same instance for different users

---

realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java
realm/realm-library/src/main/java/io/realm/OrderedRealmCollectionImpl.java
realm/realm-library/src/main/java/io/realm/OrderedRealmCollectionSnapshot.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmConfiguration.java
realm/realm-library/src/main/java/io/realm/RealmList.java
realm/realm-library/src/main/java/io/realm/RealmMigration.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java
realm/realm-library/src/main/java/io/realm/StandardRealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/exceptions/RealmFileException.java
realm/realm-library/src/main/java/io/realm/internal/SortDescriptor.java
realm/realm-library/src/main/java/io/realm/internal/fields/CachedFieldDescriptor.java
realm/realm-library/src/main/java/io/realm/internal/fields/DynamicFieldDescriptor.java
realm/realm-library/src/main/java/io/realm/internal/fields/FieldDescriptor.java
realm/realm-library/src/main/java/io/realm/log/RealmLog.java
realm/realm-library/src/objectServer/java/io/realm/ErrorCode.java
realm/realm-library/src/objectServer/java/io/realm/ObjectServer.java
realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java
realm/realm-library/src/objectServer/java/io/realm/SyncManager.java
realm/realm-library/src/objectServer/java/io/realm/SyncSession.java
realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
realm/realm-library/src/objectServer/java/io/realm/internal/network/AuthenticateResponse.java

Added explicit Locale information to follow `lint`s advice.

Explicitly specify Locale for String.format() instead of implicit current Locale

---

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/internal/OsSchemaInfo.java
realm/realm-library/src/main/java/io/realm/internal/RealmProxyMediator.java
realm/realm-library/src/main/java/io/realm/internal/modules/CompositeMediator.java
realm/realm-library/src/main/java/io/realm/internal/modules/FilterableMediator.java

Using map to avoid duplicated OsSchemaInfo in mediator, especially it is
an common case for composite mediator.
The key is the module class. Not using class name string is because of
we may want to support same name class in different packages in the
future.

Returns a schema info map in mediator

---

realm/realm-annotations-processor/src/main/java/io/realm/processor/Backlink.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/DefaultModuleGenerator.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmJsonTypeHelper.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyInterfaceGenerator.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java
realm/realm-annotations-processor/src/test/java/io/realm/processor/RealmProcessorTest.java
realm/realm-annotations-processor/src/test/resources/some/test/ÁrvíztűrőTükörfúrógép.java

Explicitly specify Locale for String.format() in our annotation processor.
And also added a test for non-latin model name and field names.

Explicitly specify Locale for String.format() in our annotation processor

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmLinkTests.java
realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp

If the link query is on a nullable field, it seems to query the wrong field.
This is embarrassing bug, and the solution is simple: Follow links between tables and not queries links.
Fixes #4856

Fixing isNull() for link queries

---

CHANGELOG.md
realm/realm-library/src/main/cpp/jni_util/log.cpp

I discovered this while debugging our unstable integration tests.
I haven't found a way to reproduce this in a unit test since it depends on the logging happening from a non-java thread (like the Sync thread).
Error was this one:
```
06-30 06:33:51.053 11311 13305 I REALM_SYNC: Connection[12]: Session[29]: Sending: UNBIND
06-30 06:33:51.054 11311 13305 F art     : art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): local reference table overflow (max=512)
06-30 06:33:51.054 11311 13305 F art     : art/runtime/indirect_reference_table.cc:115] local reference table dump:
06-30 06:33:51.054 11311 13305 F art     : art/runtime/indirect_reference_table.cc:115]   Last 10 entries (of 512):
06-30 06:33:51.054 11311 13305 F art     : art/runtime/indirect_reference_table.cc:115] …
```

Fix reference table overflow when logging from the sync thread

---

realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/DynamicRealmTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmCacheTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmConfigurationTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmInMemoryTest.java
realm/realm-library/src/androidTest/java/io/realm/RealmInterprocessTest.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTest/java/io/realm/TypeBasedNotificationsTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/Thread.java
realm/realm-library/src/androidTest/java/io/realm/entities/conflict/String.java
realm/realm-library/src/androidTest/java/io/realm/internal/CollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/JNIRowTest.java
realm/realm-library/src/androidTest/java/io/realm/internal/ObserverPairListTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/android/JsonUtilsTest.java
realm/realm-library/src/main/java/io/realm/internal/OutOfMemoryError.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProcessCommitTests.java

Fixes a lot of warnings reported by ErrorProne. Mostly it looks like ErrorProne suddenly check our unit test files as well.

Fix ErrorProne warnings

---

realm/realm-library/src/syncIntegrationTest/java/io/realm/BaseIntegrationTest.java
tools/sync_test_server/ros-testing-server.js

Courtesy of @alebsack.
This fixes a bunch of flaky integration tests. Mostly seen during the development of #4558 , but could also be the root cause for a bunch of other stability issues we have seen lately with integration tests timing out.

Better control of ROS instance used by the integration tests

---

realm/realm-library/src/androidTest/java/io/realm/rule/RunTestWithRemoteService.java
realm/realm-library/src/androidTest/java/io/realm/rule/RunWithRemoteService.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProcessCommitTests.java

When running remote service test, the remote service is killed in after
function. It is too early when running it together with looper thread
test.

Fix multi-processes tests

---

CHANGELOG.md
realm/realm-library/src/objectServer/java/io/realm/ErrorCode.java

Discovered while adding tests for #4871 
This PR adds support for all known error codes coming from ROS, including standard HTTP error codes. All names are just capitalized versions of this list https://github.com/realm/realm-object-server/blob/master/object-server/doc/problems.md

Add missing sync error codes

---

realm/realm-library/src/objectServer/java/io/realm/ErrorCode.java

Happened because another feature was merged into `master` that also added this code. The automatic merge could not detect this.

Fix merge conflict resulting in duplicate error code

---

realm/realm-library/src/androidTest/java/io/realm/OrderedCollectionChangeSetTests.java

There is no guarantee that async query will be finished later after the
transaction. So the original assertEquals(9, collection.size()) might
not be true always.
Just remove the object deletion logic since it has nothing to do with
the test purpose.

Fix flaky emptyChangeSet_findAllAsync

---

realm/realm-library/src/androidTest/AndroidManifest.xml

android.permission.SET_DEBUG_APP and android:debuggable="true" are
needed for attaching debugger on some devices (eg.: Huawei device).

Options in AndroidManifest for attaching debugger

---

realm/realm-library/src/androidTest/AndroidManifest.xml

This reverts commit 790f225bf1820ddca2b6d52fa997466e078afef8.
That commit triggered a stange crash in JNI when Running RealmTest, it
failed with a native crash on test compactOnLaunch_shouldNotCompact:
JNI DETECTED ERROR IN APPLICATION:
can't call boolean
io.realm.DefaultCompactOnLaunchCallback.shouldCompact(long, long) on instance of
io.realm.RealmTests$6'
Looks very much like a bug in Android.

Revert "Options in AndroidManifest for attaching debugger"

---

realm/realm-library/src/objectServer/java/io/realm/ErrorCode.java

Fixes #4980 
This adds error codes not documented in the protocol definition.
Note, that these new error codes also clashes with existing ones. E.g we have `BAD_CHANGESET(212) // Bad changeset (UPLOAD)` and now `BAD_CHANGESET_DOWNLOAD(112) // Bad changeset (DOWNLOAD)`.
Finding a consistent way of naming all these enums do appear straight forward nor easy to make consistent and easy to use by end users, so I went with the simplest approach and suffixed the conflicting new ones with `_DOWNLOAD`. Suggestions for making this better is welcome.

Add missing error codes

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/java/io/realm/SessionTests.java
realm/realm-library/src/main/cpp/io_realm_SyncSession.cpp
realm/realm-library/src/objectServer/java/io/realm/SyncSession.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncedRealmTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/SyncSessionTests.java

Mostly to mirror `SyncSession.downloadAllServerChanges()`, but this should also prove quite helpful for a lot of our Sync integration tests.

Add support for SyncSession.uploadAllLocalChanges()

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmSchemaTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SchemaTests.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmMigrationTests.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/ImmutableRealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/ImmutableRealmSchema.java
realm/realm-library/src/main/java/io/realm/MutableRealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/MutableRealmSchema.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmCache.java
realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/RealmSchema.java

Before this change, Realm.getSchema() and DynamicRealm.getSchema() both
return a mutable version RealmSchema object. That would cause issue when
changing the typed Realm's schema then continue to use typed inferface
to access the Realm where the column indices might be changed already
and had not been refreshed before the transaction commited.
After this change:
Realm.getSchema() returns an immutable RealmSchema object. And all
RealmObjectSchema objects retrieved from that will be immutable as
well.

Immutable RealmSchema and RealmObjectSchema

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmSchemaTests.java
realm/realm-library/src/main/java/io/realm/MutableRealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/MutableRealmSchema.java
realm/realm-library/src/main/java/io/realm/internal/Table.java

`RealmSchema.create(String)` and `RealmObjectSchema.setClassName(String)` did not accept class name whose length was 51 to ~56~ 57.

Fix class name length check

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/Object4957.java

Close #4957
We are using HashMap to maintain a cache of added managed RealmObject
when doing copyOrUpdate. But if the given object graph contains objects
which have same PK but are different java object, cache missing will
happen. That caused the object got set multiple times. For non-list
fields, it is not a problem since it will eventually has the expected
value if user's objects graph is consistent. For list, that results the
elements in the list are added multiple times since we don't clear the
RealmList in copy().

copyToRealmOrUpdate cause dup values in list field

---

CHANGELOG.md
realm/realm-library/src/androidTest/AndroidManifest.xml
realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp
realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp
realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp
realm/realm-library/src/main/cpp/java_binding_context.cpp
realm/realm-library/src/main/cpp/java_binding_context.hpp
realm/realm-library/src/main/cpp/java_sort_descriptor.cpp
realm/realm-library/src/main/cpp/java_sort_descriptor.hpp
realm/realm-library/src/main/cpp/jni_util/java_method.cpp
realm/realm-library/src/main/cpp/jni_util/java_method.hpp
realm/realm-library/src/main/java/io/realm/CompactOnLaunchCallback.java
realm/realm-library/src/main/java/io/realm/internal/OsObject.java
realm/realm-library/src/main/java/io/realm/internal/SortDescriptor.java
realm/realm-library/src/objectServer/java/io/realm/SyncManager.java
realm/realm-library/src/objectServer/java/io/realm/SyncSession.java

- cherry-pick #4939 to enabled debug in menifest which caused a crash described in #4964.
- Removed API to create JavaMethod from jobject/class name string.  There seems to be a bug in Android JVM when getting the method by: jclass cls = env->GetObjectClass(obj); jmethodID method = env->GetMethodID(cls, "xxx", "xxx") The methodID retrieved by the above way triggers a strange bug in JVM, it reports the method cannot be found on a non-relevant object. Like:
> can't call boolean io.realm.DefaultCompactOnLaunchCallback.shouldCompact(long, long) on instance of io.realm.RealmTests$6'
Where RealmTest$6 has nothing to do with that JNI call.  It is not because of the local ref of cls has been deleted -- Even if it is deleted, the methodID should still be valid according to the doc:
> The class …

Work around jmethod bug with Android

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncManagerTests.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmMigrationTests.java
realm/realm-library/src/main/cpp/io_realm_RealmFileUserStore.cpp
realm/realm-library/src/main/cpp/io_realm_internal_Property.cpp
realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp
realm/realm-library/src/main/java/io/realm/internal/Property.java
realm/realm-library/src/objectServer/java/io/realm/RealmFileUserStore.java
realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
realm/realm-library/src/objectServer/java/io/realm/UserStore.java
realm/realm-library/src/objectServer/java/io/realm/internal/SyncObjectServerFacade.java

Breaking changes from Object Store:
to 50cf5ee583
- To identify a user, Object Store needs both user ID and auth URL. Thus
API has been changed in UserStore.
- Property::PropertyType has been changed which is not the same with
field types in the core anymore.

Update Object Store

---

realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp

The message in the nativeGetTable wants to talk about a `class` but, in stead, uses the name of the `table`.

Fix class name in not found message

---

Dockerfile
Jenkinsfile

Since the lto has been disabled, linking is much faster now. No need to
use lcache anymore.

Disable lcache

---

realm/realm-library/src/objectServer/java/io/realm/PermissionManager.java

Part of #4558 
Found during another review. This ensures that we correctly remove tasks from the task queue even though onSuccess/OnError callbacks throw an exception.

PermissionWrapper - Remove tasks if callback crashes

---

CHANGELOG.md
realm/realm-library/src/objectServer/java/io/realm/SyncUser.java

Part of #4558 
Deprecates `getManagementRealm()` in favour of `getPermissionManager()`. The implementation should be deleted in 4.0

Deprecate Management Realm

---

realm/realm-library/src/main/java/io/realm/internal/fields/CachedFieldDescriptor.java
realm/realm-library/src/main/java/io/realm/internal/fields/DynamicFieldDescriptor.java

This PR did not change the logic at all, but gave a common prefix `current` to variables those are updated in the loop.
The most important improvement in this PR is correct usage of `table` and `class`.

Refactor compileFieldDescription() in CachedFieldDescriptor and DynamicFieldDescriptor

---

realm/realm-library/src/main/java/io/realm/FieldAttribute.java

`FieldAttribute.PRIMARY_KEY` does not mark `REQUIRED` the field after this change https://github.com/realm/realm-java/commit/e36e69bb6887d3427b40f661a80c71b6dfb2548f#diff-8b882bdae59573a63bd9922af9ec0f81R144

Fix misleading documentation about FieldAttribute.PRIMARY_KEY

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/SortDescriptorTests.java
realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/internal/ColumnIndices.java
realm/realm-library/src/main/java/io/realm/internal/ColumnInfo.java
realm/realm-library/src/main/java/io/realm/internal/fields/CachedFieldDescriptor.java
realm/realm-library/src/main/java/io/realm/internal/fields/FieldDescriptor.java

This PR fixes #5096
The important change is in `CachedFieldDescriptor#compileFieldDescription()`.
At the end of the method, they passed `className` as an first argument of `setCompilationResults()`. However, that argument should be the name of the container class of final field and actually the `className` is not the one. 
This PR also improve performance of `CachedFieldDescriptor#compileFieldDescription()`.
In the method, map lookup happened three times with the same key for each field. This PR replaced it with just one lookup for each field.

Fix class name in exception message

---

realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp

I ran into this while debugging a unit test failure my unit tests in #4558  kept running into. 
I cannot reproduce it in standalone unit tests. It is 100% triggerable in some of my other tests but only in Android Studio, not from the commandline 🤔 Really puzzling
Anyway, getting the method reference when calling JNI works. If anyone has a better idea on how to do this, I'm all ears.
Sidenote: After this fix, all the flakiness from my PermissionManager tests seems have disappeared. So I suspect it previously was caused by flakiness in the notification subsystem and recent changes just caused the error to finally bubble up.
EDIT: And no, still got failing tests 😢

Object notifications cannot find class

---

examples/kotlinExample/build.gradle
realm/build.gradle

https://blog.jetbrains.com/kotlin/2017/08/kotlin-1-1-4-is-out/
Kotlin 1.1.4 now supports default nullability that we recently introduced to Realm Java.

Update kotlin to 1.1.4-2

---

dependencies.list
tools/sync_test_server/ros-testing-server.js

Better detection of when ROS is running. Previously you could run into a lot of `SocketTimeout` exceptions. Also upgraded ROS used in tests to latest stable Debian version.
@realm/java

Upgrade Integration Test setup

---

examples/kotlinExample/build.gradle
realm/realm-library/build.gradle

Original kapt feature has been deprecated. This PR enables `kotlin-kapt` plugin instead.

Apply kotlin-kapt plugin

---

examples/kotlinExample/build.gradle
realm/realm-library/build.gradle

This PR is applying the same changes with #5126 to `releases` branch.

apply kotlin-kapt plugin since original kapt feature has been deprecated

---

realm/realm-library/src/objectServer/java/io/realm/ErrorCode.java

@morten-krogh told me that `doc/protocol.md` was not the one we should refer from `ErrorCode.java`.
https://github.com/realm/realm-sync/pull/1561#issuecomment-323847407
I've update the comment in `ErrorCode.java`.

Update a reference URL of Client Error

---

realm/realm-library/src/androidTest/java/io/realm/internal/AndroidCapabilitiesTest.java
realm/realm-library/src/androidTest/java/io/realm/rule/RunInLooperThread.java
realm/realm-library/src/androidTest/java/io/realm/rule/RunTestInLooperThread.java
realm/realm-library/src/main/java/io/realm/internal/android/AndroidCapabilities.java

Required to test functionality that requires the Main thread _and_ also loops. The `@UITest` annotation does not have this capability.

Add support for `RunInHandlerThread` to emulate the Main thread

---

realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp
realm/realm-library/src/main/cpp/jni_util/java_global_ref.hpp
realm/realm-library/src/main/cpp/jni_util/java_global_weak_ref.cpp
realm/realm-library/src/main/cpp/jni_util/java_global_weak_ref.hpp
realm/realm-library/src/main/java/io/realm/internal/OsRealmConfig.java

Holding strong java refs in the lambda function in the Object Store
config will cause circular refs with SharedRealm/Callbacks/Config. That
will leak some objects.

Fix possible leaks with java callback in config

---

realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/SyncSessionTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/suite/IntegrationTestSuite.java

See https://github.com/realm/realm-object-store/pull/532
When assertion enabled, those will fail earlier. Without the assertion,
all different kind of native crash will happen.

Unclosed realm & SyncManager::reset_for_testing

---

CHANGELOG.md
realm/realm-library/src/main/cpp/io_realm_RealmFileUserStore.cpp
realm/realm-library/src/main/cpp/io_realm_SyncSession.cpp
realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp
realm/realm-library/src/main/cpp/io_realm_internal_OsObject.cpp
realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp
realm/realm-library/src/main/cpp/io_realm_internal_Util.cpp
realm/realm-library/src/main/cpp/java_binding_context.cpp
realm/realm-library/src/main/cpp/java_binding_context.hpp
realm/realm-library/src/main/cpp/java_class_global_def.hpp
realm/realm-library/src/main/cpp/jni_util/java_method.cpp
realm/realm-library/src/main/cpp/util.cpp
realm/realm-library/src/main/cpp/util.hpp

- Add JavaClassGlobalDef to handle global jclass loading.
- Move common types classes loading to JavaClassGlobalDef.
- Load SharedRealm$$SchemaChangeCallback & RealmNotifier in JNI_OnLoad
to fix #5195 .
- Code clean up.
NOTE:
Currently the JavaClassGlobalDef::initialize() takes about 0.3 ms on a
lowend armv7 device. So keeping less classes loaded at the beginning
will still be a good idea since the Realm.init() will be usually called
on the UI thread when start.

java_class_global_def for global class loading

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java

The columnInfo can be used instead which is much faster.

No need to call Table.getPrimaryKey in proxy

---

Jenkinsfile
dependencies.list
realm/realm-library/src/main/cpp/util.cpp
realm/realm-library/src/main/java/io/realm/exceptions/RealmFileException.java
realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java
realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
realm/realm-library/src/objectServer/java/io/realm/internal/network/AuthServerResponse.java
realm/realm-library/src/objectServer/java/io/realm/internal/network/ChangePasswordRequest.java
realm/realm-library/src/objectServer/java/io/realm/internal/network/OkHttpAuthenticationServer.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/EncryptedSynchronizedRealmTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProgressListenerTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/UserFactory.java
tools/sync_test_server/ros-testing-server.js

* Sync-RC21
* ROS 2.0.0-alpha.34
* Added support for Authorization headers
* Added support for new Sync exception
* Enabled remote revokation again
TODO

Upgrade to latest Sync RC + ROS 

---

Jenkinsfile

This PR changes PR's so they only build for `armeabi-v7a` and run integration tests against the `ObjectServer` variant. `master` still runs the full test suite.
Nesting was wrong as well so fixed.
Relevant changes are in https://github.com/realm/realm-java/commit/78a2af9af4f3e73a8edec4f57143f88c53cf3479
Build time for PR's have been reduced to ~22 minutes, so at least a 50% reduction. We can probably get that lower.
@emanuelez What would it take to run integration tests on an x86 emulator instead of on a device?
TODO

Minimize overhead on CI for PR builds.

---

realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java

It was added in #1379 to expose the timeout problem in finalizer. Since
we are not using finalizer anymore, just remove it.

Remove largeRealmMultipleThreads

---

realm/realm-library/src/androidTest/java/io/realm/internal/PrimaryKeyTests.java
realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp
realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp
realm/realm-library/src/main/java/io/realm/RealmCache.java
realm/realm-library/src/main/java/io/realm/internal/SharedRealm.java
realm/realm-library/src/main/java/io/realm/internal/Table.java

- Hide all the information about PK table from Java.
- Remove SharedRealm.readGroup().

Move PK table migration to JNI totally

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/internal/android/ISO8601UtilsTest.java
realm/realm-library/src/main/java/io/realm/internal/android/ISO8601Utils.java

Fixes #5309 
Add support for ISO8601 2-digit time zone designator for Date parsing as reported in Issue #5309.

Add support for ISO8601 2-digit time zone designator in Date parsing (#5309)

---

realm/realm-library/build.gradle
realm/realm-library/src/main/cpp/CMake/RealmCore.cmake
realm/realm-library/src/main/cpp/CMakeLists.txt

- Separate core library cmake to RealmCore.cmake
- Build core from source code with the new core's cmake build. This is
much faster than before, it will only build the needed ABI and
release/debug variant.

Build core from source

---

realm/realm-library/build.gradle
realm/realm-library/src/androidTest/java/io/realm/CollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/ManagedRealmCollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java

From #5354 
I should have listened to @beeender 
Using the debug version is causing all sorts of crashes. Reverting to using the `release` version until we can fix it.

Use release version of Sync when testing

---

realm/realm-library/src/androidTestObjectServer/java/io/realm/SchemaTests.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SessionTests.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncConfigurationTests.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmMigrationTests.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/TestSyncConfigurationFactory.java
realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp
realm/realm-library/src/main/java/io/realm/internal/ObjectServerFacade.java
realm/realm-library/src/main/java/io/realm/internal/OsRealmConfig.java
realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java
realm/realm-library/src/objectServer/java/io/realm/internal/SyncObjectServerFacade.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/BaseIntegrationTest.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SSLConfigurationTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncSessionTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProgressListenerTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/suite/IntegrationTestSuite.java

This PR exposes the SyncSessionStopPolicy in SyncConfiguration.
This will hopefully help combat the test assertions we are seeing with active sessions being present when a test ends. This is especially a problem in the PermissionManager tests that rely on internal Realms.
Only downside is that `SyncConfiguration.getSessionStopPolicy()` had to be made public. I put big fat warnings there though, so hopefully, it is okay?

Expose SyncSessionStopPolicy in SyncConfiguration

---

realm/realm-library/src/androidTest/java/io/realm/DynamicRealmObjectTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java
realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp
realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java
realm/realm-library/src/main/java/io/realm/RealmList.java
realm/realm-library/src/main/java/io/realm/internal/CheckedRow.java
realm/realm-library/src/main/java/io/realm/internal/InvalidRow.java
realm/realm-library/src/main/java/io/realm/internal/PendingRow.java
realm/realm-library/src/main/java/io/realm/internal/Row.java
realm/realm-library/src/main/java/io/realm/internal/UncheckedRow.java

Part of #5031
This PR adds support for primitive arrays in DynamicRealmObject
TODO

Array of primitives: DynamicRealm support

---

CHANGELOG.md
realm-annotations/src/main/java/io/realm/annotations/Beta.java
realm-annotations/src/main/java/io/realm/annotations/Ignore.java
realm-annotations/src/main/java/io/realm/annotations/Index.java
realm-annotations/src/main/java/io/realm/annotations/LinkingObjects.java
realm-annotations/src/main/java/io/realm/annotations/PrimaryKey.java
realm-annotations/src/main/java/io/realm/annotations/RealmClass.java
realm-annotations/src/main/java/io/realm/annotations/Required.java

Fixes #5344 
Thinking about this, we actually also need to keep these if we at some point support inheritance for model classes as the superclass might exist in another jar file. But for now, the primary driver is giving other library developers better tools for interacting with Realm.
The size increase of this in peoples apps should be minimal.
@Zhuinden does this fix your issue?

Keep annotations at runtime

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java
realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
realm/realm-library/src/androidTest/java/io/realm/LinkingObjectsManagedTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/OsListTests.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmMigrationTests.java
realm/realm-library/src/main/cpp/io_realm_internal_OsObjectSchemaInfo.cpp
realm/realm-library/src/main/java/io/realm/internal/OsObjectSchemaInfo.java
realm/realm-library/src/main/java/io/realm/internal/Property.java

This PR fixes some of the issues found in #5391
**3.7.2 - Nexus 6P**
1445
1397
1345
1350
1359
Avg: 1379
**4.0.0-SNAPSHOT with proxy class fixes**
1129
1067
1054
973
1030
Avg: 1051
Savings ~25%
**4.0.0-SNAPSHOT with proxy/mediator fixes**
1115
974
939
937
950
Avg: 983
Savings ~ 29%
**4.0.0-SNAPSHOT with no-alloc/proxy/mediator fixes**
988
944
966
959
997
Avg: 971
Savings ~ 30%
1 second to open a Realm still feels like too much though, but this was just low hanging fruits.

Fix some performance issues when initializing the Schema 

---

realm/realm-library/src/main/cpp/CMakeLists.txt
realm/realm-library/src/syncIntegrationTest/java/io/realm/SSLConfigurationTests.java
tools/sync_test_server/ros-testing-server.js

- Some features were missing which caused ssl tests failures.
See https://github.com/realm/openssl-android/pull/2
Linking with pre-build openssl 1.0.2k-1.
- Use a new Realm instead of using deleteRealm()

Enable SSL integration tests

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java

To disable treating kotlin non-null types as @Required.
From v3.6.0, all the kotlin RealmModel's non-null field will be set as
required in the schema. However it is a breaking change for the kotlin
project which has a Realm file created before 3.6.0.
To disable this behaviour introduced in 3.6.0, add below things to the
project's build.gradle:
kapt {
arguments {
arg("realm.ignoreKotlinNullability", true)
}
}
Close #5412

Add realm.ignoreKotlinNullability

---

realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProgressListenerTests.java

Need fix https://github.com/realm/realm-sync/issues/1770

Ignore downloadProgressListener_indefinitely

---

CHANGELOG.md
realm/realm-library/src/objectServer/java/io/realm/internal/network/OkHttpAuthenticationServer.java

Otherwise integration tests would fail when setting the network type to
GSM on emulator.

Increase http timeout

---

realm/realm-library/src/syncIntegrationTest/java/io/realm/PermissionManagerTests.java

Adding temporary fix for unit tests to prevent CI from failing almost consistently.

Enable work-around for failing permission tests

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/Constants.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java
realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
realm/realm-library/src/androidTest/java/io/realm/internal/PrimaryKeyTests.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmSchema.java
realm/realm-library/src/main/java/io/realm/internal/ColumnIndices.java
realm/realm-library/src/main/java/io/realm/internal/RealmProxyMediator.java
realm/realm-library/src/main/java/io/realm/internal/Table.java
realm/realm-library/src/main/java/io/realm/internal/modules/CompositeMediator.java
realm/realm-library/src/main/java/io/realm/internal/modules/FilterableMediator.java

Prefix "class_" should be hide from java layer and handled in Object
Store. Try to that direction step by step.
Close #5455

Remove depreacted RealmProxyMediator.getTableName

---

CHANGELOG.md
realm/realm-library/src/objectServer/java/io/realm/ErrorCode.java
realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
realm/realm-library/src/objectServer/java/io/realm/internal/network/ExponentialBackoffTask.java

fixes https://github.com/realm/realm-java/issues/5403 now we should retry when encountering any `IOException` error

fix SocketTimeout

---

examples/secureTokenAndroidKeyStore/src/main/java/io/realm/examples/securetokenandroidkeystore/MainActivity.java

monkey is not passing for `secureTokenAndroidKeyStore`
```
E/AndroidRuntime(11515): Process: io.realm.examples.securetokenandroidkeystore, PID: 11515
E/AndroidRuntime(11515): java.lang.RuntimeException: Unable to start activity ComponentInfo{io.realm.examples.securetokenandroidkeystore/io.realm.examples.securetokenandroidkeystore.MainActivity}: java.lang.IllegalArgumentException: User not authenticated or authentication expired.
E/AndroidRuntime(11515): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime(11515): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime(11515): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime(11515): 	at …
```

fix secureTokenAndroidKeyStore example to pass monkey test

---

realm/realm-library/src/syncIntegrationTest/java/io/realm/BaseIntegrationTest.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/IsolatedIntegrationTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/StandardIntegrationTest.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/HttpUtils.java
tools/sync_test_server/ros-testing-server.js

If startRealmObjectServer was called twice without stop in between,
syncServerChildProcess will be overwritten by a terminated process since
the 2nd call of creating sync server will fail and set the syncServerChildProcess.
This would make the stopRealmObjectServer get stuck forever.
In practice, we need to make sure the server has been stopped before
start it. So just treat the "start" as a "restart" command which will
stop the sync server if needed.
Thus, no need to stop in tear down functions in java side anymore.

Fix a socket timeout issue with test server

---

build.gradle
examples/build.gradle
gradle-plugin/build.gradle
library-benchmarks/build.gradle
realm-annotations/build.gradle
realm-transformer/build.gradle
realm/build.gradle
tools/update_gradle_wrapper.sh

No need to edit `gradle-wrapper.properties` after generating the file.

Specify distributionType in wrapper task

---

CHANGELOG.md
realm-transformer/build.gradle
realm-transformer/src/main/groovy/io/realm/transformer/ManagedClassPool.groovy
realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy

Fixes #5521 
I don't have a Windows machine to verify this on, but by doing code review it does appear that file handlers are being leaked. Unfortunately one of the leaks are inside JavaAssist, so I reported that upstream while implementing a workaround in our end for the time being.

Fix leaking file handlers.

---

Jenkinsfile

The _logcat_ is collected on CI but only archived if the tests fail.
sometimes the CI fails with `Expected X tests, received Y` ([example](https://ci.realm.io/job/realm/job/realm-java/job/PR-5511/21/consoleFull)) which doesn't provide the _logcat_ to investigate what happened. This PR allow archive  the _logcat_ regardless of the test

CI fails without exporting the logcat.zip

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/OrderedCollectionChangeSetTests.java
realm/realm-library/src/main/java/io/realm/OrderedCollectionChangeSet.java
realm/realm-library/src/main/java/io/realm/RealmList.java
realm/realm-library/src/main/java/io/realm/internal/OsCollectionChangeSet.java

- The notification token for RealmList<RealmModel> will be added to the
underlying OsList instead of the OsResults created from the list. This
will have a different behavior for a corner case,
see https://github.com/realm/realm-object-store/pull/602 . Thus the
test cases needs to be modified accordingly.
- This would be the precondition of using
https://github.com/realm/realm-object-store/pull/601
- Add toString() for OrderedCollectionChangeSet.

Added notification to OsList instead of OsResults

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/OrderedRealmCollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/internal/OsResultsTests.java
realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp
realm/realm-library/src/main/java/io/realm/RealmList.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java
realm/realm-library/src/main/java/io/realm/RealmResults.java
realm/realm-library/src/main/java/io/realm/internal/OsResults.java
realm/realm-library/src/main/java/io/realm/internal/OsSharedRealm.java
realm/realm-library/src/main/java/io/realm/internal/PendingRow.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncSessionTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/Constants.java

- OsResults.load() actually does evaluate queries if needed now by using
newly exposed OS method Results.evaluate_query_if_needed(). So the
Results's mode will be changed to TABLEVIEW from QUERY. This matches
the old async query behaviour and solved the performance issues when
the query results are huge, the size() method took unnecessary long
time even the Results accessor will be called at the next line.
close #5328 close #5387
- Update Object Store to 3eb19c014fdf .
- Refactor the APIs for creating OsResults.

Evaluate queries immediately for sync queries

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp
realm/realm-library/src/main/java/io/realm/internal/OsSharedRealm.java

Every temp OsSharedRealm created during construction for the callbacks
have to be closed before the exception throws to users.
close #5570

Life cycle of temp OsSharedRealm in callbacks

---

tools/sync_test_server/ros-testing-server.js

Health checking without waiting is too frequent. Use 0.5 second as the
interval between every attempt.
NOTE: CI failure caused by this usually cannot be seen the exact test
case in the gradle log. But it will give you something like:
"Tests on Nexus 5X - 6.0 failed: Test run failed to complete. Expected
3762 tests, received 3"

Fix CI failure caused by ROS docker

---

Jenkinsfile
gradle-plugin/src/test/groovy/io/realm/gradle/PluginTest.groovy

The Gradle plugin tests are not part of the CI checks, so for instance `jitpack` dependency was removed in https://github.com/realm/realm-java/commit/d00ddcaa4a2ab7d86616b5c01fcd28df077ceeba#diff-fbc37097ca151e18a6db623e59ebdba8 which should break the tests.

Fixing Plugin Test

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/java/io/realm/SessionTests.java
realm/realm-library/src/objectServer/java/io/realm/ErrorCode.java

The ObjectStore is now reportings unrecognized sync error to the binding https://github.com/realm/realm-object-store/commit/d36a7b603c256b9df5e9b3acc4645c770d630a31
Previously `ErrorCode#fromInt` was throwing an exception when it can't map the error to the known ones. This PR fixed this behaviour by logging a warning instead, since the Sync client may report operating system errors ex https://stackoverflow.com/questions/48217332/realm-sync-not-working-after-reconnecting-to-the-internet

fixes unknown error code

---

realm-annotations/src/main/java/io/realm/annotations/Required.java

It caused confusion like:
https://stackoverflow.com/questions/47940219/realmmigrationneededexception-when-adding-realmlistint-kotlin

javadoc for Required annotation

---

CHANGELOG.md
realm-transformer/build.gradle

We have a [reproducible](https://github.com/realm/realm-java/issues/5641#issuecomment-358617948) crash at runtime (`ClassNotFoundException`)  when a certain setup uses Realm and SLF4J https://github.com/realm/realm-java/issues/5641. 
Downgrading to Javassist `3_21_0_ga` solved the issue, still, need to investigate what changed between https://github.com/jboss-javassist/javassist/compare/rel_3_21_0_ga...rel_3_22_0_ga that causes the issue and why

downgrade javassist

---

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.java
realm/realm-annotations-processor/src/test/resources/io/realm/AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/NullTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/RealmDefaultModuleMediator.java
realm/realm-annotations-processor/src/test/resources/io/realm/SimpleRealmProxy.java
realm/realm-library/src/main/java/io/realm/internal/RealmProxyMediator.java
realm/realm-library/src/main/java/io/realm/internal/modules/CompositeMediator.java
realm/realm-library/src/main/java/io/realm/internal/modules/FilterableMediator.java

These are no longer used since we moved to the Object Store schema concept. I found this while working on #5280

Remove getFieldNames from proxy classes

---

CHANGELOG.md
realm/realm-library/src/objectServer/java/io/realm/SyncSession.java

- There was an issue with the `onGoingAccessTokenQuery` logic that causes the call to obtain an `access_token` ignored if previously an attempt was made offline.
- Removed session network listener in `SyncSession` since it's redundant with the `SyncManager ` one

Fixes #5677

---

examples/moduleExample/app/src/main/java/io/realm/examples/appmodules/model/Pig.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/ModuleMetaData.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProcessor.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/Utils.java
realm/realm-annotations-processor/src/test/resources/io/realm/some_test_AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/some_test_BooleansRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/some_test_NamePolicyMixedClassSettingsRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/some_test_NamePolicyModuleDefaultsRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/some_test_NullTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/some_test_SimpleRealmProxy.java

With the support for changing the internal names, we can no longer infer the name from the reference type itself. This turned out to cause problems if the referenced type was in another compilation unit. This PR splits out the fix from https://github.com/realm/realm-java/pull/5729 as the functionality was originally merged to master (but has not yet been released).
Not Changelog as the functionality has not yet been released.
The functionality is being tested in the `moduleExample` where the app now has a reference to a library module class.

Support types in other compilation units

---

realm/kotlin-extensions/src/main/kotlin/io/realm/kotlin/RealmQueryExtensions.kt

In Kotlin, Non-nullable types are a subclass of nullable types, so this is a cleaner implementation.

Non-nullable types are a subclass of nullable types

---

realm/realm-library/src/androidTestObjectServer/java/io/realm/util/SyncTestUtils.java
realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/internal/Table.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/PartialSyncTests.java

Fixes https://github.com/realm/realm-java/issues/5758
Partial Sync does not support the `clearTable` instruction. This fixes it. Due to performance concerns, this code path is only triggered for partially synchronized Realms.

Support clearing data using Partial Sync

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/java/io/realm/SessionTests.java
realm/realm-library/src/objectServer/java/io/realm/SyncManager.java
realm/realm-library/src/objectServer/java/io/realm/SyncSession.java
realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
realm/realm-library/src/objectServer/java/io/realm/internal/SyncObjectServerFacade.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncSessionTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncedRealmTests.java

Currently when the user login, the Object Store will try to revive its inactive sessions
(stored previously after a logout). This will cause the OS to call `bindSession` to obtain an access token, however since the Realm might not be open yet, the `wrapObjectStoreSessionIfRequired`will not be invoked to wrap the OS store session with the Java session, which causes the Sync client to not resume syncing.

logout logging not resuming sync

---

tools/sync_test_server/Dockerfile

CI failure which may be related to the latest `winston` dependency. Now specifying an exact version when building ROS for integration test

Using a specific version of winston library

---

examples/moduleExample/app/src/main/java/io/realm/examples/appmodules/ModulesExampleActivity.java
examples/moduleExample/app/src/main/java/io/realm/examples/appmodules/model/Pig.java

This fixes the app module example.
It, unfortunately, does this by reverting the code that tests that app modules can link to library module model classes. The reason for this is that testing this is impossible without seriously complicating the current example (e.g. just using the default configuration is no longer possible).
Creating another example just for this seems a bit much and the chance of the functionality breaking is probably low.
I verified that it worked manually before removing the code, by using the following default config `RealmConfiguration defaultConfig = new RealmConfiguration.Builder().modules(Realm.getDefaultModule(), new DomesticAnimalsModule()).build();`
/cc @nhachicha

Fix module example

---

CHANGELOG.md
examples/objectServerExample/src/main/java/io/realm/examples/objectserver/CounterActivity.java
examples/objectServerExample/src/main/java/io/realm/examples/objectserver/LoginActivity.java
examples/secureTokenAndroidKeyStore/src/main/java/io/realm/examples/securetokenandroidkeystore/MainActivity.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/AuthenticateRequestTests.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java
realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java
realm/realm-library/src/objectServer/java/io/realm/SyncCredentials.java
realm/realm-library/src/objectServer/java/io/realm/SyncManager.java
realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SSLConfigurationTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncSessionTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncedRealmIntegrationTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/EncryptedSynchronizedRealmTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ObjectLevelPermissionIntegrationTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProcessCommitTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProgressListenerTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/UserFactory.java

Align Sync API's with Cocoa.
Reasoning:
> “Log in” is a phrasal verb, while “login” is a noun. Given that the method in question performs an action, the verb is the correct choice.

Align Sync API's with Cocoa

---

CHANGELOG.md
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncedRealmTests.java

- Fixed Changelog entries
- Workaround deleteRealm throwing in `loginLogoutResumeSyncing` sometimes 
(due to https://github.com/realm/realm-java/issues/5416)

deleteRealm throwing in loginLogoutResumeSyncing

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java
realm/realm-library/src/main/java/io/realm/RealmObject.java

RealmObject.isValid now returns the correct value for the null argument.

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java
realm/realm-library/src/main/java/io/realm/RealmList.java

Fixes #5860 
Apparently, a brain fart was made in the unit test for this resulting in a wrong implementation compared to the managed list. Tests have been modified to make sure they test the same behaviour in both managed and unmanaged mode.

Fix RealmList.move() for unmanaged lists

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/java/io/realm/ObjectLevelPermissionsTest.java
realm/realm-library/src/main/java/io/realm/sync/permissions/PermissionUser.java

Sync is adding a private per-user role in realm/realm-sync#2068. We'll need to update our schema to accommodate.

Expose the per-user private role

---

Jenkinsfile

10 steps back and 11 forward.
After a lot of detours I discovered that Zaki added a small optimization which meant that if `PbuildTargetABIs` was set to to the empty string, all ABI's where being filtered, resulting in only metrics for the Java code being sent to the server (which also explains why only a a few hundred kb was being reported for the full AAR).
To fix this, we now only set `PbuildTargetABIs` if it has a value.

Fix AAR size not being reported correctly

---

tools/unroll_stacktrace.sh

This script is a helper script when unrolling stacktraces provided by users making the process a lot less manual, as it is especially tedious to find and download the unstripped versions of Realm.
Example of usage:
```
=> sh unroll_stacktrace.sh base 3.5.0 armeabi-v7a ./dump.txt
Unrolling /Users/cm/Realm/realm-java/tools/./dump.txt from Realm Java 3.5.0 (base) using ABI armeabi-v7a
********** Crash dump: **********
Build fingerprint: 'google/sailfish/sailfish:7.1.2/NJH47F/4146041:user/release-keys'
pid: 28302, tid: 28302, name: com.anghami  >>> com.anghami <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xae47ffff
Stack frame #00 pc 00018acc  /system/lib/libc.so (memmove+444)
Stack frame #01 pc 0012fc8d  /data/app/com.anghami-1/lib/arm/librealm-jni.so: Routine …
```

Add script to help unrolling crash reports

---

CHANGELOG.md
realm/kotlin-extensions/src/main/kotlin/io/realm/kotlin/RealmQueryExtensions.kt
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp
realm/realm-library/src/main/java/io/realm/RealmQuery.java
realm/realm-library/src/main/java/io/realm/internal/TableQuery.java

Closes #4011
This PR will make our `in()` operator mirror Cocoas equivalent where parsing in no values and treat it as "always false".
At the same time I added support for two new predicates: `alwaysTrue()` and `alwaysFalse()`
`alwaysFalse()` is used by `in()`. `alwaysTrue()` isn't terrible useful outside generic code going down a branch in a 'or()` expression, but it also provides symmetri. See https://github.com/realm/realm-java/issues/3238#issue-168877473
Naming the operators wasn't that easy, but in the end, I opted for the naming also used in Guava https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/base/Predicates.html
It seems more descriptive in our query language than both `.trueExpression()` or `.truePredicate()`

Support empty input to in and alwaysTrue and alwaysFalse

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/java/io/realm/ObjectLevelPermissionsTest.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncConfigurationTests.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncManagerTests.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java
realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncedRealmTests.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/objectServer/java/io/realm/PermissionManager.java
realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java
realm/realm-library/src/objectServer/java/io/realm/internal/SyncObjectServerFacade.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SSLConfigurationTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncSessionTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncedRealmIntegrationTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/EncryptedSynchronizedRealmTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ObjectLevelPermissionIntegrationTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/PartialSyncTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProcessCommitTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProgressListenerTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/QueryBasedSyncTests.java

In 6.0 Partial Sync will become the default mode instead of Full Synchronization.
Partial Sync has only been an internal working name for this feature, but the public name will be "Query-based Synchronization" or "Query-based Sync". This PR makes the changes to support that.
Most of the changes are in the unit tests as we can continue to use the old `isPartial` parameter internally. However, there is some value in also refactoring the internal API's just to avoid confusion (like with Backlinks/LinkingObjects). Thoughts @nhachicha ?

Query-based sync as the default mode

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java
realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp
realm/realm-library/src/main/java/io/realm/internal/OsSharedRealm.java
realm/realm-library/src/main/java/io/realm/internal/Table.java

Closes #5899 
Root cause:
When changing nullability status on a field, we actually do it by creating a new column, move all data there and then delete the old column. This is a problem in the context of primary keys for the following reason:
Use case: Change primary key int column from nullable to required.
1) create tmp int column: All rows will have the 0 value default value (which actually violates the pk constraint)
2) Start moving values from the old column to the new row by row. This is done using a special `set_unique` instruction. If 0 was present in the old column, we will now do a `set_unique_int(col, row, 0)`, but since all rows have the 0 value, the result is that the rows are collapsed causing data loss.
Solution:
Since changing nullability is only supported for non-sync …

Migration that changes primary key deletes rows

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java
realm/realm-library/src/main/java/io/realm/OrderedRealmCollectionImpl.java
realm/realm-library/src/main/java/io/realm/RealmList.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java

Closes #5997 
We already had `RealmObject.getRealm()` this adds the same methods to `RealmList`, `RealmResults`, `RealmQuery` and `OrderedRealmCollectionSnapshot`.

Add getRealm methods

---

examples/build.gradle

Before this PR monkey could send system events which regularly caused test failures not related to Realm, e.g. if the monkey switched to the guest account.
With this change, all events should be in-app. It might cause a few subtle errors to never be exposed, but any such errors would be related to us implementing an example project wrong (e.g. with respect to the lifecycle) and not to Realm as such.

Prevent monkey from using system events

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/ImmutableRealmSchema.java
realm/realm-library/src/main/java/io/realm/MutableRealmSchema.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmSchema.java

Closes #5745
This PR fixes `Realm.deleteAll()` and `Realm.isEmpty()` so they now respect the defined schema. 
This is important if the schema is only a subset of the actual tables found in the Realm.
This means that `deleteAll()` will only delete the schema defined and `isEmpty()` will only return the result based on the defined schema as well.
TODO:

Fix Realm.deleteAll() and Realm.isEmpty()

---

realm-transformer/src/main/groovy/io/realm/transformer/GroovyUtil.groovy
realm-transformer/src/main/kotlin/io/realm/transformer/RealmTransformer.kt
realm-transformer/src/main/kotlin/io/realm/transformer/build/BuildTemplate.kt

This also fixed an invalid cast that wasn't detected before because the code path was never touched.

Fix analytics not being sent

---

CHANGELOG.md
realm-transformer/src/main/java/io/realm/transformer/Utils.java
realm-transformer/src/main/kotlin/io/realm/transformer/RealmTransformer.kt
realm-transformer/src/main/kotlin/io/realm/transformer/build/BuildTemplate.kt
realm-transformer/src/main/kotlin/io/realm/transformer/ext/CtClassExt.kt
realm-transformer/src/main/kotlin/io/realm/transformer/ext/ProjectExt.kt

Closes #6082 
Converts the util functions to Kotlin and added extra crash safety when sending analytics (basically, we should never crash no matter what goes wrong). Now all exceptions are just silently logged to the debug log.

Fix nullpointer when using RealmTransformer

---

examples/objectServerExample/build.gradle
examples/objectServerExample/src/main/java/io/realm/examples/objectserver/CounterActivity.java
examples/objectServerExample/src/main/java/io/realm/examples/objectserver/LoginActivity.java

Ran into this while testing https://github.com/realm/realm-java/pull/6110
Previously the example depended on a local version of ROS running, but testing using Cloud is much simpler, so the example was modified to work when you just copy the instance URL from the web UI.
The actual demo actually also didn't work correctly since it used `findFirstAsync()` instead of `findAllAsync()` meaning that no subscription was ever created.

Make ObjectServerExample more accessible

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/java/io/realm/SessionTests.java
realm/realm-library/src/main/cpp/io_realm_SyncSession.cpp
realm/realm-library/src/objectServer/java/io/realm/SyncSession.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncSessionTests.java

Closes: https://github.com/realm/realm-java-private/issues/235
This PR adds support for manually stopping and starting a session. 
The session lifecycle is still tied to the Realm though. Changing that will be a major refactor of the SyncSession in Object Store.
This approach just uses existing methods on the underlying session that already have the semantics we desire. Calling `log_out()` is probably a bit heavy-handed since it will also clear the access token, but caching the token in ObjectStore didn't seem worth it as we probably need to do a full refactor of the Session anyway. 
This means that using this approach there is currently the overhead of an extra HTTP request when calling `stop/start()`.
**TODO:**

Added support for stopping and starting a session

---

realm/realm-library/src/objectServer/java/io/realm/SyncManager.java
realm/realm-library/src/objectServer/java/io/realm/internal/network/AuthenticationServer.java
realm/realm-library/src/objectServer/java/io/realm/internal/network/OkHttpAuthenticationServer.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/BaseIntegrationTest.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/AuthTests.java
realm/realm-library/src/syncTestUtils/java/io/realm/SyncTestUtils.java
realm/realm-library/src/syncTestUtils/java/io/realm/objectserver/utils/UserFactory.java
tools/sync_test_server/integration-test-command-server.js

Fixes #6138 
Fixes #6137 
This PR fixes various lifecycle issues with tests introduced with #6131 
It also includes a workaround so we can correctly store ros-logs. However the logs are only pulled once ROS is shut down, so I suspect in some cases we might not get logs. We should continue to investigate ways of seeing the logs in real time.

Fix various lifecycle issues with tests

---

realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/internal/ObjectServerFacade.java
realm/realm-library/src/objectServer/java/io/realm/internal/SyncObjectServerFacade.java

The library-transformer strips all methods marked `@ObjectServer`. Unfortunately, it seems it also strips similar named methods even though they don't have this annotation. In this case `ObjectServerFacade.init(Context, String)`. Renaming the internal method is the quickest way to make 5.8.0 ready for release.
I'll be making a fix for the behaviour after the release.

Transformer strips similar named methods

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java
realm/realm-annotations-processor/src/main/java/io/realm/processor/TypeMirrors.java
realm/realm-annotations-processor/src/main/resources/META-INF/gradle/incremental.annotation.processors

Closes #5906 
I don't think there is any way to add automated tests for this so I did smoke tests doing the following:

Add support for incremental annotation processors

---

CHANGELOG.md
realm/realm-library/src/objectServer/java/io/realm/PermissionManager.java
realm/realm-library/src/objectServer/java/io/realm/SyncManager.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/PermissionManagerTests.java

Closes #6492
Adds functionality for partly working around https://github.com/realm/realm-java-private/issues/259
Before this PR, the `PermissionManager` held on to any error reported, even intermittent network errors. This caused it to stop working once such an error was encountered. 
With this PR, all errors known to be temporary are just ignored, since the end user cannot do anything besides retrying closing/opening the PermissionManager again. Internally we are already retrying sending data which is much more efficient, so no reason to put that burden on the end user.
With this change, only non-recoverable errors should be reported to end users.

PermissionManager should ignore intermittent errors

---

README.md
realm/realm-library/build.gradle
realm/realm-library/src/main/cpp/CMake/RealmCore.cmake
realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp

Closes https://github.com/realm/realm-java/issues/6444
Fixed a few bugs for building with a local copy of Realm and added instructions on how to do it practice. This will enable better debugging for native code where we should now be able to better follow code paths that ends up in Core.
We also now accept both relative and absolute paths to Realm Core, before only absolute paths really worked.

Add instructions for building Realm from a local source

---

CHANGELOG.md
realm-transformer/build.gradle
realm-transformer/src/main/kotlin/io/realm/transformer/RealmTransformer.kt
realm-transformer/src/main/kotlin/io/realm/transformer/build/BuildTemplate.kt
realm-transformer/src/main/kotlin/io/realm/transformer/build/FullBuild.kt
realm-transformer/src/main/kotlin/io/realm/transformer/build/IncrementalBuild.kt

Closes https://github.com/realm/realm-java/issues/6531
Test by compilling and running all all examples in the repo with `3.6.0-alpha05` (latest release). Before this PR some of the examples would crash at runtime, now they all run.
Reason being that in 3.6.0 the R file is now generated inside a seperate JAR file that needs to be copied as well.

Correctly copy JAR files in the Realm transformer

---

CHANGELOG.md
dependencies.list
realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp
realm/realm-library/src/main/java/io/realm/internal/OsRealmConfig.java

See https://jira.mongodb.org/browse/HELP-10664. Needs realm/realm-object-store#816 and realm/realm-sync#3067.

Add support for configuring sync with the system proxy

---

CHANGELOG.md
dependencies.list
realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmTests.java
realm/realm-library/src/testUtils/java/io/realm/entities/AllTypes.java

Closes #5668
Closes #6093
Closes #6152 
Closes #6239
Closes #6257
Closes #6505
Closes #6362
Closes #6634
Closes #6525
TODO

Upgrade sync + fix encryption race

---

CHANGELOG.md
realm/realm-library/proguard-rules-consumer-common.pro

Closes https://github.com/realm/realm-java/issues/6449
This was test manually by upgrading Gradle Build Tools to 3.4.1, installing the `moduleExample` in release mode and running the app. Before this fix, the app would crash on startup. After, it works.

Fix Proguard setup for release builds using R8

---

gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy

Using the Kotlin multiplatform plugin instead of the "kotlin-android" one currently, lead to the kapt dependencies not being applied.

Realm plugin: consider kotlin-multiplatform plugin

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmObjectSchemaTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/CyclicType.java
realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp
realm/realm-library/src/main/java/io/realm/ImmutableRealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/MutableRealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/internal/CheckedRow.java
realm/realm-library/src/main/java/io/realm/internal/OsResults.java

Closes #6657
Also add support for creating `OsResults` directly from a table, which is much faster than running a query for all objects in a table.

Fix transform crashing when you delete transformed objects

---

CHANGELOG.md
realm-transformer/src/main/kotlin/io/realm/transformer/RealmTransformer.kt

Closes #6691 
This PR disables anonymous analytics when Gradle is invoked with the `--offline` parameter. This will speed the build up by 6 seconds, since we are currently waiting for the network layer to throw a timeout exception  (timeouts configured by us in `RealmAnalytics.java`).
Tested manually.

Better support for Gradle offline mode

---

dependencies.list
realm/kotlin-extensions/build.gradle
realm/realm-library/src/main/cpp/io_realm_RealmFileUserStore.cpp
realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp
realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp
realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp
realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp
realm/realm-library/src/main/java/io/realm/internal/OsSharedRealm.java

Upgrade to latest Sync release + ObjectStore.
Unclear why Dokka suddenly starts to fail, so it is temporarily disabled. A task to re-enable it has been added to https://github.com/realm/realm-java/pull/6756

Upgrade to latest Sync alpha.4 release + ObjectStore

---

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.kt
realm/realm-annotations-processor/src/test/resources/io/realm/some_test_AllTypesRealmProxy.java
realm/realm-annotations-processor/src/test/resources/io/realm/some_test_NullTypesRealmProxy.java

Add support for RealmProxy#toString() to print length information for binary field

---

CHANGELOG.md
Dockerfile
dependencies.list
gradle-plugin/src/test/groovy/io/realm/gradle/PluginTest.groovy
realm/realm-library/src/androidTest/java/io/realm/RxJavaTests.java
realm/realm-library/src/main/java/io/realm/rx/RealmObservableFactory.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ObjectLevelPermissionIntegrationTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/ProgressListenerTests.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver/utils/HttpUtils.java
tools/sync_test_server/ros/tsconfig.json

Closes https://github.com/realm/realm-java/issues/6764
- This should remove the last known bug for Core 6.
- Cleaned up the changelog preparing for release.
- Also found the bug with our RxJava tests. It turned out to reveal a true issue. Apparently, the async queries are so fast on my emulator and device that it resolved correctly before the subscription triggered, but on CI, we attempted to subscribe to a still-pending object which failed.

Fix ProgressListeners for Core 6

---

Jenkinsfile
dependencies.list
tools/sync_test_server/setup_mongodb_realm.sh
tools/sync_test_server/start_server.sh
tools/sync_test_server/stop_server.sh

Switches the Registry from which we download the Stitch images from AWS to Github. This removes the requirement of having access to our secret AWS credentials.
It also now correctly stores any relevant logs: LogCat, Command Server, MongoDB Realm and MongoDB itself.
After this PR has been merged. You need to create a GitHub access token to run the integration tests. There is a HOWTO in the `start_server.sh` file.

Switch to using Github Docker Registry

---

realm/build.gradle
realm/realm-library/build.gradle

Fixes: https://github.com/realm/realm-java/issues/6799
Reverted to minSdkVersion 16
Added support for multidexing - can't use the latest version though, TODO added with explanation in that regard

Add support for Multidex to AndroidTests

---

Jenkinsfile

We should start releasing SNAPSHOT builds from the v10 branch so other teams can more easily consume the merged Stitch/Realm SDK.
This PR changes CI so the `v10` branch is now treated like our other "major" branches, i.e. we run all tests for all architectures on it, and SNAPSHOTs are being released.
The version is `10.0.0-SNAPSHOT` and can be found here once deployed: http://oss.jfrog.org/oss-snapshot-local/io/realm
Howto for using SNAPSHOTs are here: https://github.com/realm/realm-java/blob/master/README.md#using-snapshots

Release SNAPSHOT builds from v10

---

realm/kotlin-extensions/build.gradle

@nhachicha Not entirely sure how this happened as your datatype PR was green. Anyway. This should fix the build failure on `v10`

Fix Kotlin Extensions Base tests

---

Jenkinsfile
realm/realm-library/build.gradle
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/RealmFunctionsTest.kt
realm/realm-library/src/main/cpp/CMakeLists.txt
realm/realm-library/src/main/cpp/io_realm_RealmFunctions.cpp
realm/realm-library/src/main/cpp/util_sync.cpp
realm/realm-library/src/main/cpp/util_sync.hpp
realm/realm-library/src/objectServer/java/io/realm/RealmFunctions.java
realm/realm-library/src/objectServer/java/io/realm/internal/jni/JniBsonProtocol.java
realm/realm-library/src/objectServer/java/io/realm/internal/jni/OSJNIBsonProtocol.java
realm/realm-library/src/objectServer/java/io/realm/internal/util/BsonConverter.java
realm/realm-library/src/testObjectServer/kotlin/io/realm/BsonTest.kt

Passing BSON to JNI by wrapping it in a document with key `value`. 
Java side: `OSJNIBsonProtocol`:
- `public static String encode(BsonValue bsonValue)`
- `public static BsonValue decode(String string)`
JNI side:
- `realm::bson::Bson jstring_to_bson(JNIEnv* env, jstring arg);`
- `jstring bson_to_jstring(JNIEnv* env, realm::bson::Bson bson);`
- 
Conversion does currently not handle the below types as mapping from primitive types is not obvious: 
```
BsonType.DOCUMENT,
BsonType.UNDEFINED,
BsonType.DATE_TIME,
BsonType.NULL,
BsonType.REGULAR_EXPRESSION,
BsonType.SYMBOL,
BsonType.DB_POINTER,
BsonType.JAVASCRIPT,
BsonType.JAVASCRIPT_WITH_SCOPE,
BsonType.TIMESTAMP,
BsonType.END_OF_DOCUMENT,
BsonType.MIN_KEY,
BsonType.MAX_KEY
```

JNI BSON Protocol

---

Jenkinsfile

This PR separates some changes discovered while working on https://github.com/realm/realm-java/pull/6822
- We accidentally still built all debug ABI's on PR's instead of only armeabi-v7a. (this should save quite some time)
- Quicker exit if the device is not available. Currently, we wait 1.5 hours before timing out the build which would block other builds because we held a resource lock.
- Fixing a bug when tearing down the build. If it was terminated early it would result in the wrong kind of error being reported.

Reduce build time

---

Jenkinsfile

This PR caches our Docker files in a remote location allowing all builds to take advantage of it. Also moves to build/preparing the docker images to a separate step so it is easier to track

Cache docker file and configure/create all docker images as a single step

---

dependencies.list
tools/sync_test_server/app_config/services/BackingDB/rules/test_data.SyncPerson.json

Updates the version of Stitch we use for Integration tests to latest (as of today) version.

Update Integration Test server to latest version

---

Jenkinsfile

Removing explicit references to Jenkins build nodes and use labels instead

Re-enabling all android CI build nodes

---

dependencies.list
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/KotlinSyncedRealmTests.kt
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/RealmUserTests.kt
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/entities/SyncPerson.kt
realm/realm-library/src/main/cpp/CMake/RealmCore.cmake
realm/realm-library/src/main/cpp/io_realm_RealmApp.cpp
realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp
realm/realm-library/src/main/cpp/io_realm_internal_objectstore_OsSyncUser.cpp
realm/realm-library/src/main/java/io/realm/internal/ObjectServerFacade.java
realm/realm-library/src/main/java/io/realm/internal/OsRealmConfig.java
realm/realm-library/src/objectServer/java/io/realm/RealmApp.java
realm/realm-library/src/objectServer/java/io/realm/RealmUser.java
realm/realm-library/src/objectServer/java/io/realm/internal/SyncObjectServerFacade.java
realm/realm-library/src/objectServer/java/io/realm/internal/objectstore/OsSyncUser.java
tools/sync_test_server/app_config/services/BackingDB/rules/test_data.SyncPerson.json

The primary purpose of this PR was to just upgrade Sync and ObjectStore to latest versions, but resulted in doing a few more things:
* Sync upgraded to latest version (10.0.0-alpha.14)
* ObjectStore at latest commit
* Added support for DeviceID, which required some more metadata to be sent.
* Re-enabled roundtrip tests through MongoDB Realm
* Modified test schema so we now use the proper model lists (these were not supported initially)

Add support for Device Id and bump Sync/OS to latest version

---

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.kt
realm/realm-annotations-processor/src/test/resources/io/realm/some_test_EmbeddedClassSimpleParentRealmProxy.java
realm/realm-library/src/androidTest/kotlin/io/realm/EmbeddedObjectsTest.kt

This PR fixes a bug when using `copyToRealm` with objects that contains lists of embedded objects.
The bug manifested as all the elements in the list showing up as having no values.
What happened was that the values were correctly written and then wrongly overridden by the bug.

Fix copying lists of embedded objects

---

realm/build.gradle
realm/realm-library/build.gradle
realm/realm-library/src/main/java/io/realm/RealmResults.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/App.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/Credentials.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/User.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/functions/Functions.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/mongo/iterable/MongoCursor.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/mongo/iterable/MongoIterable.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/sync/Sync.java

* Enables JavaDoc again
* Fixes a number of formatting errors in the JavaDoc
*  Note. I'm disabling strict mode because I saw a lot of errors like this:
```
/Users/cm/Realm/realm-java/realm/realm-library/src/objectServer/java/io/realm/mongodb/auth/ApiKeyAuth.java:112: error: reference not found
* The key is enabled when created. It can be disabled by calling {@link #disableApiKey(ObjectId)}.
```
Even though the generated output created the correct link and you could jump to the class inside Android Studio.
This PR doesn't fix an issue with us linking to 3rd party API's like BSON
I'll create an issue tracking this.

Re-enable JavaDoc generation

---

CHANGELOG.md
realm/realm-library/src/main/cpp/java_class_global_def.hpp
realm/realm-library/src/main/cpp/java_network_transport.hpp

Fixes #6937 
The underlying problem is that if the first network request comes from the Sync Client C++ thread, it will attempt to load the JavaClass into the static variable. But the Sync thread is started from C++ and doesn't have access to the Java class loader (see https://developer.android.com/training/articles/perf-jni#native-libraries), so it will crash with class-not-found.
If any Java call managed to get here first, this would not crash and all subsequent calls would succeed.
The fixes move the class lookup to JNI_Onload and stores it in our `JavaClassGlobalDef` wrapper which is guaranteed to be called from Java.
Unfortunately, it isn't possible to create a unit test for this as the static variable is preserved across all unit tests, but the fix has been verified manually by:
1) …

Avoid crash if looking up NetworkTransport response class from C++ thread

---

realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/entities/DefaultSyncSchema.kt
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/entities/SyncAllTypes.kt
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/entities/SyncAllTypesWithFloat.kt
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/transport/OkHttpNetworkTransportTests.kt
realm/realm-library/src/syncIntegrationTest/kotlin/io/realm/SyncSessionTests.kt

Updates to SynsSessionTests including:
- Avoid crashing test app when `interruptedWaits` fails
- Eliminate `float` from `SyncAllTypes`-schema as it generate change sets that are rejected by the current sync implementation
- Add test case to track the failing `float` support

Update SyncSessionTests schema to avoid UPLOAD errors

---

realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/CredentialsTests.kt
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/admin/ServerAdmin.kt
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/push/PushTest.kt
realm/realm-library/src/main/cpp/io_realm_internal_objectstore_OsAppCredentials.cpp
realm/realm-library/src/main/cpp/io_realm_internal_objectstore_OsPush.cpp
realm/realm-library/src/objectServer/java/io/realm/internal/objectstore/OsAppCredentials.java
realm/realm-library/src/objectServer/java/io/realm/internal/objectstore/OsPush.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/Credentials.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/push/Push.java
tools/sync_test_server/app_config/auth_providers/custom-function.json
tools/sync_test_server/app_config/functions/testAuthFunc/config.json
tools/sync_test_server/app_config/functions/testAuthFunc/source.js
tools/sync_test_server/app_config/functions/void/config.json

Closes:
https://github.com/realm/realm-java/issues/6908
Added:
- custom function credentials
- server API key (just another flavour for the standard user API key - which was already implemented, but it's treated differently in the OS)
- modified custom function credentials so that they are generated using a Bson document instead of an array of objects - needed to map the function arguments correctly
- removed token from deregistering push notifications - this will be rendered moot once v10 is updated with the latest OS v10.

Add server API key and custom function credentials for user authentication

---

README.md

During the onboarding with Christian we realised that there is a way to prevents Gatekeeper to kill all NDK processes on OSX.
We have included a note for future references on how to disable and enable it.

Suggest users to disable gatekeeper when building realm on OSX

---

CHANGELOG.md
dependencies.list
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SyncedRealmTests.kt
realm/realm-library/src/syncTestUtils/kotlin/io/realm/mongodb/SyncTestUtils.kt

This PR bumps our test image to the latest version as well as pull in all the latest Object Store changes. This includes an important bug fix regarding starting Sync with an expired access token.

Upgrade to latest Server Docker image + Object Store 

---

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.kt

Seems like the FIXMEs are not relevant as we do not support mixing objects from different libraries into same model objects.

Remove irrelevant FIXMEs

---

CHANGELOG.md
dependencies.list
realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java

Closes https://github.com/realm/realm-java/issues/6875
Closes https://github.com/realm/realm-java/issues/6866
Upgrade Core which contains some fixes for both files being corrupted during a file upgrade and slow upgrade times on Android if the file contained String indexes.

Fix file upgrade bugs

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/internal/async/RealmAsyncTaskImpl.java
realm/realm-library/src/objectServer/java/io/realm/SyncManager.java
realm/realm-library/src/objectServer/java/io/realm/SyncSession.java
realm/realm-library/src/objectServer/java/io/realm/SyncUser.java
realm/realm-library/src/objectServer/java/io/realm/internal/async/ResetableRealmAsyncTask.java
realm/realm-library/src/objectServer/java/io/realm/internal/network/ExponentialBackoffTask.java
realm/realm-library/src/syncIntegrationTest/java/io/realm/SyncedRealmIntegrationTests.java

Backport https://github.com/realm/realm-java/pull/7019 to the 6.x releases, due to customers hitting this and upgrading right now is not an option.
CI might be a problem. Looking into it.

Backport fix to refreshing connections

---

dependencies.list
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/MongoClientTest.kt
realm/realm-library/src/main/cpp/io_realm_internal_objectstore_OsMongoCollection.cpp
realm/realm-library/src/syncIntegrationTest/kotlin/io/realm/EncryptedSynchronizedRealmTests.kt
realm/realm-library/src/syncIntegrationTest/kotlin/io/realm/SyncSessionTests.kt
tools/sync_test_server/start_server.sh

- Bumped server to the version that includes a fix for projections and sort - https://github.com/10gen/baas/pull/3022
- Rewrote tests for `findAndModify` methods with examples based on the online documentation.
- Fixed bug in JNI that returned a boolean as the upserted value instead of an objectId.
- Replaced `BsonObjectId` used as partition value in `EncryptedSynchronizedRealmTests` and `SyncSessionTests` and added "ignore" to `setEncryptionKey_shouldCrashIfKeyNotProvided` until https://github.com/realm/realm-java/issues/7028 is fixed.

Revisit MongoCollection tests for findOneAndModify operations

---

Jenkinsfile

Re-enables Slack notifications on broken branches. It also now tracks when a branch becomes healthy again.

Re-enable Slack notifications

---

build.gradle
realm/templates/README.md
realm/templates/redirect.html.template

One step closer to having a fully automated release...
It works by:
1) Uploading new docs to a version folder
2) Update the redirect found in `/java/latest` and `kotlin/latest`
Note, there is a also a redirect for the Kotlin docs since Dokka output a slightly annoying format where there only exist a `style.css` in the root and you have to go to a subfolder for the index.html.

Automate uploading docs to MongoDB Realm website

---

CHANGELOG.md
dependencies.list
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SyncConfigurationTests.kt
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SyncedRealmTests.kt
realm/realm-library/src/main/cpp/io_realm_mongodb_sync_SyncSession.cpp
realm/realm-library/src/objectServer/java/io/realm/internal/SyncObjectServerFacade.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/sync/Sync.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/sync/SyncConfiguration.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/sync/SyncSession.java
realm/realm-library/src/syncIntegrationTest/kotlin/io/realm/SyncSessionTests.kt
tools/sync_test_server/app_config/services/BackingDB/config.json

Closes https://github.com/realm/realm-java/issues/7022
Adds support for defining Null partition values. Note the unit test currently captures the server not supporting it, but we will reverse that as soon as it does.

Add support for the Null partition

---

examples/newsreaderExample/src/main/java/io/realm/examples/newsreader/model/network/NYTimesDataLoader.java
examples/newsreaderExample/src/main/java/io/realm/examples/newsreader/model/network/NYTimesService.java
examples/newsreaderExample/src/main/res/values/strings.xml

Updates NYTimes API version to v2. V1 is obsolete and V2 supports https protocol.
Closes #7045

Update newsreaderExample's NYTimes api version to v2

---

examples/mongoDbRealmExample/build.gradle
realm/realm-library/proguard-rules-consumer-common.pro
realm/realm-library/proguard-rules-consumer-objectServer.pro
realm/realm-library/src/objectServer/java/io/realm/internal/jni/OsJNIVoidResultCallback.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/AppException.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/ErrorCode.java

This PR protects ObjectId and Decimal128 BSON types in proguard.

Add rules for bson type references

---

dependencies.list
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/UserTests.kt
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SyncedRealmTests.kt
tools/sync_test_server/app_config/auth_providers/anon-user.json
tools/sync_test_server/app_config/auth_providers/api-key.json
tools/sync_test_server/app_config/auth_providers/custom-function.json
tools/sync_test_server/app_config/auth_providers/local-userpass.json
tools/sync_test_server/app_config/functions/authFunc/config.json
tools/sync_test_server/app_config/functions/authorizedOnly/config.json
tools/sync_test_server/app_config/functions/confirmFunc/config.json
tools/sync_test_server/app_config/functions/error/config.json
tools/sync_test_server/app_config/functions/firstArg/config.json
tools/sync_test_server/app_config/functions/null/config.json
tools/sync_test_server/app_config/functions/resetFunc/config.json
tools/sync_test_server/app_config/functions/sum/config.json
tools/sync_test_server/app_config/functions/testAuthFunc/config.json
tools/sync_test_server/app_config/functions/void/config.json
tools/sync_test_server/app_config/graphql/config.json
tools/sync_test_server/app_config/services/BackingDB/config.json
tools/sync_test_server/app_config/services/BackingDB/rules/test_data.SyncDog.json
tools/sync_test_server/app_config/services/BackingDB/rules/test_data.SyncPerson.json
tools/sync_test_server/app_config/services/BackingDB/rules/test_data.custom_user_data.json
tools/sync_test_server/app_config/services/BackingDB/rules/test_data.mongo_data.json
tools/sync_test_server/app_config/services/gcm/config.json
tools/sync_test_server/app_config/stitch.json

Server image now supports importing apps with custom user data cluster configuration. 
Also fixed expected results for tests for #7022 with new server image. 
Closes #6942

Include ignored custom user data tests

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.kt
realm/realm-annotations-processor/src/test/resources/io/realm/some_test_NullTypesRealmProxy.java
realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java

Closes https://github.com/realm/realm-java/issues/7084
Fixes a bug when calling `toString()` on a RealmObject with a `byte[]` field that contained the value `null`.

Fix NullPointerException in toString

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/UTFStrings.java
realm/realm-library/src/androidTest/java/io/realm/UTFStringsTests.java
realm/realm-library/src/main/cpp/util.cpp

Show a more descriptive message for UTF encoding exceptions
This PR rebases the changes from #7091 into releases.
Error descriptions are extracted from the comments in [utf8.hpp : to_utf8()](https://github.com/realm/realm-java/blob/0e1464114782f88165309bd0d73d13a8fde72ab7/realm/realm-library/src/main/cpp/utf8.hpp#L260)
closes #7081

Show error messages for UTF decoding issues

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/internal/ColumnIndices.java

ColumnIndices was not thread-safe and could throw concurrent modification exceptions if the app tried, at the same time, to refresh a schema and to get info about a model.
closes #6876

Fixes concurrent modification exception in ColumnIndices class

---

Jenkinsfile
build.gradle
tools/publish_release.sh

This adds support for fully automating 10.x releases by using tags.
After this is merged the only thing needed to publish a release is to tag a commit and then build the branch. I don't believe CI runs automatically when just pushing a tag, so I suspect this must be triggered manually (needs to be tested).
I tested as many parts of this script as I could but the entire thing hasn't run yet on CI so I suspect there are still some bugs around making it run correctly on CI with credentials.
Once reviewed I plan to use this to release BETA.7 as validation.

Automate 10.x releases

---

Jenkinsfile
realm/gradle.properties

This PR does 2 things:
----
Attempt to combat `java.lang.OutOfMemoryError: Java heap space` when building our v10 branch for CI which build and test both base and objectServer variants. Not sure why we suddenly started running out of memory for the builds.
Note, no effect should be visible on this PR as this error has only been observed on the v10 branch.
----
Disable OJO uploads when doing full release builds as we can only host SNAPSHOT versions on OJO
----

Fix issues with building on v10

---

CHANGELOG.md
dependencies.list
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/ApiKeyAuthTests.kt
realm/realm-library/src/objectServer/java/io/realm/internal/network/OkHttpNetworkTransport.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/Credentials.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/auth/EmailPasswordAuth.java

Closes #7117 
Only partially closes #7116 . Even with the correct argument order we are still getting "Invalid token data", but this also happens on JS, so until proven otherwise I'm going with the assumption the problem is in either ObjectStore or on the server. I'm trying to verify if the endpoint we are hitting for resetPassword is correct in order to rule out OS, but this PR should be in a reviewable state nonetheless.

Fix incorrect HTTP headers and resetPassword args

---

realm/kotlin-extensions/src/androidTest/kotlin/io/realm/CoroutineTests.kt
realm/kotlin-extensions/src/main/kotlin/io/realm/kotlin/RealmExtensions.kt

Fixes https://github.com/realm/realm-java/issues/7136
- Made `executeTransactionAwait` cooperative (although it won't cancel the transaction itself)
- Fixed bogus test so that it blocks until the coroutine job is cancelled with `cancelAndJoin`
- Added tests with heavy transactions that explore cooperation for cancellation
- Added and fixed some documentation

Fix flaky test: executeTransactionAwait

---

realm/kotlin-extensions/build.gradle

Fixes #7107
The `assemble` task has to be run explicitly before `publishObjectServerPublicationPublicationToMavenLocal`. For some reason writing `publishToMavenLocal.dependsOn assemble` is not enough anymore, so we needed to ensure this precendece by adding `builtBy` to `basePublication` and `objectServerPublication`.

Flaky build - extensions:publishObjectServerPublicationPublicationToMavenLocal

---

CHANGELOG.md
realm/realm-library/proguard-rules-consumer-common.pro

This PR fixes the crashes in JNI when trying to instantiate ObjectIds' or Decimal128s' with Proguard enabled.

Keep constructors for Decimal128 and ObjectId

---

CHANGELOG.md
realm-annotations/src/main/java/io/realm/annotations/PrimaryKey.java
realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/ObjectIdPrimaryKey.java
realm/realm-library/src/main/cpp/io_realm_internal_OsObjectStore.cpp
realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp

Fixes #7189
We didn't support adding ObjectId primary keys in migrations. This PR addresses this issue.

Add support for addPrimaryKey with ObjectId keys on migrations

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.kt
realm/realm-library/src/androidTest/java/io/realm/RealmJsonAbsentPrimaryKeyTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmJsonNullPrimaryKeyTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmJsonTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/PrimaryKeyAsObjectId.java

Closes #7197 
- Fixed logic in `RealmProxyClassGenerator` to instantiate an `ObjectId` instead of directly casting a string.
- Fixed tests for absent and null PK during json generation.
- Added missing test for creating objects with an `ObjectId` PK.

Fix wrong logic in annotation processor for generating ObjectId PKs

---

CHANGELOG.md
realm/kotlin-extensions/src/androidTest/kotlin/io/realm/CoroutinesTests.kt
realm/realm-library/src/main/java/io/realm/internal/coroutines/InternalFlowFactory.kt

Fixes #7211 
It is possible that a job is cancelled and the listener keeps emitting object updates. This could result in an `AbortFlowException`. To fix this we have to make the flow emissions cooperative.

Ensure flow emissions are cooperative after the job has been cancelled.

---

CHANGELOG.md
realm/realm-annotations-processor/build.gradle
realm/realm-annotations-processor/src/main/java/io/realm/processor/ClassCollection.kt
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.kt
realm/realm-annotations-processor/src/main/java/io/realm/processor/Utils.kt

Fixes https://github.com/realm/realm-java/issues/7213
kapt runs within modules so `classCollection` contains only processed classes from the particular module. However, the embedded class could be in another transitive module, therefore  relying on `classCollection` could throw an exception because we might be trying to lookup a class processed from another round/module.
The usage of `classCollection.getClassFromQualifiedName` is mainly introduced to know if the type we're processing is embedded or not. In this PR we introduce an alternative way to obtain this information without relying necessarily on the `classCollection`, we use alternatively the JDK compiler tools API.

Fixing annotation processor to safely check for embedded classes

---

CHANGELOG.md
realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.kt

Fixes a missed case in https://github.com/realm/realm-java/pull/7220 covering the usage of a type (defined in another module) in a `RealmList`

KAPT complementary fix for missed edge case in https://github.com/realm/realm-java/pull/7220

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/RealmObject.java

Closes #7216
- Added @Nullable annotation to the input parameter in public static <E extends RealmModel> boolean isValid(@Nullable E object) to avoid mismatch warning from Kotlin in case the object type is nullable as the function itself accepts null values.
- Updated to latest OS.

Add @Nullable annotation to input parameter in RealmObject.isValid(obj)

---

Jenkinsfile
build.gradle
tools/publish_release.sh

Closes #7264 
This PR fixes two issues with the current release process.
1) The Javadoc stylesheet was uploaded with the wrong Content-type, `plain/text` instead of `text/css`. This caused it to not be applied to our Javadoc
2) We had a redirect from `/latest/index.html` to `/<version>/index.html`, but that doesn't work for links further down the tree. The ideal solution would have been to use symlinks, but this is not supported by S3, so instead we are uploading the docs twice, once to `latest` and once to a versioned folder.

Improve release steps

---

realm/realm-library/src/androidTest/java/io/realm/RealmResultsTests.java

This just adds a test validating that https://github.com/realm/realm-core/issues/3492 actually fixed escaping when serializing objects to JSON. 
Closes #6649

Add test for escaped JSON output from results

---

realm/realm-library/src/androidTest/java/io/realm/CollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/ManagedRealmCollectionTests.java
realm/realm-library/src/androidTest/java/io/realm/OrderedRealmCollectionIteratorTests.java
realm/realm-library/src/androidTest/java/io/realm/RealmListTests.java
realm/realm-library/src/androidTest/java/io/realm/UnManagedRealmCollectionTests.java
realm/realm-library/src/main/java/io/realm/OrderedRealmCollectionSnapshot.java
realm/realm-library/src/main/java/io/realm/RealmCollection.java
realm/realm-library/src/main/java/io/realm/RealmList.java
realm/realm-library/src/main/java/io/realm/RealmMap.java
realm/realm-library/src/main/java/io/realm/RealmResults.java

- Moved implementation of `Freezable` interface to `RealmCollection`.
- Restored previously removed test cases that used `RealmCollectionMethod.FREEZE`.

Dictionary - move implementation of Freezable interface to RealmCollection

---

realm/realm-library/build.gradle
realm/realm-library/src/main/cpp/CMakeLists.txt
realm/realm-library/src/main/cpp/io_realm_internal_OsObjectStore.cpp
realm/realm-library/src/main/cpp/util.cpp
realm/realm-library/src/main/java/io/realm/MutableRealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/internal/OsObjectStore.java

- Only build relevant targets in Core, i.e. don't build FFI
- Update to latest master branch commit and fix related issues. Most noticeably, some helper methods were removed. These helper methods where designed to make it easier to work with the primary key table found in Core 5, but this was removed in Core 6. But it also meant that some extra checks are now missing. I added them to Java as a temporary solution.

Disable building FFI

---

CHANGELOG.md
Dockerfile
Jenkinsfile
dependencies.list
realm/realm-library/build.gradle
realm/realm-library/src/main/cpp/CMakeLists.txt

Upgrade the NDK 22, this brings a lot of benefits:
*  Enable a new linker flag that hide native library symbols (i.e. OpenSSL). Not sure why this wasn't enabled before, but it shaved almost 1MB from the x86_64 binary. 
* JS discovered that all Android builds statically linked zlib, this has been fixed in Core.
* With the NDK upgrade we moved from gold to lld linker. 
I haven't done a thorough analysis of savings yet, but for x86_64 builds we went from 8.04 MB to 5.8 MB. So an significant improvement. However, the text-based query parser should be stripped in this built, so we will discover how much this adds when that support is added.
TODO:

Add support for NDK22

---

realm/realm-library/src/androidTest/java/io/realm/internal/OsResultsTests.java
realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp
realm/realm-library/src/main/java/io/realm/OrderedRealmCollectionImpl.java
realm/realm-library/src/main/java/io/realm/RealmResults.java
realm/realm-library/src/main/java/io/realm/internal/OsResults.java

Needed for #7077.
In order to honour Java's `Map.keySet` and `Map.values` we need to support primitive types in `RealmResults` as OS delivers these as `Results`. Currently, only `Map.values` works and only if our dictionary contains Realm models, failing otherwise.
To address this I have abstracted a bit further the `OrderedRealmCollectionImpl` class by adding an abstract `CollectionOperator` class to handle how to iterate over results depending on whether the collection contains models or primitive values.
This PR does **NOT** add support for primitive queries, which will still be disallowed.
Testing is not possible in this PR because of precisely the lack of query support, but the implementation has been tested separately against dictionaries by using `Map.values` and `Map.keySet`.

RealmResults - add support for Realm primitive data types (no queries)

---

CHANGELOG.md
realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp

Updated to latest core master and fixed breaking change in `set_embedded`: where the old version would return `false` the new one throws, so we can assume that if we catch an exception we should then return `false` and `true` if nothing happened.

Update master to latest core master

---

realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp
realm/realm-library/src/main/cpp/java_object_accessor.hpp
realm/realm-library/src/main/java/io/realm/RealmQuery.java
realm/realm-library/src/main/java/io/realm/internal/TableQuery.java

This PR adds support for argument substitution on the brand new query raw predicates.
It accepts any Realm value or Realm object as arguments.

Add argument substitution on raw query predicates

---

realm/realm-library/src/androidTest/assets/list_alltypes_primarykey.json
realm/realm-library/src/androidTest/assets/nulltypes.json
realm/realm-library/src/androidTest/java/io/realm/RealmJsonTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/DefaultValueOfField.java
realm/realm-library/src/androidTest/java/io/realm/entities/PrimitiveListTypes.java
realm/realm-library/src/main/cpp/java_object_accessor.hpp
realm/realm-library/src/main/java/io/realm/ProxyUtils.java
realm/realm-library/src/main/java/io/realm/internal/objectstore/OsObjectBuilder.java
realm/realm-library/src/testUtils/java/io/realm/entities/AllTypesPrimaryKey.java

Add missing tests for JSON import on ObjectId and Decimal128
Fixes importing null items on non-null lists
Fixes adding null decimal128 in a list get transformed in a Decimal128(0)

Add missing tests for json import on objectid and decimal128

---

realm/realm-library/src/overview.html

These changes resolve a series of redirect chains that are currently in the Realm SDK docs and are negatively affecting search engine performance.
(I'm on the Documentation Platform team at MongoDB and this was identified as part of a broader SEO project that we're currently working on.)

Use canonical URLs for docs links on overview page

---

realm/realm-library/src/androidTest/kotlin/io/realm/MixedTests.kt
realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java
realm/realm-library/src/main/java/io/realm/MixedOperator.java
realm/realm-library/src/main/java/io/realm/internal/core/NativeMixed.java

Given a Mixed which inner value referenced is an object whose schema isn't backed by an`InmutableObjectSchema`, if we retrieve its inner value it would throw a RealmException.
This PR allows falling back to a `DynamicRealmObject` in such cases.
Example:
```
ObjectWithMixed objectWithMixed = realm.where(ObjectWithMixed.class).findFirst();
// the mixed content object schema is missing in the realm
assertEquals(DynamicRealmObject.class, objectWithMixed.mixed.getValueClass());
```

Fallback to dynamic realm models on classes without an schema

---

realm/realm-library/src/androidTest/kotlin/io/realm/ManagedDictionaryTesters.kt
realm/realm-library/src/androidTest/kotlin/io/realm/ParameterizedDictionaryTests.kt
realm/realm-library/src/main/cpp/io_realm_internal_objectstore_OsObjectBuilder.cpp

This PR adds support copyOrUpdate on a dictionary of objects and using null values on objects.

Add support for copyOrUpdate dictionary of objects

---

realm/realm-library/src/androidTest/kotlin/io/realm/ManagedDictionaryTesters.kt
realm/realm-library/src/androidTest/kotlin/io/realm/ParameterizedDictionaryTests.kt
realm/realm-library/src/androidTest/kotlin/io/realm/UnmanagedDictionaryTesters.kt
realm/realm-library/src/androidTest/kotlin/io/realm/entities/DictionaryAllTypes.java
realm/realm-library/src/main/java/io/realm/ManagedMapManager.java
realm/realm-library/src/main/java/io/realm/RealmDictionary.java
realm/realm-library/src/main/java/io/realm/RealmMap.java

Added missing constraints from Set interface with regards to throwing exceptions when invalid parameters are provided to certain functions and tests for these.

Dictionary - added missing constraints from Java Map interface for invalid parameters

---

realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/ProgressListenerTests.kt

Verified that initial progress listeners are triggered even though there are no new data with the latest server image.
Closes #6976

Reenable ignored progress listener tests

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SessionTests.kt
realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp
realm/realm-library/src/objectServer/java/io/realm/mongodb/AppException.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/sync/Sync.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/sync/SyncSession.java

Closes https://github.com/realm/realm-java/issues/7363
Turned out we had two bugs around exception handling
1) Exception messages in `AppException` was not correctly stored in the (standard) message property of `RuntimeException`
2) We didn't correctly pass on Client Reset error messages to users in the `AppException.errorMessage` field.

Correctly propagate error messages to users for App Exceptions

---

realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.kt
realm/realm-annotations-processor/src/test/resources/io/realm/some_test_AllTypesRealmProxy.java
realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java
realm/realm-library/src/androidTest/kotlin/io/realm/DictionaryTester.kt
realm/realm-library/src/androidTest/kotlin/io/realm/ManagedDictionaryTesters.kt
realm/realm-library/src/androidTest/kotlin/io/realm/ParameterizedDictionaryTests.kt
realm/realm-library/src/androidTest/kotlin/io/realm/UnmanagedDictionaryTesters.kt

A guard against unmanaged objects when calling a dictionary setter has been added in the proxy code. This way we control that only managed objects can be put.
The semantics for `RealmDictionary<Mixed>` containing `RealmModel`s are different though: if a setter is called using a dictionary containing a `Mixed` instance containing an unmanaged `RealmModel`, that model will be implicitly copied to Realm since that is the default behaviour for lists and sets as well.

Dictionary - fix crash when calling a dictionary setter with unmanaged objects (also for Mixed)

---

CHANGELOG.md

Update to Realm Core 10.6.1, which contains a number of important bug fixes.
This also adds support for automatic Realm file backup when the file format is updated. This feature isn't used until next time we upgrade the fileformat. Which will be 10.5.0 (which contains the new datatypes).

Update to Core 10.6.1.

---

realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java
realm/realm-library/src/androidTest/kotlin/io/realm/entities/embedded/EmbeddedSimpleParent.kt

Adds a test to validate that it is possible to perform a schema migration that involves embedded objects.

Add migration test for embedded objects

---

CHANGELOG.md
realm/realm-library/src/androidTest/kotlin/io/realm/realmany/RealmAnyQueryTests.kt
realm/realm-library/src/main/java/io/realm/RealmAny.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java

When doing the `10.6.0-BETA.1` release I bumped the Core version which resulted in some changed behavior around sorting of RealmAny. 
This PR fixes those tests and expand the documentation to be more clear about the behavior. 
The changes are not listed in the changelog because they where already released in `BETA.1`

Fix tests and docs around RealmAny sorting 

---

realm/realm-library/src/androidTest/kotlin/io/realm/ManagedDictionaryTesters.kt
realm/realm-library/src/androidTest/kotlin/io/realm/ManagedSetTester.kt
realm/realm-library/src/androidTest/kotlin/io/realm/RealmModelManagedSetTester.kt
realm/realm-library/src/main/java/io/realm/DynamicRealmObject.java

Implement string conversion for `DynamicRealmObject` `RealmDictionary` and `RealmField` fields.
It will render the type and how many elements the field contains:
- `exampleSetField:RealmSet<String>[4]`
- `exampleDictionaryField:RealmDictionary<String>[8]`

Support toString DynamicRealmObject on dicts and sets fields

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmInterprocessTest.java
realm/realm-library/src/main/cpp/CMakeLists.txt
realm/realm-library/src/testUtils/java/io/realm/services/RemoteProcessService.java

Closes https://github.com/realm/realm-java/issues/7321
A fix for #7321 is currently being implemented in Core, but can currently only be caught on Android 12 Emulator preview images.
This PR re-enables interprocess tests and adds a test for interprocess notifications. The fix has been verified to work manually, but since the first attempt didn't account for multiprocess notifications, I added a test for it as part of the PR. But generally, any test that expects multiple notifications would break.

Fix notifications on Linux 5.5 and above

---

build.gradle

- Make room for Kotlin SDK to be at /realm-sdks/kotlin/
- Removed redirect logic, since it will no longer be required

Update docs upload script to move kotlin-extensions into java directory

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/RealmCache.java
realm/realm-library/src/syncIntegrationTest/kotlin/io/realm/SyncedRealmIntegrationTests.kt
tools/sync_test_server/Dockerfile
tools/sync_test_server/start_server.sh

An attempt at capturing #7517 
We have a lot of unit tests covering `Realm.getInstance()` so I suspect the bug is only for `Realm.getInstanceAsync()` but I haven't been able to reproduce it yet.
But both @hennasingh and @mohit-sharma-87 have reported seeing it.

Attempt to capture bug with waitForInitialRemoteData 

---

README.md

Adds a Maven central pill to replace the Bintray one that was removed on a previous PR.

Add maven central pill to Readme

---

CHANGELOG.md
realm/realm-library/src/objectServer/java/io/realm/mongodb/User.java

Spinoff from https://github.com/realm/realm-java/issues/7501 where the discussion there revealed that we have the wrong documentation for logout. Also, .NET already has public methods for removing users, as this is also the only way to delete User Realms easily. So we should expose them in Java as well.
**TODO**

Make User.remove() and User.removeAsync() public again

---

realm/realm-library/build.gradle

CI won't be able to build this PR as it is a part of #7539.
Fixes the Javadoc generation by pointing the classpath to the project compiled classes and dependencies.
It is no longer required to point to the Android Sdk's local reference as google [has published a `package-list` with their developer documentation.](https://stackoverflow.com/a/63547141)

Fix Javadoc generation on JDK11

---

CHANGELOG.md
realm-transformer/src/main/kotlin/io/realm/transformer/RealmTransformer.kt

Most CI services will set the environment variable `CI` to some value, so it's a good idea to check for it and make sure we don't count CI builds as actual developers.
* [Github Actions](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables)
* [Travis CI](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables)
* [Appveyor](https://www.appveyor.com/docs/environment-variables/)
* [Jenkins](https://github.com/jenkinsci/jenkins/pull/5370)
It also modifies the check for `REALM_DISABLE_ANALYTICS` to check for existence of the environment variable rather than value. This feels more intuitive as it will also handle cases such as setting it to `1` as well as typos. My thinking here is that if there's such an environment …

Disable analytics on CI

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/internal/RealmNotifierTests.java
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SyncedRealmTests.kt
realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp
realm/realm-library/src/main/cpp/io_realm_mongodb_sync_Sync.cpp
realm/realm-library/src/main/cpp/java_binding_context.cpp
realm/realm-library/src/objectServer/java/io/realm/mongodb/sync/Sync.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/sync/SyncSession.java
realm/realm-library/src/syncIntegrationTest/kotlin/io/realm/SyncSessionTests.kt

This PR fixes an issue where crashes inside background change listeners would not get correctly detected, thus crashing the JavaBindingContext in unrelated ways when accessing the JNIEnv. 
Sending notifications on background looper threads involves a number of callbacks from and to JNI and each of these steps needs a guard against this. It isn't possible to test for each specific callback, so I just added a test for the most important one: Exceptions inside the actual callback.
This case was detected when using coroutines with a custom looper Dispatcher. Canceling the scope would result in a `CoroutineException` inside the callback, but instead of the "real" exception people would see `JNI DETECTED ERROR IN APPLICATION: JNI NewLocalRef called with pending exception …

Fix notification exceptions not getting correctly detected in JNI

---

realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/Realm.java

Seems to be a javadoc issue, not your fault.
Note that the links don't work in the description: https://docs.mongodb.com/realm-sdks/java/latest/io/realm/Realm.Transaction.html
Because they try to relatively link... within Realm.Transaction, rather than resolving the containing class methods. Fix seems to be fully qualified links.

Fix broken links in Realm.Transaction doc

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SyncConfigurationTests.kt
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SyncedRealmTests.kt
realm/realm-library/src/objectServer/java/io/realm/internal/SyncObjectServerFacade.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/sync/Sync.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/sync/SyncConfiguration.java

Closes #7598.
It isn't possible to add an integration test for this as our integration tests uses a String partition key, but I verified a server roundtrip using a manual test where I modified the server.

Add support for UUID's as partition values.

---

gradle.properties
realm/gradle.properties

On PR #7606 we set the disabling unified testing pipeline flag into the root gradle project. This setting is not propagated into the directory Realm as they are separate projects.
This PR moves the flag into the Realm project gradle.properties.

Move UTP disabling flag into the correct gradle.properties

---

CHANGELOG.md
realm/realm-library/build.gradle
realm/realm-library/src/androidTest/kotlin/io/realm/RealmAnyCollectionTests.kt
realm/realm-library/src/main/cpp/java_class_global_def.cpp
realm/realm-library/src/testUtils/kotlin/io/realm/entities/AllKotlinTypes.kt

Fix crashes for RealmAny on ARM 32 bit architectures

---

realm/gradle.properties

The project fails to build if we don't build core as part of the project. Has been like that for a while, just didn't hunt down why my local build was failing since my environment has been out of sync while working only on realm-kotlin. With realm-java brought up to JAVA11/Cmake 3.21.4 it was a bit easier to chase. 
Don't know if we should disable the logic completely, but at least a fresh clone in a raw environment will not fail to build ... due to this.

Build core from source as default

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/MutableSubscriptionSetTests.kt
realm/realm-library/src/main/cpp/io_realm_internal_objectstore_OsMutableSubscriptionSet.cpp

This PR fixes a bug in Flexible Sync that prevented declaring multiple anonymous subscriptions on a Realm Object.

Flexible Sync bug fix on multiple anonymous subscriptions.

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/FlexibleSyncConfigurationTests.kt
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SyncConfigurationTests.kt
realm/realm-library/src/objectServer/java/io/realm/mongodb/sync/SyncConfiguration.java

This PR allows setting a custom filename on partition and flexible synced Realms.

Allow setting filename on partition and flexible sync Realms

---

realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/MongoClientTest.kt

Reenable the following tests in `MongoClientTest.kt`:
- findOneAndUpdate_noUpdates
- findOneAndReplace_noUpdates
- findOneAndUpdate_emptyCollection
- findOneAndReplace_noUpsert
- findOneAndReplace_noUpdates
closes #7238

Reenable tests for MongoCollection.findOneAndUpdate

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/Realm.java

Currently Realm is not able to run on Instant apps, trying to run it would result on a `Permission denied` while trying to open a Realm, that is hard to reason about.
With this PR we check if Realm is being initialized on an Instant app and if so a `RealmError` is thrown stating that Instant apps are not currently supported.
Manually tested with an Instant App.

Throw exception when initializing Realm on an Instant app

---

realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/DynamicRealm.java
realm/realm-library/src/main/java/io/realm/ImportFlag.java
realm/realm-library/src/main/java/io/realm/ManagedListOperator.java
realm/realm-library/src/main/java/io/realm/Realm.java
realm/realm-library/src/main/java/io/realm/RealmAny.java
realm/realm-library/src/main/java/io/realm/RealmObject.java
realm/realm-library/src/main/java/io/realm/RealmQuery.java
realm/realm-library/src/main/java/io/realm/RealmSchema.java
realm/realm-library/src/main/java/io/realm/RealmSet.java
realm/realm-library/src/main/java/io/realm/exceptions/RealmError.java
realm/realm-library/src/main/java/io/realm/exceptions/RealmException.java

This PR contains fixes of some minor typos in the documentation.
The case `a {@link android.os.Looper}` vs. `an {@link android.os.Looper}` is a bit ambiguous, depending on how it might be displayed by an IDE, but I think it should at least be handled consistently within the project.

Fixed some typos

---

dependencies.list
tools/sync_test_server/bind_android_ports.sh
tools/sync_test_server/start_local_server.sh
tools/sync_test_server/stop_local_server.sh

Import scripts and configurations from `realm-kotlin` to enable running the baas server locally on Apple silicon devices.

Add support for running baas server locally

---

realm/realm-library/src/main/java/io/realm/BaseRealm.java
realm/realm-library/src/main/java/io/realm/internal/OsSharedRealm.java
realm/realm-library/src/main/java/io/realm/mongodb/sync/SubscriptionSet.java

Note, this is just a work-around that has the downside that `SubscriptionSet` now leaks into the public API for the base library.
I tried to find the root cause, but after running a bit in circles, it is probably going to take longer than what we have time for right now. So I created https://github.com/realm/realm-java/issues/7681 to track it.

Fix unit tests not running for base library.

---

realm/realm-library/build.gradle

The native build task has a dependency for each abi, so we need to add a dependency to the Java header generating task for each of the native build tasks.

Add dependencies between native build tasks and Java header generation

---

CHANGELOG.md
realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java
realm/realm-library/src/androidTest/java/io/realm/entities/migration/HandleBackLinksChild1.java
realm/realm-library/src/androidTest/java/io/realm/entities/migration/HandleBackLinksChild2.java
realm/realm-library/src/androidTest/java/io/realm/entities/migration/HandleBackLinksParent1.java
realm/realm-library/src/androidTest/java/io/realm/entities/migration/HandleBackLinksParent2.java
realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp
realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java
realm/realm-library/src/main/java/io/realm/internal/Table.java

Closes #7769
Added support for automatic handling of back links during migrations.

Add automatic handling of orphan embedded objects during migrations

---

CHANGELOG.md
Jenkinsfile
gradle-plugin/src/main/kotlin/io/realm/gradle/Realm.kt
realm-transformer/src/main/kotlin/io/realm/transformer/RealmTransformer.kt

This PR fixes https://github.com/realm/realm-java/issues/7771 by disabling the transformer API on Unit Test components. 
There is some issue related in how the processed classes from the transformer are fed into the unit test task that does not allow the runner to resolve them.
Because Realm is not available in JVM and unit tests, disabling the Realm transformer has the same effect as applying the transformer on a Unit test, tests would only be able to use unmanaged versions of the objects.
Filed issue in google tracker: https://issuetracker.google.com/issues/270885482
The PR also fixes https://github.com/realm/realm-java/issues/7736 that prevented instrumented tests to run because of the Realm dependencies being not present in the configuration.

Allow executing instrumented and unit tests with the new transformer api release

---

CHANGELOG.md
Dockerfile
dependencies.list

This updates Core to 13.6.0. I didn't update to 13.7.0, since that includes some breaking changes to logging that might end up being reverted. This will be discussed Thursday.
Also update to CMake 3.22.1, which is what gets shipped with Android Studio as the default.

Update to Core 13.6.0

---

realm-transformer/src/main/kotlin/io/realm/transformer/RealmTransformer.kt

This PR reworks how we track kotlin usage at compile time. The previous approach triggered this warning with more recent Gradle/AGP versions:
```
Configuration '_agp_internal_javaPreCompileDebugAndroidTest_kaptClasspath' was resolved during configuration time.
This is a build performance and scalability issue.
See https://github.com/gradle/gradle/issues/2298
```
It also seemed like our old approach of tracking `kotlin-sdk` dependencies didn't report the correct result. This might be due to the Kotlin SDK being pulled as a transitive dependency of some of the other mandatory dependencies. 
I have tested the new approach against our `examples` and the detection across all the various projects yields:
```
USESKOTLIN: app false
USESKOTLIN: architectureComponentsExample false
USESKOTLIN: …
```

Track kotlin usage without inspecting configurations in configuration phase

---

CHANGELOG.md
realm/realm-annotations-processor/build.gradle
realm/realm-annotations-processor/src/main/java/io/realm/processor/Utils.kt

The fix introduced in https://github.com/realm/realm-java/pull/7807 turned out to not be enough.
I was testing the previous approach by manually unzipping the jar, and modifying the MANIFEST.MF file and then re-zipping the jar. I'm not 100% sure what is going on, but doing that seemed to cause issues with the build so some variants would compile successfully. However, recreating the SNAPSHOT artifact using the `publishToMavenLocal` would always reproduce the error.
It looks like the problem might be the presence of `Manifest-Version`, but there doesn't appear to be a way to remove this using the Gradle API.
So I decided to instead refactor our annotation processor to APIs available in Java 11. This unfortunately broke Google's Compile Testing framework which still has not been updated, …

Use Java 11 API's for checking embedded properties in the annotation processor

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SessionTests.kt
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SyncedRealmTests.kt
realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp
realm/realm-library/src/main/cpp/io_realm_internal_objectstore_OsAsyncOpenTask.cpp
realm/realm-library/src/main/cpp/io_realm_internal_objectstore_OsWatchStream.cpp
realm/realm-library/src/main/cpp/io_realm_mongodb_sync_SyncSession.cpp
realm/realm-library/src/main/cpp/java_network_transport.hpp
realm/realm-library/src/main/cpp/util.hpp
realm/realm-library/src/objectServer/java/io/realm/internal/objectstore/OsAsyncOpenTask.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/ErrorCode.java
realm/realm-library/src/objectServer/java/io/realm/mongodb/sync/Sync.java
realm/realm-library/src/syncIntegrationTest/kotlin/io/realm/SyncSessionTests.kt
realm/realm-library/src/syncTestUtils/kotlin/io/realm/TestSyncConfigurationFactory.kt

Closes #7823 
This PR accomplishes three things:
- It fixes a few places where we send the wrong native error code to Java, resulting it being mapped to UNKNOWN.
- It unifies our mapping of the native category to the Java equivalent. We had multiple places this was happening, and they were slightly divergent resulting in unexpected behavior.
- Also, after the sync error refactors, most Protocol and session errors had ended up in the wrong category, resulting in them being reported as UNKNOWN.

Unify sync error code mapping

---

CHANGELOG.md
realm/realm-library/src/main/java/io/realm/internal/OsRealmConfig.java

A null pointer exception is thrown when a proxy is configured. It is reproducible in the emulator by enabling it in the WIFI settings. 
The issue is caused by the backported logic from getHostString, it was wrong. Fixed by porting the actual expected logic.
Tested on an emulator and physical devices.
Closes #7828

Fix null pointer exception when proxy is enabled.

---

CHANGELOG.md
realm-transformer/src/main/kotlin/io/realm/transformer/ByteCodeModifier.kt

Closes #7840.
Incremental builds would not modify the accessors correctly. The issue is caused because the function `isRealmModelClass` fails to detect valid Realm models in incremental builds.
The issue was introduced when this function was refactored and failed to add a negation. [Original function](https://github.com/realm/realm-java/blob/7219b6a9bc114775a876ef2f92cf920816cc89b2/realm-transformer/src/main/kotlin/io/realm/transformer/ByteCodeModifier.kt#L184).
Tested manually and reviewed the generated bytecode.

Fix incremental builds missing accessors

---

CHANGELOG.md
realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/internal/network/NetworkRequestTests.kt
realm/realm-library/src/objectServer/java/io/realm/internal/network/NetworkRequest.java
realm/realm-library/src/objectServer/java/io/realm/internal/network/VoidNetworkRequest.java

Closes [#7848 ](https://github.com/realm/realm-java/issues/7847)
It turns out it was possible to get into a situation where a NetworkRequest would sometimes return `null` even though it shouldn't. This could happen if you cancel the `RealmAsyncTask` controlling the network request while the request was running.
It wasn't possible to add a unit test that would fail consistently in that case, so Instead I added something more low-level that ensured that we failed correctly if the request was interrupted.

Fix NetworkRequest being able to return invalid values

---

CHANGELOG.md
realm/realm-library/build.gradle
realm/realm-library/src/main/cpp/CMakeLists.txt

Starting from the upcoming Android 15, the possibility for devices configured with a memory page size of 16 KB (rather than the default 4 KB) becomes available to OEMs. This has an impact on how native code must be packed into Android applications in order to prevent crashes at runtime when unaligned code is being loaded on these devices (ref https://github.com/realm/realm-java/issues/7894).
This PR applies [the suggested migration steps](https://developer.android.com/guide/practices/page-sizes) for 16 KB ELF packaging to the output of `realm-library`. As I did not want to upgrade the entire stack to AGP 8.3+ and NDK 27+, it follows the "legacy path" that yields the same results: After building the native libraries with these flags, calls to `Realm.init()` no longer cause an immediate …

Use 16 KB ELF alignment for shared native libraries

---

realm/realm-library/proguard-rules-consumer-objectServer.pro

This PR should fix a reported crash:
```
E  /Users/nabil.hachicha/Dev/realm/release/realm-java/realm/realm-library/src/main/cpp/jni_util/java_method.cpp:33: [realm-core-13.26.0] Assertion failed: m_method_id != nullptr with (method_name, signature) =  ["onChange", "(B)V"]
<backtrace not supported on this platform>
!!! IMPORTANT: Please report this at https://github.com/realm/realm-core/issues/new/choose
```
Originating from [HELP-58718](https://jira.mongodb.org/browse/HELP-58718)

Add missing obfuscation configuration
